package netahsilat;

import io.testproject.addon.ImapMailOperations;
import io.testproject.addon.NetahsilatUtills;
import io.testproject.addon.RandomDataGenerator;
import io.testproject.addon.WebExtensions;
import io.testproject.sdk.drivers.ReportingDriver;
import io.testproject.sdk.drivers.web.RemoteWebDriver;
import io.testproject.sdk.interfaces.junit5.ExceptionsReporter;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;

import java.util.concurrent.TimeUnit;
import java.util.stream.Stream;

/**
 * This class was automatically generated by TestProject
 * Project: Quality Museum Project
 * Test: C1341 Ekleme İşlemi Kullanıcıya Bildirilsin mi (NTH-8239)
 * Generated by: Ahmet Furkan SIMSEK (furkan.simsek@qualitymuseum.com)
 * Generated on Thu Oct 06 12:24:43 GMT 2022.
 */
@DisplayName("C1341 Ekleme İşlemi Kullanıcıya Bildirilsin mi (NTH-8239)")
public class C1341 implements ExceptionsReporter {
  public static WebDriver driver;

  @BeforeAll
  static void setup() throws Exception {
    driver = new RemoteWebDriver("wThDxIHw4zNaCydjAhcfe81WrQPYlMBFI7FPwUwV8M41", new ChromeOptions(), "Ahmet Furkan SIMSEK");
  }

  /**
   * In order to upload the test to TestProject need to un-comment @ArgumentsSource and set in comment the @MethodSource
   * @org.junit.jupiter.params.provider.ArgumentsSource(io.testproject.sdk.interfaces.parameterization.TestProjectParameterizer.class) */
  @DisplayName("C1341 Ekleme İşlemi Kullanıcıya Bildirilsin mi (NTH-8239)")
  @ParameterizedTest
  @MethodSource("provideParameters")
  void execute(String ApplicationURL, String userName, String password, String RandomNumber) throws
      Exception {
    // set timeout for driver actions (similar to step timeout)
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);
    By by;
    boolean booleanResult;
    MethodLogoutlogin methodlogoutlogin;
    WebExtensions.SelectOptionbyVisibleText selectOptionbyVisibleText;
    ImapMailOperations.ReadSpecificsMail readSpecificsMail;
    NetahsilatUtills.ClickUntilGone clickUntilGone;
    RandomDataGenerator.GenerateNumberInRange generateNumberInRange;
    ImapMailOperations.DeleteAllMails deleteAllMails;

    // 1. Delete All Mails
    GeneratedUtils.sleep(500);
    deleteAllMails = ImapMailOperations.deleteAllMails("silinenmusteri","oikevwukloryjuww");
    deleteAllMails = (ImapMailOperations.DeleteAllMails)((ReportingDriver)driver).addons().execute(deleteAllMails);

    // 1. Run Method Logout&Login
    GeneratedUtils.sleep(500);
    methodlogoutlogin = new MethodLogoutlogin();
    methodlogoutlogin.ApplicationURL = ApplicationURL;
    methodlogoutlogin.userName = ProjectParameters.genelEmail;
    methodlogoutlogin.password = ProjectParameters.genelPassword;
    methodlogoutlogin.execute(driver);

    // 3. Move mouse to 'moveUstUyeYonetimi'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("li[class='content']");
    (new Actions(driver)).moveToElement(driver.findElement(by)).perform();

    // 4. Click 'ustUyeYonetimi'
    GeneratedUtils.sleep(500);
    by = By.xpath("//li[4]/a[. = 'ÜYE YÖNETİMİ']");
    driver.findElement(by).click();

    // 5. Click 'altUyeYonetimi'
    GeneratedUtils.sleep(500);
    by = By.xpath("//li[1]/a[. = 'ÜYE YÖNETİMİ']");
    driver.findElement(by).click();

    // 6. Is 'ddYeniUyeTanimi' visible?
    GeneratedUtils.sleep(500);
    by = By.xpath("//div[2]/div/img");
    driver.findElement(by).isDisplayed();

    // 7. Click 'ddYeniUyeTanimi'
    GeneratedUtils.sleep(500);
    by = By.xpath("//div[2]/div/img");
    driver.findElement(by).click();

    // 8. Click 'Yeni Müşteri Tanımla'
    GeneratedUtils.sleep(500);
    by = By.xpath("//a[. = 'Yeni Müşteri Tanımla']");
    driver.findElement(by).click();

    // 9. Generate random number between '100000' and '500000'
    GeneratedUtils.sleep(500);
    generateNumberInRange = RandomDataGenerator.generateNumberInRange("100000","500000");
    generateNumberInRange = (RandomDataGenerator.GenerateNumberInRange)((ReportingDriver)driver).addons().execute(generateNumberInRange);
    RandomNumber = String.valueOf(generateNumberInRange.result);

    // 10. Type 'Silinen' in 'Entity.VendorUser.Name'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_VendorUser_Name");
    driver.findElement(by).sendKeys("Silinen");

    // 11. Type '{{RandomNumber}}' in 'Entity.VendorUser.Surname'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_VendorUser_Surname");
    driver.findElement(by).sendKeys(RandomNumber);

    // 12. Type 'Kd!cyhz4' in 'Entity.EditPassword'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_EditPassword");
    driver.findElement(by).sendKeys("Kd!cyhz4");

    // 13. Type 'Kd!cyhz4' in 'Entity.EditRePassword'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_EditRePassword");
    driver.findElement(by).sendKeys("Kd!cyhz4");

    // 14. Type '14531457' in 'Entity.Code'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_Code");
    driver.findElement(by).sendKeys("14531457");

    // 15. Select options in 'CurrencyTLBtn' with text '[NONE]'
    GeneratedUtils.sleep(500);
    selectOptionbyVisibleText = WebExtensions.selectOptionbyVisibleText("TL");
    by = By.xpath("//select[@id='Entity_CurrencyTypeId']");
    selectOptionbyVisibleText = (WebExtensions.SelectOptionbyVisibleText)((ReportingDriver)driver).addons().execute(selectOptionbyVisibleText, by, -1);

    // 16. Select options in 'Language' with text '[NONE]'
    GeneratedUtils.sleep(500);
    selectOptionbyVisibleText = WebExtensions.selectOptionbyVisibleText("Türkçe");
    by = By.cssSelector("#Entity_LanguageId");
    selectOptionbyVisibleText = (WebExtensions.SelectOptionbyVisibleText)((ReportingDriver)driver).addons().execute(selectOptionbyVisibleText, by, -1);

    // 17. Type '181220121812' in 'Entity.ErpCode'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_ErpCode");
    driver.findElement(by).sendKeys("181220121812");

    // 18. Type 'silinenmusteri@yandex.com' in 'Entity.VendorUser.Email'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_VendorUser_Email");
    driver.findElement(by).sendKeys("silinenmusteri@yandex.com");

    // 19. Select options in 'Entity.SelectedCountry' with text '[NONE]'
    GeneratedUtils.sleep(500);
    selectOptionbyVisibleText = WebExtensions.selectOptionbyVisibleText("Turkey");
    by = By.cssSelector("#Entity_SelectedCountry");
    selectOptionbyVisibleText = (WebExtensions.SelectOptionbyVisibleText)((ReportingDriver)driver).addons().execute(selectOptionbyVisibleText, by, -1);

    // 20. Type '15173369656' in 'Entity.Tckn'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_Tckn");
    driver.findElement(by).sendKeys("15173369656");

    // 21. Type 'Otomasyon Test' in 's2id_autogen2'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#s2id_autogen2");
    driver.findElement(by).sendKeys("Otomasyon Test");

    // 22. Send 'ENTER' key(s)
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#s2id_autogen2");
    (new Actions(driver)).sendKeys(GeneratedUtils.getKeys("ENTER")).build().perform();

    // 23. Select options in 'Entity.PaymentSetDefinitionId' with text '[NONE]'
    GeneratedUtils.sleep(500);
    selectOptionbyVisibleText = WebExtensions.selectOptionbyVisibleText("Furkan Test");
    by = By.cssSelector("#Entity_PaymentSetDefinitionId");
    selectOptionbyVisibleText = (WebExtensions.SelectOptionbyVisibleText)((ReportingDriver)driver).addons().execute(selectOptionbyVisibleText, by, -1);

    // 24. Click 'Entity.SendMailToUser'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_SendMailToUser");
    driver.findElement(by).click();

    // 25. Run Click Until Gone
    GeneratedUtils.sleep(500);
    clickUntilGone = NetahsilatUtills.clickUntilGone(30);
    by = By.xpath("//button[. = 'Tamam']");
    clickUntilGone = (NetahsilatUtills.ClickUntilGone)((ReportingDriver)driver).addons().execute(clickUntilGone, by, -1);

    // 26. Type 'silinenmusteri@yandex.com' in 'SearchVendorNameVN'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#SearchVendorName");
    driver.findElement(by).sendKeys("silinenmusteri@yandex.com");

    // 27. Click 'silinen musteri'
    GeneratedUtils.sleep(500);
    by = By.xpath("//div[contains(text(),'silinenmusteri@yandex.com')] ");
    driver.findElement(by).click();

    // 28. Click 'btnListele'
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(35000, TimeUnit.MILLISECONDS);
    GeneratedUtils.sleep(500);
    by = By.xpath("//button[. = 'Listele']");
    driver.findElement(by).click();
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 29. Is 'Refresh' visible?
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(35000, TimeUnit.MILLISECONDS);
    GeneratedUtils.sleep(500);
    by = By.cssSelector("a[class='t-icon t-refresh']");
    driver.findElement(by).isDisplayed();
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 30. Does 'silinenmusteri@yandex.com' contain 'silinenmusteri@yandex.com'?
    GeneratedUtils.sleep(500);
    by = By.xpath("//div[3]//tr[1]//td[7]");
    Assertions.assertTrue(driver.findElement(by).getText().contains("silinenmusteri@yandex.com"));

    // 31. Click 'buttonBayiSilme'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("img[src*='trash.png']");
    driver.findElement(by).click();

    // 32. Run Click Until Gone
    GeneratedUtils.sleep(500);
    clickUntilGone = NetahsilatUtills.clickUntilGone(30);
    by = By.xpath("//button[. = 'Tamam']");
    clickUntilGone = (NetahsilatUtills.ClickUntilGone)((ReportingDriver)driver).addons().execute(clickUntilGone, by, -1);

    // 33. Output searched string in specific mail
    GeneratedUtils.sleep(500);
    readSpecificsMail = ImapMailOperations.readSpecificsMail("silinenmusteri","oikevwukloryjuww",RandomNumber,"C:\\TestProject\\mail\\C1341.html");
    readSpecificsMail = (ImapMailOperations.ReadSpecificsMail)((ReportingDriver)driver).addons().execute(readSpecificsMail);

    // 34. Navigate to 'file:///C:/TestProject/mail/C1341.html'
    GeneratedUtils.sleep(500);
    driver.navigate().to("file:///C:/TestProject/mail/C1341.html");

    // 35. Does 'id[soyad]' contain '{{RandomNumber}}'?
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(50000, TimeUnit.MILLISECONDS);
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#soyad");
    Assertions.assertTrue(driver.findElement(by).getText().contains(RandomNumber));
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

  }

  @Override
  public ReportingDriver getDriver() {
    return (ReportingDriver) driver;
  }

  @AfterAll
  static void tearDown() {
    if (driver != null) {
      driver.quit();
    }
  }

  private static Stream provideParameters() throws Exception {
    return Stream.of(Arguments.of("https://otomasyon.netahsilatdemo.com/Account/LogOff","","",""));
  }
}
