package netahsilat;

import io.testproject.addon.JSActions;
import io.testproject.addon.NetahsilatUtills;
import io.testproject.addon.WebExtensions;
import io.testproject.sdk.drivers.ReportingDriver;
import io.testproject.sdk.drivers.web.RemoteWebDriver;
import io.testproject.sdk.interfaces.junit5.ExceptionsReporter;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.Select;

import java.util.concurrent.TimeUnit;
import java.util.stream.Stream;

/**
 * This class was automatically generated by TestProject
 * Project: Quality Museum Project
 * Test: C1670 Bireysel Bayi Ekleme
 * Generated by: Ahmet Furkan SIMSEK (furkan.simsek@qualitymuseum.com)
 * Generated on Thu Oct 06 07:09:27 GMT 2022.
 */
@DisplayName("C1670 Bireysel Bayi Ekleme")
public class C1670 implements ExceptionsReporter {
  public static WebDriver driver;

  @BeforeAll
  static void setup() throws Exception {
    driver = new RemoteWebDriver("wThDxIHw4zNaCydjAhcfe81WrQPYlMBFI7FPwUwV8M41", new ChromeOptions(), "Ahmet Furkan SIMSEK");
  }

  /**
   * In order to upload the test to TestProject need to un-comment @ArgumentsSource and set in comment the @MethodSource
   * @org.junit.jupiter.params.provider.ArgumentsSource(io.testproject.sdk.interfaces.parameterization.TestProjectParameterizer.class) */
  @DisplayName("C1670 Bireysel Bayi Ekleme")
  @ParameterizedTest
  @MethodSource("provideParameters")
  void execute(String ApplicationURL, String userName, String password) throws Exception {
    // set timeout for driver actions (similar to step timeout)
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);
    By by;
    boolean booleanResult;
    MethodLogoutlogin methodlogoutlogin;
    WebExtensions.SelectOptionbyVisibleText selectOptionbyVisibleText;
    NetahsilatUtills.ClickUntilGone clickUntilGone;
    JSActions.TypeTextAction typeTextAction;

    // 1. Run Method Logout&Login
    GeneratedUtils.sleep(500);
    methodlogoutlogin = new MethodLogoutlogin();
    methodlogoutlogin.ApplicationURL = ApplicationURL;
    methodlogoutlogin.userName = ProjectParameters.genelEmail;
    methodlogoutlogin.password = ProjectParameters.genelPassword;
    methodlogoutlogin.execute(driver);

    // 2. Move mouse to 'moveUstUyeYonetimi'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("li[class='content']");
    (new Actions(driver)).moveToElement(driver.findElement(by)).perform();

    // 3. Click 'ustUyeYonetimi'
    GeneratedUtils.sleep(500);
    by = By.xpath("//li[4]/a[. = 'ÜYE YÖNETİMİ']");
    driver.findElement(by).click();

    // 4. Click 'altUyeYonetimi'
    GeneratedUtils.sleep(500);
    by = By.xpath("//li[1]/a[. = 'ÜYE YÖNETİMİ']");
    driver.findElement(by).click();

    // 5. Is 'ddYeniUyeTanimi' visible?
    GeneratedUtils.sleep(500);
    by = By.xpath("//div[2]/div/img");
    driver.findElement(by).isDisplayed();

    // 6. Click 'ddYeniUyeTanimi'
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(25000, TimeUnit.MILLISECONDS);
    GeneratedUtils.sleep(500);
    by = By.xpath("//div[2]/div/img");
    driver.findElement(by).click();
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 7. Click 'Yeni Bayi Tanımla'
    GeneratedUtils.sleep(500);
    by = By.xpath("//a[. = 'Yeni Bayi Tanımla']");
    driver.findElement(by).click();

    // 8. Is 'Bayi Adi' visible?
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(35000, TimeUnit.MILLISECONDS);
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_Name");
    driver.findElement(by).isDisplayed();
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 9. Type 'test bayi' in 'Bayi Adi'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_Name");
    driver.findElement(by).sendKeys("test bayi");

    // 10. Click 'Entity.IsCompany2'
    GeneratedUtils.sleep(500);
    by = By.xpath("//fieldset/div[2]/p/input[1]");
    driver.findElement(by).click();

    // 11. Type '181212' in 'Entity.Code'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_Code");
    driver.findElement(by).sendKeys("181212");

    // 12. Type 'otomasyon32@ecozum.com' in 'Entity.Email'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_Email");
    driver.findElement(by).sendKeys("otomasyon32@ecozum.com");

    // 13. Type '79119547058' in 'Entity.Tckn'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_Tckn");
    driver.findElement(by).sendKeys("79119547058");

    // 14. Type 'tahsilat test' in 's2id_autogen2'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#s2id_autogen2");
    driver.findElement(by).sendKeys("tahsilat test");

    // 15. Send 'ENTER' key(s)
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#s2id_autogen2");
    (new Actions(driver)).sendKeys(GeneratedUtils.getKeys("ENTER")).build().perform();

    // 16. Select options in 'CurrencyTLBtn' with text '[NONE]'
    GeneratedUtils.sleep(500);
    selectOptionbyVisibleText = WebExtensions.selectOptionbyVisibleText("TL");
    by = By.xpath("//select[@id='Entity_CurrencyTypeId']");
    selectOptionbyVisibleText = (WebExtensions.SelectOptionbyVisibleText)((ReportingDriver)driver).addons().execute(selectOptionbyVisibleText, by, -1);

    // 17. Type '19381938' in 'Entity.ErpCode'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_ErpCode");
    driver.findElement(by).sendKeys("19381938");

    // 18. Type 'istanbul' in 'Entity.AddressModel.Address'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_AddressModel_Address");
    driver.findElement(by).sendKeys("istanbul");

    // 19. Select the '34' option in 'Entity.AddressModel.CityId'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_AddressModel_CityId");
    (new Select(driver.findElement(by))).selectByValue("34");

    // 20. Select the '833' option in 'Entity.AddressModel.DistrictId'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_AddressModel_DistrictId");
    (new Select(driver.findElement(by))).selectByValue("833");

    // 21. Select the '2049' option in 'Entity.AddressModel.NeighborhoodId'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_AddressModel_NeighborhoodId");
    (new Select(driver.findElement(by))).selectByValue("2049");

    // 22. Type '34410' in 'Entity.AddressModel.PostCode'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_AddressModel_PostCode");
    driver.findElement(by).sendKeys("34410");

    // 23. Type '5555555555' in 'Entity.ContactModel.Phone1Number'
    GeneratedUtils.sleep(500);
    typeTextAction = JSActions.typeTextAction("5555555555");
    by = By.cssSelector("#Entity_ContactModel_Phone1Number");
    typeTextAction = (JSActions.TypeTextAction)((ReportingDriver)driver).addons().execute(typeTextAction, by, -1);

    // 24. Type '2129998877' in 'Entity.ContactModel.Fax1Number'
    GeneratedUtils.sleep(500);
    typeTextAction = JSActions.typeTextAction("2129998877");
    by = By.cssSelector("#Entity_ContactModel_Fax1Number");
    typeTextAction = (JSActions.TypeTextAction)((ReportingDriver)driver).addons().execute(typeTextAction, by, -1);

    // 25. Type 'www.qualitymuseum.com' in 'Entity.ContactModel.WebAddress'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_ContactModel_WebAddress");
    driver.findElement(by).sendKeys("www.qualitymuseum.com");

    // 26. Run Click Until Gone
    GeneratedUtils.sleep(500);
    clickUntilGone = NetahsilatUtills.clickUntilGone(30);
    by = By.xpath("//button[. = 'Tamam']");
    clickUntilGone = (NetahsilatUtills.ClickUntilGone)((ReportingDriver)driver).addons().execute(clickUntilGone, by, -1);

    // 27. Is 'Entity.Password' visible?
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(35000, TimeUnit.MILLISECONDS);
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_Password");
    driver.findElement(by).isDisplayed();
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 28. Type '{{genelPassword}}' in 'Entity.Password'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_Password");
    driver.findElement(by).sendKeys(ProjectParameters.genelPassword);

    // 29. Type '{{genelPassword}}' in 'Entity.PasswordAgain'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_PasswordAgain");
    driver.findElement(by).sendKeys(ProjectParameters.genelPassword);

    // 30. Type '41041014656' in 'Entity.Tckn'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_Tckn");
    driver.findElement(by).sendKeys("41041014656");

    // 31. Type '(531)3247684' in 'Entity.MobilePhone'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_MobilePhone");
    driver.findElement(by).sendKeys("(531)3247684");

    // 32. Type 'surname' in 'Entity.Surname'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_Surname");
    driver.findElement(by).sendKeys("surname");

    // 33. Run Click Until Gone
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(35000, TimeUnit.MILLISECONDS);
    GeneratedUtils.sleep(500);
    clickUntilGone = NetahsilatUtills.clickUntilGone(30);
    by = By.xpath("//button[. = 'Tamam']");
    clickUntilGone = (NetahsilatUtills.ClickUntilGone)((ReportingDriver)driver).addons().execute(clickUntilGone, by, -1);
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

  }

  @Override
  public ReportingDriver getDriver() {
    return (ReportingDriver) driver;
  }

  @AfterAll
  static void tearDown() {
    if (driver != null) {
      driver.quit();
    }
  }

  private static Stream provideParameters() throws Exception {
    return Stream.of(Arguments.of("https://otomasyon.netahsilatdemo.com/Account/LogOff","",""));
  }
}
