package netahsilat;

import io.testproject.addon.NetahsilatUtills;
import io.testproject.addon.WebListOperations;
import io.testproject.sdk.drivers.ReportingDriver;
import io.testproject.sdk.drivers.web.RemoteWebDriver;
import io.testproject.sdk.interfaces.junit5.ExceptionsReporter;
import java.lang.Exception;
import java.lang.Override;
import java.lang.String;
import java.util.concurrent.TimeUnit;
import java.util.stream.Stream;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

/**
 * This class was automatically generated by TestProject
 * Project: Quality Museum Project
 * Test: C1798 Admin Eklemelerinde Default grupların atanması (Bayi/Müşteri/AltBayi/AltMüşteri)
 * Generated by: Ahmet Furkan SIMSEK (furkan.simsek@qualitymuseum.com)
 * Generated on Mon Oct 10 07:12:52 GMT 2022.
 */
@DisplayName("C1798 Admin Eklemelerinde Default grupların atanması (Bayi/Müşteri/AltBayi/AltMüşteri)")
public class C1798 implements ExceptionsReporter {
  public static WebDriver driver;

  @BeforeAll
  static void setup() throws Exception {
    driver = new RemoteWebDriver("wThDxIHw4zNaCydjAhcfe81WrQPYlMBFI7FPwUwV8M41", new ChromeOptions(), "Ahmet Furkan SIMSEK");
  }

  /**
   * In order to upload the test to TestProject need to un-comment @ArgumentsSource and set in comment the @MethodSource
   * @org.junit.jupiter.params.provider.ArgumentsSource(io.testproject.sdk.interfaces.parameterization.TestProjectParameterizer.class) */
  @DisplayName("C1798 Admin Eklemelerinde Default grupların atanması (Bayi/Müşteri/AltBayi/AltMüşteri)")
  @ParameterizedTest
  @MethodSource("provideParameters")
  void execute(String ApplicationURL, String userName, String password, String currentDateTime)
      throws Exception {
    // set timeout for driver actions (similar to step timeout)
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);
    By by;
    boolean booleanResult;
    MethodLogin methodlogin;
    NetahsilatUtills.ClickUntilGone clickUntilGone;
    WebListOperations.GetTextFromSelectedItem getTextFromSelectedItem;

    // 1. Navigate to '{{Otomasyon3Logout}}'
    driver.navigate().to(ProjectParameters.Otomasyon3Logout);

    // 2. Run Method Login
    //    otomasyon@test.com
    methodlogin = new MethodLogin();
    methodlogin.ApplicationURL = ApplicationURL;
    methodlogin.userName = "otomasyon@test.com";
    methodlogin.password = password;
    methodlogin.execute(driver);
    currentDateTime = String.valueOf(methodlogin.currentDateTime);

    // 3. Move mouse to 'moveUstUyeYonetimi'
    by = By.cssSelector("li[class='content']");
    (new Actions(driver)).moveToElement(driver.findElement(by)).perform();

    // 4. Click 'ustUyeYonetimi'
    by = By.xpath("//li[4]/a[. = 'ÜYE YÖNETİMİ']");
    driver.findElement(by).click();

    // 5. Click 'altUyeYonetimi'
    by = By.xpath("//li[1]/a[. = 'ÜYE YÖNETİMİ']");
    driver.findElement(by).click();

    // 6. Click 'ddYeniUyeTanimi'
    by = By.xpath("//div[2]/div/img");
    driver.findElement(by).click();

    // 7. Click 'Yeni Bayi Tanımla'
    by = By.xpath("//a[. = 'Yeni Bayi Tanımla']");
    driver.findElement(by).click();

    // 8. Type 'Bayitest' in 'Bayi/Kullanıcı Adı3'
    by = By.cssSelector("#Masked_Name");
    driver.findElement(by).sendKeys("Bayitest");

    // 9. Type 'test1' in 'Bayi Kodu'
    by = By.cssSelector("#Entity_Code");
    driver.findElement(by).sendKeys("test1");

    // 10. Type 'C1798@test.com' in 'Yeni Bayi Tanımla E-Posta'
    by = By.cssSelector("#Masked_Email");
    driver.findElement(by).sendKeys("C1798@test.com");

    // 11. Type '11111111111' in 'Vergi Numarası'
    by = By.cssSelector("#Entity_TaxNumber");
    driver.findElement(by).sendKeys("11111111111");

    // 12. Type 'TORBALI' in 'Yeni Bayi Tanımla Vergi Dairesi'
    by = By.cssSelector("#Entity_TaxOffice");
    driver.findElement(by).sendKeys("TORBALI");

    // 13. Type 'admin@netahsilat.com admin' in 's2id_autogen2'
    by = By.cssSelector("#s2id_autogen2");
    driver.findElement(by).sendKeys("admin@netahsilat.com admin");

    // 14. Send 'ENTER' key(s)
    (new Actions(driver)).sendKeys(GeneratedUtils.getKeys("ENTER")).build().perform();

    // 15. Run Click Until Gone
    clickUntilGone = NetahsilatUtills.clickUntilGone(30);
    by = By.xpath("//button[. = 'Tamam']");
    clickUntilGone = (NetahsilatUtills.ClickUntilGone)((ReportingDriver)driver).addons().execute(clickUntilGone, by, -1);

    // 16. Type 'test' in 'Entity.Surname'
    by = By.cssSelector("#Entity_Surname");
    driver.findElement(by).sendKeys("test");

    // 17. Type '{{password}}' in 'Entity.Password'
    by = By.cssSelector("#Entity_Password");
    driver.findElement(by).sendKeys(password);

    // 18. Type '{{password}}' in 'Entity.PasswordAgain'
    by = By.cssSelector("#Entity_PasswordAgain");
    driver.findElement(by).sendKeys(password);

    // 19. Run Click Until Gone
    clickUntilGone = NetahsilatUtills.clickUntilGone(30);
    by = By.xpath("//button[. = 'Tamam']");
    clickUntilGone = (NetahsilatUtills.ClickUntilGone)((ReportingDriver)driver).addons().execute(clickUntilGone, by, -1);

    // 20. Type 'C1798@test.com' in 'SearchUserName'
    by = By.cssSelector("#SearchUserName");
    driver.findElement(by).sendKeys("C1798@test.com");

    // 21. Click 'C1798@test.com ListelenenDiv'
    by = By.xpath("//li//div[text()='Ba**** te****,']");
    driver.findElement(by).click();

    // 22. Click 'Listele'
    by = By.xpath("//button[. = 'Listele']");
    driver.findElement(by).click();

    // 23. Is 'Listele' is clickable?
    by = By.xpath("//button[. = 'Listele']");
    (new WebDriverWait(driver, 15)).until(ExpectedConditions.elementToBeClickable(by));

    // 24. Click 'KullanıcılarıGörüntüleImage'
    by = By.cssSelector("img[src*='fugue/detail.png']");
    driver.findElement(by).click();

    // 25. Click ''Ba**** te****' Rol Ekle/Çıkar img '
    by = By.xpath("//td[starts-with(text(),'Ba**** te****')]//..//img[contains(@src,'user-silhouette-question')]");
    driver.findElement(by).click();

    // 26. Retrieves the text of the currently selected option of a select element
    getTextFromSelectedItem = WebListOperations.getGetTextFromSelectedItem();
    by = By.cssSelector("#roleGroupId");
    getTextFromSelectedItem = (WebListOperations.GetTextFromSelectedItem)((ReportingDriver)driver).addons().execute(getTextFromSelectedItem, by, -1);

    // 27. Click 'Vazgeç'
    by = By.xpath("//button[. = 'Vazgeç']");
    driver.findElement(by).click();

    // 28. Click 'Bayitest trash.img'
    by = By.xpath("//td[contains(text(),'Bayitest')]/..//img[contains(@src,'trash.png')]");
    driver.findElement(by).click();

    // 29. Run Click Until Gone
    clickUntilGone = NetahsilatUtills.clickUntilGone(30);
    by = By.xpath("//button[. = 'Tamam']");
    clickUntilGone = (NetahsilatUtills.ClickUntilGone)((ReportingDriver)driver).addons().execute(clickUntilGone, by, -1);

    // 30. Is 'Gösterilecek Kayıt Bulunamadı.' visible?
    by = By.xpath("//td[. = 'Gösterilecek Kayıt Bulunamadı.']");
    driver.findElement(by).isDisplayed();

  }

  @Override
  public ReportingDriver getDriver() {
    return (ReportingDriver) driver;
  }

  @AfterAll
  static void tearDown() {
    if (driver != null) {
      driver.quit();
    }
  }

  private static Stream provideParameters() throws Exception {
    return Stream.of(Arguments.of("https://otomasyon3.netahsilatdemo.com/","otomasyon@test.com","Kd!cyhz4",""));
  }
}
