package netahsilat;

import io.testproject.addon.GridOperations;
import io.testproject.addon.JSActions;
import io.testproject.sdk.drivers.ReportingDriver;
import io.testproject.sdk.drivers.web.RemoteWebDriver;
import io.testproject.sdk.interfaces.junit5.ExceptionsReporter;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.concurrent.TimeUnit;
import java.util.stream.Stream;

/**
 * This class was automatically generated by TestProject
 * Project: Quality Museum Project
 * Test: C1802 Yetkilerin Kendi içinde sınıflandırılması (Site Yetkisi) -NTH-14411
 * Generated by: Ahmet Furkan SIMSEK (furkan.simsek@qualitymuseum.com)
 * Generated on Mon Oct 10 07:15:37 GMT 2022.
 */
@DisplayName("C1802 Yetkilerin Kendi içinde sınıflandırılması (Site Yetkisi) -NTH-14411")
public class C1802 implements ExceptionsReporter {
  public static WebDriver driver;

  @BeforeAll
  static void setup() throws Exception {
    driver = new RemoteWebDriver("wThDxIHw4zNaCydjAhcfe81WrQPYlMBFI7FPwUwV8M41", new ChromeOptions(), "Ahmet Furkan SIMSEK");
  }

  /**
   * In order to upload the test to TestProject need to un-comment @ArgumentsSource and set in comment the @MethodSource
   * @org.junit.jupiter.params.provider.ArgumentsSource(io.testproject.sdk.interfaces.parameterization.TestProjectParameterizer.class) */
  @DisplayName("C1802 Yetkilerin Kendi içinde sınıflandırılması (Site Yetkisi) -NTH-14411")
  @ParameterizedTest
  @MethodSource("provideParameters")
  void execute(String ApplicationURL, String userName, String password, String currentDateTime,
      String RolName) throws Exception {
    // set timeout for driver actions (similar to step timeout)
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);
    By by;
    boolean booleanResult;
    MethodLogin methodlogin;
    JSActions.ClickAction clickAction;
    GridOperations.getAllDataWithList getAllDataWithList;

    // 1. Navigate to '{{Otomasyon3Logout}}'
    driver.navigate().to(ProjectParameters.Otomasyon3Logout);

    // 2. Run Method Login
    //    otomasyon@test.com
    methodlogin = new MethodLogin();
    methodlogin.ApplicationURL = ApplicationURL;
    methodlogin.userName = "otomasyon@test.com";
    methodlogin.password = ProjectParameters.genelPassword;
    methodlogin.execute(driver);
    currentDateTime = String.valueOf(methodlogin.currentDateTime);

    // 3. Click 'moveToKullaniciYönetimi'
    by = By.cssSelector("li[class='user']");
    driver.findElement(by).click();

    // 4. Click 'KULLANICI YÖNETİMİ1'
    by = By.cssSelector("a[title='KULLANICI YÖNETİMİ']");
    driver.findElement(by).click();

    // 5. Click 'ROL YÖNETİMİ'
    by = By.xpath("//a[. = 'ROL YÖNETİMİ']");
    driver.findElement(by).click();

    // 6. Click 'Yeni Rol Grubu Tanımla DropdownMenu'
    by = By.xpath("//h1[text()='Yeni Rol Grubu Tanımla']/../div");
    driver.findElement(by).click();

    // 7. Click 'Site Yetkisi'
    by = By.xpath("//li[@class='icon_bayi']/.//a[text()='Site Yetkisi']");
    driver.findElement(by).click();

    // 8. Fetch All Data as List
    //    Rollerin açılır olanlarının validate edilmesi 
    getAllDataWithList = new GridOperations.getAllDataWithList();
    by = By.xpath("//span[@class='t-icon t-plus']//..//span[@class='t-in']");
    getAllDataWithList = (GridOperations.getAllDataWithList)((ReportingDriver)driver).addons().execute(getAllDataWithList, by, -1);

    // 9. Click 'Yeni Rol Ekle Plus İşareti'
    for (int i = 1; i <= 11; i++) {
      clickAction = JSActions.getClickAction();
      by = By.xpath("//span[@class='t-icon t-plus']");
      clickAction = (JSActions.ClickAction)((ReportingDriver)driver).addons().execute(clickAction, by, -1);
    }

    // 10. Is 'Yeni Rol Ekle Plus İşareti' not present or invisible?
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(2000, TimeUnit.MILLISECONDS);
    by = By.xpath("//span[@class='t-icon t-plus']");
    (new WebDriverWait(driver, 2)).until(ExpectedConditions.invisibilityOf(driver.findElement(by)));
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 11. Click 'Yeni Rol Ekle - İşareti'
    for (int i = 1; i <= 11; i++) {
      clickAction = JSActions.getClickAction();
      by = By.xpath("//span[@class='t-icon t-minus']");
      clickAction = (JSActions.ClickAction)((ReportingDriver)driver).addons().execute(clickAction, by, -1);
    }

    // 12. Is 'Yeni Rol Ekle - İşareti' not present or invisible?
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(2000, TimeUnit.MILLISECONDS);
    by = By.xpath("//span[@class='t-icon t-minus']");
    (new WebDriverWait(driver, 2)).until(ExpectedConditions.invisibilityOf(driver.findElement(by)));
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 13. Click 'Yeni Rol Ekle Yönetici Checkbox'
    by = By.cssSelector("#chckIsAdmin");
    driver.findElement(by).click();

    // 14. Is 'Yeni Rol Ekle Yönetici Checkbox' visible and selected?
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(2000, TimeUnit.MILLISECONDS);
    by = By.cssSelector("#chckIsAdmin");
    (new WebDriverWait(driver, 2)).until(ExpectedConditions.elementSelectionStateToBe(by, true));
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 15. Click 'Yeni Rol Ekle Yönetici Checkbox'
    by = By.cssSelector("#chckIsAdmin");
    driver.findElement(by).click();

    // 16. Is 'Yeni Rol Ekle Yönetici Checkbox' visible and selected?
    //    INVERT STEP RESULT

    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(2000, TimeUnit.MILLISECONDS);
    try {
      by = By.cssSelector("#chckIsAdmin");
      (new WebDriverWait(driver, 2)).until(ExpectedConditions.elementSelectionStateToBe(by, true));
      Assertions.fail("Step 'Is 'Yeni Rol Ekle Yönetici Checkbox' visible and selected?' result inverted, step failed");
    }
    catch (RuntimeException ex) {
    }
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 17. Click 'Alt Bayi İşlemleri Plus İşareti'
    by = By.xpath("//span[text()='Alt Bayi İşlemleri']//..//.//span[@class='t-icon t-plus']");
    driver.findElement(by).click();

    // 18. Click 'Alt Bayi İşlemleri Checkbox'
    by = By.xpath("//span[text()='Alt Bayi İşlemleri']//..//input[2]");
    driver.findElement(by).click();

    // 19. Is 'Alt Bayi Ekleme Checkbox' visible and selected?
    //    INVERT STEP RESULT

    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(2000, TimeUnit.MILLISECONDS);
    try {
      by = By.xpath("//span[text()='Alt Bayi Ekleme']//..//input[2]");
      (new WebDriverWait(driver, 2)).until(ExpectedConditions.elementSelectionStateToBe(by, true));
      Assertions.fail("Step 'Is 'Alt Bayi Ekleme Checkbox' visible and selected?' result inverted, step failed");
    }
    catch (RuntimeException ex) {
    }
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 20. Is 'Alt Bayi Sanal Pos Yönetimi Checkbox' visible and selected?
    //    INVERT STEP RESULT

    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(2000, TimeUnit.MILLISECONDS);
    try {
      by = By.xpath("//span[text()='Alt Bayi Sanal Pos Yönetimi']//..//input[2]");
      (new WebDriverWait(driver, 2)).until(ExpectedConditions.elementSelectionStateToBe(by, true));
      Assertions.fail("Step 'Is 'Alt Bayi Sanal Pos Yönetimi Checkbox' visible and selected?' result inverted, step failed");
    }
    catch (RuntimeException ex) {
    }
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 21. Is 'Alt Bayi Pos Bilgileri Toplu Ekleme Checkbox' visible and selected?
    //    INVERT STEP RESULT

    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(2000, TimeUnit.MILLISECONDS);
    try {
      by = By.xpath("//span[text()='Alt Bayi Pos Bilgileri Toplu Ekleme']//..//input[2]");
      (new WebDriverWait(driver, 2)).until(ExpectedConditions.elementSelectionStateToBe(by, true));
      Assertions.fail("Step 'Is 'Alt Bayi Pos Bilgileri Toplu Ekleme Checkbox' visible and selected?' result inverted, step failed");
    }
    catch (RuntimeException ex) {
    }
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 22. Is 'Alt Bayi, Alt Müşteri Ödeme Seti Yönetim Checkbox' visible and selected?
    //    INVERT STEP RESULT

    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(2000, TimeUnit.MILLISECONDS);
    try {
      by = By.xpath("//span[text()='Alt Bayi, Alt Müşteri Ödeme Seti Yönetim']//..//input[2]");
      (new WebDriverWait(driver, 2)).until(ExpectedConditions.elementSelectionStateToBe(by, true));
      Assertions.fail("Step 'Is 'Alt Bayi, Alt Müşteri Ödeme Seti Yönetim Checkbox' visible and selected?' result inverted, step failed");
    }
    catch (RuntimeException ex) {
    }
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 23. Click 'Alt Bayi Ekleme Checkbox'
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(2000, TimeUnit.MILLISECONDS);
    by = By.xpath("//span[text()='Alt Bayi Ekleme']//..//input[2]");
    driver.findElement(by).click();
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 24. Click 'Alt Bayi Sanal Pos Yönetimi Checkbox'
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(2000, TimeUnit.MILLISECONDS);
    by = By.xpath("//span[text()='Alt Bayi Sanal Pos Yönetimi']//..//input[2]");
    driver.findElement(by).click();
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 25. Click 'Alt Bayi Pos Bilgileri Toplu Ekleme Checkbox'
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(2000, TimeUnit.MILLISECONDS);
    by = By.xpath("//span[text()='Alt Bayi Pos Bilgileri Toplu Ekleme']//..//input[2]");
    driver.findElement(by).click();
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 26. Click 'Alt Bayi, Alt Müşteri Ödeme Seti Yönetim Checkbox'
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(2000, TimeUnit.MILLISECONDS);
    by = By.xpath("//span[text()='Alt Bayi, Alt Müşteri Ödeme Seti Yönetim']//..//input[2]");
    driver.findElement(by).click();
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 27. Is 'Alt Bayi İşlemleri Checkbox' visible and selected?
    by = By.xpath("//span[text()='Alt Bayi İşlemleri']//..//input[2]");
    (new WebDriverWait(driver, 15)).until(ExpectedConditions.elementSelectionStateToBe(by, true));

    // 28. Is 'Yeni Rol Ekle Yönetici Checkbox' visible and selected?
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(2000, TimeUnit.MILLISECONDS);
    by = By.cssSelector("#chckIsAdmin");
    (new WebDriverWait(driver, 2)).until(ExpectedConditions.elementSelectionStateToBe(by, true));
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

  }

  @Override
  public ReportingDriver getDriver() {
    return (ReportingDriver) driver;
  }

  @AfterAll
  static void tearDown() {
    if (driver != null) {
      driver.quit();
    }
  }

  private static Stream provideParameters() throws Exception {
    return Stream.of(Arguments.of("https://otomasyon3.netahsilatdemo.com/","otomasyon@test.com","Kd!cyhz4","",""));
  }
}
