package netahsilat;

import io.testproject.addon.CombinedActions;
import io.testproject.addon.JSActions;
import io.testproject.addon.VisibleElementsOperations;
import io.testproject.addon.WebExtensions;
import io.testproject.sdk.drivers.ReportingDriver;
import io.testproject.sdk.drivers.web.RemoteWebDriver;
import io.testproject.sdk.interfaces.junit5.ExceptionsReporter;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;

import java.util.concurrent.TimeUnit;
import java.util.stream.Stream;

/**
 * This class was automatically generated by TestProject
 * Project: Quality Museum Project
 * Test: C2097 Ödeme talimat formu ne zaman gösterilsin? (+ Dil Kontrolü)
 * Generated by: Ahmet Furkan SIMSEK (furkan.simsek@qualitymuseum.com)
 * Generated on Fri Oct 07 11:13:25 GMT 2022.
 */
@DisplayName("C2097 Ödeme talimat formu ne zaman gösterilsin? (+ Dil Kontrolü)")
public class C2097 implements ExceptionsReporter {
  public static WebDriver driver;

  @BeforeAll
  static void setup() throws Exception {
    driver = new RemoteWebDriver("wThDxIHw4zNaCydjAhcfe81WrQPYlMBFI7FPwUwV8M41", new ChromeOptions(), "Ahmet Furkan SIMSEK");
  }

  /**
   * In order to upload the test to TestProject need to un-comment @ArgumentsSource and set in comment the @MethodSource
   * @org.junit.jupiter.params.provider.ArgumentsSource(io.testproject.sdk.interfaces.parameterization.TestProjectParameterizer.class) */
  @DisplayName("C2097 Ödeme talimat formu ne zaman gösterilsin? (+ Dil Kontrolü)")
  @ParameterizedTest
  @MethodSource("provideParameters")
  void execute(String ApplicationURL, String userName, String password, String kartNo, String CVV,
      String ayYil) throws Exception {
    // set timeout for driver actions (similar to step timeout)
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);
    By by;
    boolean booleanResult;
    MethodParametrikdemesadeceKartTypeTextWithDelayIsimsiz methodparametrikdemesadecekarttypetextwithdelayisimsiz;
    MethodLogoutlogin methodlogoutlogin;
    WebExtensions.SelectOptionbyVisibleText selectOptionbyVisibleText;
    CombinedActions.ClearAndTypeAction clearAndTypeAction;
    JSActions.ClickAction clickAction;
    VisibleElementsOperations.ClearContentsIfVisibleWeb clearContentsIfVisibleWeb;
    WebExtensions.SetElementAttribute setElementAttribute;

    // 1. Run Method Logout&Login
    GeneratedUtils.sleep(500);
    methodlogoutlogin = new MethodLogoutlogin();
    methodlogoutlogin.ApplicationURL = ApplicationURL;
    methodlogoutlogin.userName = ProjectParameters.genelEmail;
    methodlogoutlogin.password = ProjectParameters.genelPassword;
    methodlogoutlogin.execute(driver);

    // 2. Move mouse to 'moveToSiteYönetimi'
    by = By.cssSelector("li[class='config']");
    (new Actions(driver)).moveToElement(driver.findElement(by)).perform();

    // 3. Click 'moveToSiteYönetimi'
    by = By.cssSelector("li[class='config']");
    driver.findElement(by).click();

    // 4. Click 'btnParametreler'
    by = By.cssSelector("a[title='PARAMETRELER']");
    driver.findElement(by).click();

    // 5. Is 'Ödemelerde BIN numarası kontrol edils...' visible?
    by = By.xpath("//label[. = 'Ödemelerde BIN numarası kontrol edilsin']");
    driver.findElement(by).isDisplayed();

    // 6. Click 'li > a > Ödeme Talimat Formu'
    by = By.xpath("//a[normalize-space()='Ödeme Talimat Formu']");
    driver.findElement(by).click();

    // 7. Is 'editorToolbar' visible?
    by = By.xpath("//div[contains(@id,'toolbargroup') and not(contains(@id,'Locales' ))]");
    driver.findElement(by).isDisplayed();

    // 8. Select options in 'ShowPaymentInstructionFormMode' with text '[NONE]'
    selectOptionbyVisibleText = WebExtensions.selectOptionbyVisibleText("Ödeme sonrasında gösterilsin");
    by = By.cssSelector("#ShowPaymentInstructionFormMode");
    selectOptionbyVisibleText = (WebExtensions.SelectOptionbyVisibleText)((ReportingDriver)driver).addons().execute(selectOptionbyVisibleText, by, -1);

    // 9. Click 'Kaydet1'
    by = By.cssSelector("#kaydet");
    driver.findElement(by).click();

    // 10. Does 'Ödeme Talimat Formu Başarıyla kaydedi...' contain 'Ödeme Talimat Formu Başarıyla kaydedildi.'?
    by = By.xpath("//li[. = 'Ödeme Talimat Formu Başarıyla kaydedildi.']");
    Assertions.assertTrue(driver.findElement(by).getText().contains("Ödeme Talimat Formu Başarıyla kaydedildi."));

    // 11. Navigate to '{{ApplicationURL}}'
    driver.navigate().to(ApplicationURL);

    // 12. Navigate to '{{UyeliksizOdemeURL}}'
    driver.navigate().to(ProjectParameters.UyeliksizOdemeURL);

    // 13. Clear the contents of 'PureAmount' if it's visible
    clearContentsIfVisibleWeb = VisibleElementsOperations.clearContentsIfVisibleWeb("");
    by = By.cssSelector("#PureAmount");
    clearContentsIfVisibleWeb = (VisibleElementsOperations.ClearContentsIfVisibleWeb)((ReportingDriver)driver).addons().execute(clearContentsIfVisibleWeb, by, -1);

    // 14. Type '100' in 'PureAmount'
    by = By.cssSelector("#PureAmount");
    driver.findElement(by).sendKeys("100");

    // 15. Click 'Taksit Seçimi'
    by = By.cssSelector("#installment-selection-text");
    driver.findElement(by).click();

    // 16. Run Method Parametrik Ödeme (Sadece Kart - Type text with delay)  - İsimsiz
    methodparametrikdemesadecekarttypetextwithdelayisimsiz = new MethodParametrikdemesadeceKartTypeTextWithDelayIsimsiz();
    methodparametrikdemesadecekarttypetextwithdelayisimsiz.kartNo = ProjectParameters.genelKartNo;
    methodparametrikdemesadecekarttypetextwithdelayisimsiz.CVV = ProjectParameters.genelKartCVV;
    methodparametrikdemesadecekarttypetextwithdelayisimsiz.ayYil = ProjectParameters.genelKartAyYil;
    methodparametrikdemesadecekarttypetextwithdelayisimsiz.adSoyad = "Odeme User";
    methodparametrikdemesadecekarttypetextwithdelayisimsiz.execute(driver);

    // 17. Run Clear 'inputEmailPricinPage' contents and type 'netahsilatotomasyon@yandex.com'
    clearAndTypeAction = CombinedActions.clearAndTypeAction("netahsilatotomasyon@yandex.com");
    by = By.cssSelector("#Email");
    clearAndTypeAction = (CombinedActions.ClearAndTypeAction)((ReportingDriver)driver).addons().execute(clearAndTypeAction, by, -1);

    // 18. Move mouse to 'genelOdemeTaksitSecenegi'
    by = By.xpath("(//td[contains(@class,'commRate-20')])[1]");
    (new Actions(driver)).moveToElement(driver.findElement(by)).perform();

    // 19. Click 'genelOdemeTaksitSecenegi'
    clickAction = JSActions.getClickAction();
    by = By.xpath("(//td[contains(@class,'commRate-20')])[1]");
    clickAction = (JSActions.ClickAction)((ReportingDriver)driver).addons().execute(clickAction, by, -1);

    // 20. Click 'btnNormalPayment'
    by = By.cssSelector("#btnNormalPayment");
    driver.findElement(by).click();

    // 21. Does 'İşleminiz Tamamlandı. Referans Numarası : (GENEL)' contain 'İşleminiz Tamamlandı. Referans Numarası :'?
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(35000, TimeUnit.MILLISECONDS);
    by = By.xpath("//p[contains(text(),'İşleminiz Tamamlandı. Referans Numarası :')]");
    Assertions.assertTrue(driver.findElement(by).getText().contains("İşleminiz Tamamlandı. Referans Numarası :"));
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 22. Does 'KREDI KARTI ÖDEME TALIMATI1' contain 'KREDI KARTI ÖDEME TALIMATI'?
    by = By.xpath("//p[. = 'KREDI KARTI ÖDEME TALIMATI']");
    Assertions.assertTrue(driver.findElement(by).getText().contains("KREDI KARTI ÖDEME TALIMATI"));

    // 23. Run Method Logout&Login
    methodlogoutlogin = new MethodLogoutlogin();
    methodlogoutlogin.ApplicationURL = ApplicationURL;
    methodlogoutlogin.userName = userName;
    methodlogoutlogin.password = password;
    methodlogoutlogin.execute(driver);

    // 24. Move mouse to 'moveToSiteYönetimi'
    by = By.cssSelector("li[class='config']");
    (new Actions(driver)).moveToElement(driver.findElement(by)).perform();

    // 25. Click 'moveToSiteYönetimi'
    by = By.cssSelector("li[class='config']");
    driver.findElement(by).click();

    // 26. Click 'btnParametreler'
    by = By.cssSelector("a[title='PARAMETRELER']");
    driver.findElement(by).click();

    // 27. Is 'Ödemelerde BIN numarası kontrol edils...' visible?
    by = By.xpath("//label[. = 'Ödemelerde BIN numarası kontrol edilsin']");
    driver.findElement(by).isDisplayed();

    // 28. Click 'li > a > Ödeme Talimat Formu'
    by = By.xpath("//a[normalize-space()='Ödeme Talimat Formu']");
    driver.findElement(by).click();

    // 29. Select options in 'ShowPaymentInstructionFormMode' with text '[NONE]'
    selectOptionbyVisibleText = WebExtensions.selectOptionbyVisibleText("Ödeme öncesinde gösterilsin");
    by = By.cssSelector("#ShowPaymentInstructionFormMode");
    selectOptionbyVisibleText = (WebExtensions.SelectOptionbyVisibleText)((ReportingDriver)driver).addons().execute(selectOptionbyVisibleText, by, -1);

    // 30. Is 'editorToolbar' visible?
    by = By.xpath("//div[contains(@id,'toolbargroup') and not(contains(@id,'Locales' ))]");
    driver.findElement(by).isDisplayed();

    // 31. Click 'Kaydet1'
    by = By.cssSelector("#kaydet");
    driver.findElement(by).click();

    // 32. Does 'Ödeme Talimat Formu Başarıyla kaydedi...' contain 'Ödeme Talimat Formu Başarıyla kaydedildi.'?
    by = By.xpath("//li[. = 'Ödeme Talimat Formu Başarıyla kaydedildi.']");
    Assertions.assertTrue(driver.findElement(by).getText().contains("Ödeme Talimat Formu Başarıyla kaydedildi."));

    // 33. Navigate to '{{ApplicationURL}}'
    driver.navigate().to(ApplicationURL);

    // 34. Navigate to '{{UyeliksizOdemeURL}}'
    driver.navigate().to(ProjectParameters.UyeliksizOdemeURL);

    // 35. Clear the contents of 'PureAmount' if it's visible
    clearContentsIfVisibleWeb = VisibleElementsOperations.clearContentsIfVisibleWeb("");
    by = By.cssSelector("#PureAmount");
    clearContentsIfVisibleWeb = (VisibleElementsOperations.ClearContentsIfVisibleWeb)((ReportingDriver)driver).addons().execute(clearContentsIfVisibleWeb, by, -1);

    // 36. Type '100' in 'PureAmount'
    by = By.cssSelector("#PureAmount");
    driver.findElement(by).sendKeys("100");

    // 37. Run Method Parametrik Ödeme (Sadece Kart - Type text with delay)  - İsimsiz
    methodparametrikdemesadecekarttypetextwithdelayisimsiz = new MethodParametrikdemesadeceKartTypeTextWithDelayIsimsiz();
    methodparametrikdemesadecekarttypetextwithdelayisimsiz.kartNo = ProjectParameters.genelKartNo;
    methodparametrikdemesadecekarttypetextwithdelayisimsiz.CVV = ProjectParameters.genelKartCVV;
    methodparametrikdemesadecekarttypetextwithdelayisimsiz.ayYil = ProjectParameters.genelKartAyYil;
    methodparametrikdemesadecekarttypetextwithdelayisimsiz.adSoyad = "Odeme User";
    methodparametrikdemesadecekarttypetextwithdelayisimsiz.execute(driver);

    // 38. Move mouse to 'genelOdemeTaksitSecenegi'
    by = By.xpath("(//td[contains(@class,'commRate-20')])[1]");
    (new Actions(driver)).moveToElement(driver.findElement(by)).perform();

    // 39. Click 'genelOdemeTaksitSecenegi'
    clickAction = JSActions.getClickAction();
    by = By.xpath("(//td[contains(@class,'commRate-20')])[1]");
    clickAction = (JSActions.ClickAction)((ReportingDriver)driver).addons().execute(clickAction, by, -1);

    // 40. Click 'Ödeme Talimatı Oluştur Button'
    by = By.xpath("//input[@type='button' and @value='ÖDEME TALİMATI OLUŞTUR']");
    driver.findElement(by).click();

    // 41. Set 'style' attribute value on 'slimScrollDiv'
    setElementAttribute = WebExtensions.setElementAttribute("style","position: relative; overflow: hidden; width: auto; height: 999px; display: block;");
    by = By.cssSelector(".slimScrollDiv");
    setElementAttribute = (WebExtensions.SetElementAttribute)((ReportingDriver)driver).addons().execute(setElementAttribute, by, -1);

    // 42. Set 'style' attribute value on 'slimScrollDiv>div'
    setElementAttribute = WebExtensions.setElementAttribute("style","padding: 15px; overflow: hidden; width: auto; height: 999px !important;");
    by = By.cssSelector(".slimScrollDiv>div");
    setElementAttribute = (WebExtensions.SetElementAttribute)((ReportingDriver)driver).addons().execute(setElementAttribute, by, -1);

    // 43. Does ': Odeme User' contain ': Odeme User'?
    by = By.xpath("//td[. = ': Odeme User']");
    Assertions.assertTrue(driver.findElement(by).getText().contains(": Odeme User"));

    // 44. Does ': 435508******4358' contain ': 435508******4358'?
    by = By.xpath("//td[. = ': 435508******4358']");
    Assertions.assertTrue(driver.findElement(by).getText().contains(": 435508******4358"));

    // 45. Does ': 100 ₺' contain ': 100 ₺'?
    by = By.xpath("//td[. = ': 100 ₺']");
    Assertions.assertTrue(driver.findElement(by).getText().contains(": 100 ₺"));

    // 46. Does ': 1' contain ': 1'?
    by = By.xpath("//td[. = ': 1']");
    Assertions.assertTrue(driver.findElement(by).getText().contains(": 1"));

    // 47. Does 'Talimat Formu - Provizyon Tutarı XPath' contain ': 100 ₺ .'?
    by = By.xpath("//td[normalize-space()='Provizyon Tutarı']//following-sibling::td[1]");
    Assertions.assertTrue(driver.findElement(by).getText().contains(": 100 ₺ ."));

    // 48. Does 'Üyeliksiz Ödeme1' contain 'Üyeliksiz Ödeme'?
    by = By.xpath("//strong[. = 'Üyeliksiz Ödeme']");
    Assertions.assertTrue(driver.findElement(by).getText().contains("Üyeliksiz Ödeme"));

    // 49. Is 'payment-instruction-form' visible?
    by = By.cssSelector("#payment-instruction-form");
    driver.findElement(by).isDisplayed();

    // 50. Click 'UI English Select'
    clickAction = JSActions.getClickAction();
    by = By.xpath("//a[contains(text(),'English')] ");
    clickAction = (JSActions.ClickAction)((ReportingDriver)driver).addons().execute(clickAction, by, -1);

    // 51. Is 'User Name' visible?
    by = By.xpath("//label[. = '\n                User Name\n            ']");
    driver.findElement(by).isDisplayed();

    // 52. Navigate to '{{UyeliksizOdemeURL}}'
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(25000, TimeUnit.MILLISECONDS);
    GeneratedUtils.sleep(500);
    driver.navigate().to(ProjectParameters.UyeliksizOdemeURL);
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 53. Clear the contents of 'PureAmount' if it's visible
    clearContentsIfVisibleWeb = VisibleElementsOperations.clearContentsIfVisibleWeb("");
    by = By.cssSelector("#PureAmount");
    clearContentsIfVisibleWeb = (VisibleElementsOperations.ClearContentsIfVisibleWeb)((ReportingDriver)driver).addons().execute(clearContentsIfVisibleWeb, by, -1);

    // 54. Type '100' in 'PureAmount'
    by = By.cssSelector("#PureAmount");
    driver.findElement(by).sendKeys("100");

    // 55. Run Method Parametrik Ödeme (Sadece Kart - Type text with delay)  - İsimsiz
    methodparametrikdemesadecekarttypetextwithdelayisimsiz = new MethodParametrikdemesadeceKartTypeTextWithDelayIsimsiz();
    methodparametrikdemesadecekarttypetextwithdelayisimsiz.kartNo = ProjectParameters.genelKartNo;
    methodparametrikdemesadecekarttypetextwithdelayisimsiz.CVV = ProjectParameters.genelKartCVV;
    methodparametrikdemesadecekarttypetextwithdelayisimsiz.ayYil = ProjectParameters.genelKartAyYil;
    methodparametrikdemesadecekarttypetextwithdelayisimsiz.adSoyad = "Odeme User";
    methodparametrikdemesadecekarttypetextwithdelayisimsiz.execute(driver);

    // 56. Move mouse to 'genelOdemeTaksitSecenegi'
    by = By.xpath("(//td[contains(@class,'commRate-20')])[1]");
    (new Actions(driver)).moveToElement(driver.findElement(by)).perform();

    // 57. Click 'genelOdemeTaksitSecenegi'
    clickAction = JSActions.getClickAction();
    by = By.xpath("(//td[contains(@class,'commRate-20')])[1]");
    clickAction = (JSActions.ClickAction)((ReportingDriver)driver).addons().execute(clickAction, by, -1);

    // 58. Click 'PREPARE PAYMENT ORDER BUTTON'
    by = By.xpath("//input[@type='button' and @value='PREPARE PAYMENT ORDER']");
    driver.findElement(by).click();

    // 59. Does 'CREDIT CARD PAYMENT INSTRUCTIONS' contain 'CREDIT CARD PAYMENT INSTRUCTIONS'?
    by = By.xpath("//p[. = 'CREDIT CARD PAYMENT INSTRUCTIONS']");
    Assertions.assertTrue(driver.findElement(by).getText().contains("CREDIT CARD PAYMENT INSTRUCTIONS"));

    // 60. Click 'UI Türkçe Select'
    clickAction = JSActions.getClickAction();
    by = By.xpath("//a[contains(text(),'Türkçe')] ");
    clickAction = (JSActions.ClickAction)((ReportingDriver)driver).addons().execute(clickAction, by, -1);

  }

  @Override
  public ReportingDriver getDriver() {
    return (ReportingDriver) driver;
  }

  @AfterAll
  static void tearDown() {
    if (driver != null) {
      driver.quit();
    }
  }

  private static Stream provideParameters() throws Exception {
    return Stream.of(Arguments.of("https://otomasyon.netahsilatdemo.com/Account/LogOff","otomasyon@test.com","Kd!cyhz4","","",""));
  }
}
