package netahsilat;

import io.testproject.addon.ImapMailOperations;
import io.testproject.sdk.drivers.ReportingDriver;
import io.testproject.sdk.drivers.web.RemoteWebDriver;
import io.testproject.sdk.interfaces.junit5.ExceptionsReporter;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.concurrent.TimeUnit;
import java.util.stream.Stream;

/**
 * This class was automatically generated by TestProject
 * Project: Quality Museum Project
 * Test: C3244
 * Generated by: Ahmet Furkan SIMSEK (furkan.simsek@qualitymuseum.com)
 * Generated on Sun Oct 09 19:35:08 GMT 2022.
 */
@DisplayName("C3244")
public class C3244 implements ExceptionsReporter {
  public static WebDriver driver;

  @BeforeAll
  static void setup() throws Exception {
    driver = new RemoteWebDriver("wThDxIHw4zNaCydjAhcfe81WrQPYlMBFI7FPwUwV8M41", new ChromeOptions(), "Ahmet Furkan SIMSEK");
  }

  /**
   * In order to upload the test to TestProject need to un-comment @ArgumentsSource and set in comment the @MethodSource
   * @org.junit.jupiter.params.provider.ArgumentsSource(io.testproject.sdk.interfaces.parameterization.TestProjectParameterizer.class) */
  @DisplayName("C3244")
  @ParameterizedTest
  @MethodSource("provideParameters")
  void execute(String ApplicationURL) throws Exception {
    // set timeout for driver actions (similar to step timeout)
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);
    By by;
    boolean booleanResult;
    MethodLogin methodlogin;
    ImapMailOperations.DeleteAllMails deleteAllMails;

    // 1. Navigate to 'https://otomasyon3.netahsilatdemo.com/'
    GeneratedUtils.sleep(500);
    driver.navigate().to("https://otomasyon3.netahsilatdemo.com/");

    // 2. Run Method Login
    methodlogin = new MethodLogin();
    methodlogin.ApplicationURL = ApplicationURL;
    methodlogin.userName = ProjectParameters.genelEmail;
    methodlogin.password = ProjectParameters.genelPassword;
    methodlogin.execute(driver);

    // 3. Delete All Mails
    GeneratedUtils.sleep(500);
    deleteAllMails = ImapMailOperations.deleteAllMails(ProjectParameters.odemeEmail,ProjectParameters.yandexMailKey);
    deleteAllMails = (ImapMailOperations.DeleteAllMails)((ReportingDriver)driver).addons().execute(deleteAllMails);

    // 4. Move mouse to 'moveUstUyeYonetimi'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("li[class='content']");
    (new Actions(driver)).moveToElement(driver.findElement(by)).perform();

    // 5. Click 'ustUyeYonetimi'
    GeneratedUtils.sleep(500);
    by = By.xpath("//li[4]/a[. = 'ÜYE YÖNETİMİ']");
    driver.findElement(by).click();

    // 6. Click 'altUyeYonetimi'
    GeneratedUtils.sleep(500);
    by = By.xpath("//li[1]/a[. = 'ÜYE YÖNETİMİ']");
    driver.findElement(by).click();

    // 7. Type 'netahsilatotomasyon@yandex.com' in 'SearchVendorName'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#SearchVendorName");
    driver.findElement(by).sendKeys("netahsilatotomasyon@yandex.com");

    // 8. Click 'SearchVendorName'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#SearchVendorName");
    driver.findElement(by).click();

    // 9. Click 'resultListelenen'
    GeneratedUtils.sleep(500);
    by = By.xpath("//body/ul//div");
    driver.findElement(by).click();

    // 10. Click 'Listele'
    GeneratedUtils.sleep(500);
    by = By.xpath("//button[. = 'Listele']");
    driver.findElement(by).click();

    // 11. Is 'Listele' is clickable?
    GeneratedUtils.sleep(500);
    by = By.xpath("//button[. = 'Listele']");
    (new WebDriverWait(driver, 15)).until(ExpectedConditions.elementToBeClickable(by));

    // 12. Click 'Ödeme'
    GeneratedUtils.sleep(500);
    by = By.xpath("//a[. = 'Ödeme']");
    driver.findElement(by).click();

    // 13. Switch to window '1'
    GeneratedUtils.sleep(500);
    driver.switchTo().window(driver.getWindowHandles().toArray(new String[0])[1]);

    // 14. Click 'KART KAYDI LİNKİ'
    GeneratedUtils.sleep(500);
    by = By.xpath("//a[. = 'KART KAYDI LİNKİ']");
    driver.findElement(by).click();

    // 15. Click 'QrTypeSelection'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#QrTypeSelection");
    driver.findElement(by).click();

    // 16. Is 'carduser' visible and selected?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("[name='carduser']");
    (new WebDriverWait(driver, 15)).until(ExpectedConditions.elementSelectionStateToBe(by, true));

    // 17. Type 'test' in 'NewUserFullName'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#NewUserFullName");
    driver.findElement(by).sendKeys("test");

    // 18. Type 'test@test.com' in 'NewUserEmail'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#NewUserEmail");
    driver.findElement(by).sendKeys("test@test.com");

    // 19. Type '2222222222' in 'NewUserPhone'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#NewUserPhone");
    driver.findElement(by).sendKeys("2222222222");

    // 20. Click 'Ekle'
    GeneratedUtils.sleep(500);
    by = By.xpath("//button[. = 'Ekle']");
    driver.findElement(by).click();

    // 21. Click 'clickTestRadioButton'
    GeneratedUtils.sleep(500);
    by = By.xpath("//*[text()='test']/..//input[@name='carduser']");
    driver.findElement(by).click();

    // 22. Is 'clickBreyselTurkButton' visible and selected?
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);
    try {
      GeneratedUtils.sleep(500);
      by = By.xpath("//*[text()='Bireysel türk']/..//input[@name='carduser']");
      (new WebDriverWait(driver, 15)).until(ExpectedConditions.elementSelectionStateToBe(by, true));
      Assertions.fail("Step 'Is 'clickBreyselTurkButton' visible and selected?' result inverted, step failed");
    }
    catch (RuntimeException ex) {
    }
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 23. Click 'testSil'
    GeneratedUtils.sleep(500);
    by = By.xpath("//*[text()='test']/..//a");
    driver.findElement(by).click();

    // 24. Click 'clickBreyselTurkButton'
    GeneratedUtils.sleep(500);
    by = By.xpath("//*[text()='Bireysel türk']/..//input[@name='carduser']");
    driver.findElement(by).click();

    // 25. Click 'Gönder'
    GeneratedUtils.sleep(500);
    by = By.xpath("//button[. = 'Gönder']");
    driver.findElement(by).click();

    // 26. Is 'Kart kaydetme sayfasına yönlenebilmek...' present?
    GeneratedUtils.sleep(500);
    by = By.xpath("//h4[. = '\n            Kart kaydetme sayfasına yönlenebilmek için telefonunuzdan aşağıdaki QR bilgisini okutunuz.\n        ']");
    driver.findElement(by);

    // 27. Is 'IMG' present?
    GeneratedUtils.sleep(500);
    by = By.xpath("//div[2]/div//img");
    driver.findElement(by);

    // 28. Is 'İsim' present?
    GeneratedUtils.sleep(500);
    by = By.xpath("//strong[. = 'İsim']");
    driver.findElement(by);

    // 29. Is 'Bireysel türk' present?
    GeneratedUtils.sleep(500);
    by = By.xpath("//td[. = 'Bireysel türk']");
    driver.findElement(by);

    // 30. Is 'Telefon' present?
    GeneratedUtils.sleep(500);
    by = By.xpath("//strong[. = 'Telefon']");
    driver.findElement(by);

    // 31. Is 'E-Posta' present?
    GeneratedUtils.sleep(500);
    by = By.xpath("//strong[. = 'E-Posta']");
    driver.findElement(by);

    // 32. Is 'ne*****************@ya********' present?
    GeneratedUtils.sleep(500);
    by = By.xpath("//td[. = 'ne*****************@ya********']");
    driver.findElement(by);

    // 33. Is 'Yazdır' present?
    GeneratedUtils.sleep(500);
    by = By.xpath("//button[. = '  Yazdır']");
    driver.findElement(by);

    // 34. Is 'Geri' present?
    GeneratedUtils.sleep(500);
    by = By.xpath("//button[. = 'Geri']");
    driver.findElement(by);

  }

  @Override
  public ReportingDriver getDriver() {
    return (ReportingDriver) driver;
  }

  @AfterAll
  static void tearDown() {
    if (driver != null) {
      driver.quit();
    }
  }

  private static Stream provideParameters() throws Exception {
    return Stream.of(Arguments.of("https://otomasyon3.netahsilatdemo.com/"));
  }
}
