package netahsilat;

import io.testproject.addon.DateTimeOperations;
import io.testproject.sdk.drivers.ReportingDriver;
import io.testproject.sdk.drivers.web.RemoteWebDriver;
import io.testproject.sdk.interfaces.junit5.ExceptionsReporter;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.concurrent.TimeUnit;
import java.util.stream.Stream;

/**
 * This class was automatically generated by TestProject
 * Project: Quality Museum Project
 * Test: C3252
 * Generated by: Ahmet Furkan SIMSEK (furkan.simsek@qualitymuseum.com)
 * Generated on Sun Oct 09 19:34:07 GMT 2022.
 */
@DisplayName("C3252")
public class C3252 implements ExceptionsReporter {
  public static WebDriver driver;

  @BeforeAll
  static void setup() throws Exception {
    driver = new RemoteWebDriver("wThDxIHw4zNaCydjAhcfe81WrQPYlMBFI7FPwUwV8M41", new ChromeOptions(), "Ahmet Furkan SIMSEK");
  }

  /**
   * In order to upload the test to TestProject need to un-comment @ArgumentsSource and set in comment the @MethodSource
   * @org.junit.jupiter.params.provider.ArgumentsSource(io.testproject.sdk.interfaces.parameterization.TestProjectParameterizer.class) */
  @DisplayName("C3252")
  @ParameterizedTest
  @MethodSource("provideParameters")
  void execute(String ApplicationURL, String userName, String password, String CurrentDate) throws
      Exception {
    // set timeout for driver actions (similar to step timeout)
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);
    By by;
    boolean booleanResult;
    MethodLogin methodlogin;
    String string;
    DateTimeOperations.CurrentDate currentDate;

    // 1. Navigate to 'https://otomasyon3.netahsilatdemo.com/'
    GeneratedUtils.sleep(500);
    driver.navigate().to("https://otomasyon3.netahsilatdemo.com/");

    // 2. Run Method Login
    GeneratedUtils.sleep(500);
    methodlogin = new MethodLogin();
    methodlogin.ApplicationURL = "https://otomasyon3.netahsilatdemo.com/";
    methodlogin.userName = ProjectParameters.genelEmail;
    methodlogin.password = ProjectParameters.genelPassword;
    methodlogin.execute(driver);

    // 3. Move mouse to 'moveUstUyeYonetimi'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("li[class='content']");
    (new Actions(driver)).moveToElement(driver.findElement(by)).perform();

    // 4. Click 'ustUyeYonetimi'
    GeneratedUtils.sleep(500);
    by = By.xpath("//li[4]/a[. = 'ÜYE YÖNETİMİ']");
    driver.findElement(by).click();

    // 5. Click 'altUyeYonetimi'
    GeneratedUtils.sleep(500);
    by = By.xpath("//li[1]/a[. = 'ÜYE YÖNETİMİ']");
    driver.findElement(by).click();

    // 6. Type 'netahsilatotomasyon@yandex.com' in 'SearchVendorNameVN'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#SearchVendorName");
    driver.findElement(by).sendKeys("netahsilatotomasyon@yandex.com");

    // 7. Click 'resultListelenen'
    GeneratedUtils.sleep(500);
    by = By.xpath("//body/ul//div");
    driver.findElement(by).click();

    // 8. Click 'btnListele'
    GeneratedUtils.sleep(500);
    by = By.xpath("//button[. = 'Listele']");
    driver.findElement(by).click();

    // 9. Is 'Refresh' visible?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("a[class='t-icon t-refresh']");
    driver.findElement(by).isDisplayed();

    // 10. Click 'Ödeme1'
    GeneratedUtils.sleep(500);
    by = By.xpath("//a[. = 'Ödeme']");
    driver.findElement(by).click();

    // 11. Switch to window '1'
    GeneratedUtils.sleep(500);
    driver.switchTo().window(driver.getWindowHandles().toArray(new String[0])[1]);

    // 12. Is 'Bireysel türk7' visible?
    GeneratedUtils.sleep(500);
    by = By.xpath("//strong[. = 'Bireysel türk']");
    driver.findElement(by).isDisplayed();

    // 13. Click 'KART KAYDI LİNKİ'
    GeneratedUtils.sleep(500);
    by = By.xpath("//a[. = 'KART KAYDI LİNKİ']");
    driver.findElement(by).click();

    // 14. Click 'QrTypeSelection'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#QrTypeSelection");
    driver.findElement(by).click();

    // 15. Click 'Gönder2'
    GeneratedUtils.sleep(500);
    by = By.xpath("//button[. = 'Gönder']");
    driver.findElement(by).click();

    // 16. Switch to window '0'
    GeneratedUtils.sleep(500);
    driver.switchTo().window(driver.getWindowHandles().toArray(new String[0])[0]);

    // 17. Move mouse to 'moveToIslemler'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("li[class='tag']");
    (new Actions(driver)).moveToElement(driver.findElement(by)).perform();

    // 18. Click 'İŞLEMLER1'
    GeneratedUtils.sleep(500);
    by = By.xpath("//a[. = 'İŞLEMLER']");
    driver.findElement(by).click();

    // 19. Click 'KART KAYDETME LINKI LISTELEME1'
    GeneratedUtils.sleep(500);
    by = By.xpath("//a[. = 'Kart Kaydetme Linki Listeleme']");
    driver.findElement(by).click();

    // 20. Click 'Kart Kaydetme Linki Listeleme 1. Satır Detail Buton'
    GeneratedUtils.sleep(500);
    by = By.xpath("//*[@id=\"CardSaveLinkGrid\"]/table/tbody/tr[1]/td[1]/..//img[contains(@src,'salesdetail.png')]");
    driver.findElement(by).click();

    // 21. Is 'IMG97' present?
    GeneratedUtils.sleep(500);
    by = By.xpath("//td/img");
    driver.findElement(by);

    // 22. Get current date
    GeneratedUtils.sleep(500);
    currentDate = DateTimeOperations.currentDate("d.MM.yyyy HH:mm");
    currentDate = (DateTimeOperations.CurrentDate)((ReportingDriver)driver).addons().execute(currentDate);
    CurrentDate = String.valueOf(currentDate.result);

    // 23. Get text from 'TarihValidate'
    GeneratedUtils.sleep(500);
    by = By.xpath("//strong[normalize-space()='İstek Tarihi']/..//li");
    string = driver.findElement(by).getAttribute("value");
    Assertions.assertTrue(string.startsWith(CurrentDate));

    // 24. Does 'İstek Gönderildi1' contain 'İstek Gönderildi'?
    GeneratedUtils.sleep(500);
    by = By.xpath("//span[. = 'İstek Gönderildi']");
    Assertions.assertTrue(driver.findElement(by).getText().contains("İstek Gönderildi"));

    // 25. Does 'Gönderim Tipi QROrder' contain 'Gönderim Tipi'?
    GeneratedUtils.sleep(500);
    by = By.xpath("//strong[normalize-space()='Gönderim Tipi']");
    Assertions.assertTrue(driver.findElement(by).getText().contains("Gönderim Tipi"));

    // 26. Does 'İstek Yapan' contain 'İstek Yapan'?
    GeneratedUtils.sleep(500);
    by = By.xpath("//strong[. = 'İstek Yapan']");
    Assertions.assertTrue(driver.findElement(by).getText().contains("İstek Yapan"));

    // 27. Does 'Geçerlilik Tarihi2' contain 'Geçerlilik Tarihi'?
    GeneratedUtils.sleep(500);
    by = By.xpath("//strong[. = 'Geçerlilik Tarihi']");
    Assertions.assertTrue(driver.findElement(by).getText().contains("Geçerlilik Tarihi"));

    // 28. Does 'İşlem 1. Alıcı' contain ':Bi**** tü'?
    GeneratedUtils.sleep(500);
    by = By.xpath("//strong[normalize-space()='1. Alıcı']/..//..//td[2]");
    Assertions.assertTrue(driver.findElement(by).getText().contains(":Bi**** tü"));

    // 29. Does 'Kaydedilen Kart Sayısı' contain 'Kaydedilen Kart Sayısı'?
    GeneratedUtils.sleep(500);
    by = By.xpath("//strong[. = 'Kaydedilen Kart Sayısı']");
    Assertions.assertTrue(driver.findElement(by).getText().contains("Kaydedilen Kart Sayısı"));

    // 30. Is '1. Alıcı' present?
    GeneratedUtils.sleep(500);
    by = By.xpath("//strong[. = '1. Alıcı ']");
    driver.findElement(by);

    // 31. Is ':0' present?
    GeneratedUtils.sleep(500);
    by = By.xpath("//td[. = '\n                                :0\n                            ']");
    driver.findElement(by);

    // 32. Is 'IMG3' present?
    GeneratedUtils.sleep(500);
    by = By.xpath("//td/img");
    driver.findElement(by);

    // 33. Is 'Yazdır1' is clickable?
    GeneratedUtils.sleep(500);
    by = By.xpath("//a[. = 'Yazdır']");
    (new WebDriverWait(driver, 15)).until(ExpectedConditions.elementToBeClickable(by));

    // 34. Click 'btnKapat'
    GeneratedUtils.sleep(500);
    by = By.xpath("//button[. = 'Kapat']");
    driver.findElement(by).click();

  }

  @Override
  public ReportingDriver getDriver() {
    return (ReportingDriver) driver;
  }

  @AfterAll
  static void tearDown() {
    if (driver != null) {
      driver.quit();
    }
  }

  private static Stream provideParameters() throws Exception {
    return Stream.of(Arguments.of("https://otomasyon3.netahsilatdemo.com/","otomasyon@test.com","Kd!cyhz4",""));
  }
}
