package netahsilat;

import io.testproject.addon.ImapMailOperations;
import io.testproject.addon.VisibleElementsOperations;
import io.testproject.addon.WebExtensions;
import io.testproject.sdk.drivers.ReportingDriver;
import io.testproject.sdk.drivers.web.RemoteWebDriver;
import io.testproject.sdk.interfaces.junit5.ExceptionsReporter;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.concurrent.TimeUnit;
import java.util.stream.Stream;

/**
 * This class was automatically generated by TestProject
 * Project: Quality Museum Project
 * Test: C3832 MS - Url shortener kontrolü
 * Generated by: Ahmet Furkan SIMSEK (furkan.simsek@qualitymuseum.com)
 * Generated on Sun Oct 09 19:29:32 GMT 2022.
 */
@DisplayName("C3832 MS - Url shortener kontrolü")
public class C3832 implements ExceptionsReporter {
  public static WebDriver driver;

  @BeforeAll
  static void setup() throws Exception {
    driver = new RemoteWebDriver("wThDxIHw4zNaCydjAhcfe81WrQPYlMBFI7FPwUwV8M41", new ChromeOptions(), "Ahmet Furkan SIMSEK");
  }

  /**
   * In order to upload the test to TestProject need to un-comment @ArgumentsSource and set in comment the @MethodSource
   * @org.junit.jupiter.params.provider.ArgumentsSource(io.testproject.sdk.interfaces.parameterization.TestProjectParameterizer.class) */
  @DisplayName("C3832 MS - Url shortener kontrolü")
  @ParameterizedTest
  @MethodSource("provideParameters")
  void execute(String ApplicationURL, String userName, String password) throws Exception {
    // set timeout for driver actions (similar to step timeout)
    driver.manage().timeouts().implicitlyWait(2000, TimeUnit.MILLISECONDS);
    By by;
    boolean booleanResult;
    MethodLogin methodlogin;
    String string;
    ImapMailOperations.ReadSpecificsMail readSpecificsMail;
    ImapMailOperations.DeleteAllMails deleteAllMails;
    VisibleElementsOperations.ClickIfVisibleWeb clickIfVisibleWeb;
    WebExtensions.SetElementAttribute setElementAttribute;

    // 1. Navigate to '{{Otomasyon3Logout}}'
    driver.navigate().to(ProjectParameters.Otomasyon3Logout);

    // 2. Run Method Login
    methodlogin = new MethodLogin();
    methodlogin.ApplicationURL = ApplicationURL;
    methodlogin.userName = ProjectParameters.genelEmail;
    methodlogin.password = ProjectParameters.genelPassword;
    methodlogin.execute(driver);

    // 3. Delete All Mails
    deleteAllMails = ImapMailOperations.deleteAllMails(ProjectParameters.odemeEmail,ProjectParameters.yandexMailKey);
    deleteAllMails = (ImapMailOperations.DeleteAllMails)((ReportingDriver)driver).addons().execute(deleteAllMails);

    // 4. Move mouse to 'moveToSiteYönetimi'
    by = By.cssSelector("li[class='config']");
    (new Actions(driver)).moveToElement(driver.findElement(by)).perform();

    // 5. Click 'btnSiteYönetimi'
    by = By.cssSelector("a[title='SİTE YÖNETİMİ']");
    driver.findElement(by).click();

    // 6. Click 'PARAMETRELER1'
    by = By.xpath("//a[. = 'PARAMETRELER']");
    driver.findElement(by).click();

    // 7. Click 'Kart Kayıt Linki Parametreleri'
    by = By.xpath("//a[. = '\n            Kart Kayıt Linki Parametreleri\n        ']");
    driver.findElement(by).click();

    // 8. Click 'Url shortener aktif (Checked)' if it's visible
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(2000, TimeUnit.MILLISECONDS);
    clickIfVisibleWeb = VisibleElementsOperations.clickIfVisibleWeb("");
    by = By.xpath("//label[normalize-space()='Url shortener aktif']//..//..//span[@class='jquery-safari-checkbox']");
    clickIfVisibleWeb = (VisibleElementsOperations.ClickIfVisibleWeb)((ReportingDriver)driver).addons().execute(clickIfVisibleWeb, by, -1);
    driver.manage().timeouts().implicitlyWait(2000, TimeUnit.MILLISECONDS);

    // 9. Click 'Kaydet1'
    by = By.cssSelector("#kaydet");
    driver.findElement(by).click();

    // 10. Is 'Kart Kayıt Linki Parametreleri Başarı...' visible?
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);
    GeneratedUtils.sleep(500);
    by = By.xpath("//li[. = 'Kart Kayıt Linki Parametreleri Başarıyla kaydedildi.']");
    driver.findElement(by).isDisplayed();
    driver.manage().timeouts().implicitlyWait(2000, TimeUnit.MILLISECONDS);

    // 11. Move mouse to 'moveUstUyeYonetimi'
    by = By.cssSelector("li[class='content']");
    (new Actions(driver)).moveToElement(driver.findElement(by)).perform();

    // 12. Click 'ustUyeYonetimi'
    by = By.xpath("//li[4]/a[. = 'ÜYE YÖNETİMİ']");
    driver.findElement(by).click();

    // 13. Click 'altUyeYonetimi'
    by = By.xpath("//li[1]/a[. = 'ÜYE YÖNETİMİ']");
    driver.findElement(by).click();

    // 14. Type 'netahsilatotomasyon@yandex.com' in 'SearchVendorName'
    by = By.cssSelector("#SearchVendorName");
    driver.findElement(by).sendKeys("netahsilatotomasyon@yandex.com");

    // 15. Click 'resultListelenen'
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);
    GeneratedUtils.sleep(500);
    by = By.xpath("//body/ul//div");
    driver.findElement(by).click();
    driver.manage().timeouts().implicitlyWait(2000, TimeUnit.MILLISECONDS);

    // 16. Click 'Listele'
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);
    GeneratedUtils.sleep(500);
    by = By.xpath("//button[. = 'Listele']");
    driver.findElement(by).click();
    driver.manage().timeouts().implicitlyWait(2000, TimeUnit.MILLISECONDS);

    // 17. Is 'Refresh' visible?
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);
    GeneratedUtils.sleep(500);
    by = By.cssSelector("a[class='t-icon t-refresh']");
    driver.findElement(by).isDisplayed();
    driver.manage().timeouts().implicitlyWait(2000, TimeUnit.MILLISECONDS);

    // 18. Set 'target' attribute value on 'Ödeme'
    setElementAttribute = WebExtensions.setElementAttribute("target","_top");
    by = By.xpath("//a[. = 'Ödeme']");
    setElementAttribute = (WebExtensions.SetElementAttribute)((ReportingDriver)driver).addons().execute(setElementAttribute, by, -1);

    // 19. Click 'Ödeme'
    by = By.xpath("//a[. = 'Ödeme']");
    driver.findElement(by).click();

    // 20. Is 'Bireysel türk1' visible?
    by = By.xpath("//strong[. = 'Bireysel türk']");
    driver.findElement(by).isDisplayed();

    // 21. Click 'KART KAYDI LİNKİ'
    by = By.xpath("//a[. = 'KART KAYDI LİNKİ']");
    driver.findElement(by).click();

    // 22. Click 'EmailTypeSelection (Unchecked)'
    by = By.cssSelector("#EmailTypeSelection:not(:checked)");
    driver.findElement(by).click();

    // 23. Does 'Bireysel Türk Eposta ' contain 'netahsilatotomasyon@yandex.com'?
    by = By.xpath("//td[text()='Bireysel türk']/..//td[3]");
    Assertions.assertTrue(driver.findElement(by).getText().contains("netahsilatotomasyon@yandex.com"));

    // 24. Is 'kart Kaydeyme Bireysel Türk Checkbox' visible and selected?
    by = By.xpath("//td[text()='Bireysel türk']/..//input[1]");
    (new WebDriverWait(driver, 2)).until(ExpectedConditions.elementSelectionStateToBe(by, true));

    // 25. Click 'Gönder'
    by = By.xpath("//button[. = 'Gönder']");
    driver.findElement(by).click();

    // 26. Is 'İşleminiz başarıyla tamamlanmıştır' visible?
    by = By.xpath("//h4[. = 'İşleminiz başarıyla tamamlanmıştır']");
    driver.findElement(by).isDisplayed();

    // 27. Is 'Ana Sayfa' visible?
    by = By.xpath("//a[. = 'Ana Sayfa']");
    driver.findElement(by).isDisplayed();

    // 28. Is 'Kart Kayıt Linki Gönder' visible?
    by = By.xpath("//a[. = 'Kart Kayıt Linki Gönder ']");
    driver.findElement(by).isDisplayed();

    // 29. Output searched string in specific mail
    readSpecificsMail = ImapMailOperations.readSpecificsMail(ProjectParameters.odemeEmail,ProjectParameters.yandexMailKey,"http://otomasyon3.netahsilatdemo.com/","C:/TestProject/mail/C3832.html");
    readSpecificsMail = (ImapMailOperations.ReadSpecificsMail)((ReportingDriver)driver).addons().execute(readSpecificsMail);

    // 30. Navigate to 'file:///C:/TestProject/mail/C3832.html'
    driver.navigate().to("file:///C:/TestProject/mail/C3832.html");

    // 31. Get text from 'KAYIT_LINKI'
    by = By.cssSelector("#KAYIT_LINKI");
    string = driver.findElement(by).getAttribute("value");
    Assertions.assertTrue(string.startsWith("https://thsl.at"));

    // 32. Navigate back
    driver.navigate().back();

    // 33. Click 'YÖNETİCİ1'
    by = By.xpath("//a[. = 'YÖNETİCİ']");
    driver.findElement(by).click();

    // 34. Move mouse to 'moveToSiteYönetimi'
    by = By.cssSelector("li[class='config']");
    (new Actions(driver)).moveToElement(driver.findElement(by)).perform();

    // 35. Click 'btnSiteYönetimi'
    by = By.cssSelector("a[title='SİTE YÖNETİMİ']");
    driver.findElement(by).click();

    // 36. Click 'PARAMETRELER1'
    by = By.xpath("//a[. = 'PARAMETRELER']");
    driver.findElement(by).click();

    // 37. Click 'Kart Kayıt Linki Parametreleri'
    by = By.xpath("//a[. = '\n            Kart Kayıt Linki Parametreleri\n        ']");
    driver.findElement(by).click();

    // 38. Click 'Url shortener aktif (UnChecked)'
    by = By.xpath("//label[normalize-space()='Url shortener aktif']//..//..//span[@class='jquery-safari-checkbox jquery-safari-checkbox-checked']");
    driver.findElement(by).click();

    // 39. Click 'Kaydet1'
    by = By.cssSelector("#kaydet");
    driver.findElement(by).click();

    // 40. Is 'Kart Kayıt Linki Parametreleri Başarı...' visible?
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);
    GeneratedUtils.sleep(500);
    by = By.xpath("//li[. = 'Kart Kayıt Linki Parametreleri Başarıyla kaydedildi.']");
    driver.findElement(by).isDisplayed();
    driver.manage().timeouts().implicitlyWait(2000, TimeUnit.MILLISECONDS);

  }

  @Override
  public ReportingDriver getDriver() {
    return (ReportingDriver) driver;
  }

  @AfterAll
  static void tearDown() {
    if (driver != null) {
      driver.quit();
    }
  }

  private static Stream provideParameters() throws Exception {
    return Stream.of(Arguments.of("https://otomasyon3.netahsilatdemo.com/","otomasyon@test.com","Kd!cyhz4"));
  }
}
