package netahsilat;

import io.testproject.addon.GridOperations;
import io.testproject.sdk.drivers.ReportingDriver;
import io.testproject.sdk.drivers.web.RemoteWebDriver;
import io.testproject.sdk.interfaces.junit5.ExceptionsReporter;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;

import java.util.concurrent.TimeUnit;
import java.util.stream.Stream;

/**
 * This class was automatically generated by TestProject
 * Project: Quality Museum Project
 * Test: C438 Kullanıcı İle Listeleme
 * Generated by: Ahmet Furkan SIMSEK (furkan.simsek@qualitymuseum.com)
 * Generated on Mon Oct 03 13:52:34 GMT 2022.
 */
@DisplayName("C438 Kullanıcı İle Listeleme")
public class C438 implements ExceptionsReporter {
  public static WebDriver driver;

  @BeforeAll
  static void setup() throws Exception {
    driver = new RemoteWebDriver("wThDxIHw4zNaCydjAhcfe81WrQPYlMBFI7FPwUwV8M41", new ChromeOptions(), "Ahmet Furkan SIMSEK");
  }

  /**
   * In order to upload the test to TestProject need to un-comment @ArgumentsSource and set in comment the @MethodSource
   * @org.junit.jupiter.params.provider.ArgumentsSource(io.testproject.sdk.interfaces.parameterization.TestProjectParameterizer.class) */
  @DisplayName("C438 Kullanıcı İle Listeleme")
  @ParameterizedTest
  @MethodSource("provideParameters")
  void execute(String ApplicationURL, String userName, String password) throws Exception {
    // set timeout for driver actions (similar to step timeout)
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);
    By by;
    boolean booleanResult;
    MethodLogoutlogin methodlogoutlogin;
    GridOperations.GetData getData;

    // 1. Run Method Logout&Login
    GeneratedUtils.sleep(500);
    methodlogoutlogin = new MethodLogoutlogin();
    methodlogoutlogin.ApplicationURL = ApplicationURL;
    methodlogoutlogin.userName = userName;
    methodlogoutlogin.password = password;
    methodlogoutlogin.execute(driver);

    // 2. Move mouse to 'moveToIslemler'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("li[class='tag']");
    (new Actions(driver)).moveToElement(driver.findElement(by)).perform();

    // 3. Click 'İŞLEMLER'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("a[title='İŞLEMLER']");
    driver.findElement(by).click();

    // 4. Click 'İşlemDetaylarıListesi'
    GeneratedUtils.sleep(500);
    by = By.xpath("//a[. = 'İŞLEM DETAYLARI LİSTESİ']");
    driver.findElement(by).click();

    // 5. Type 'TestAd SoyadTest' in 'AppUserName'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#AppUserName");
    driver.findElement(by).sendKeys("TestAd SoyadTest");

    // 6. Is 'kullaniciTestAdSoyadTest' visible?
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(35000, TimeUnit.MILLISECONDS);
    GeneratedUtils.sleep(500);
    by = By.xpath("/html/body/ul[3]/li/div");
    driver.findElement(by).isDisplayed();
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 7. Clear 'AppUserName' contents
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#AppUserName");
    driver.findElement(by).clear();

    // 8. Type 'SoyadTest' in 'AppUserName'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#AppUserName");
    driver.findElement(by).sendKeys("SoyadTest");

    // 9. Is 'AppUserName' visible?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#AppUserName");
    driver.findElement(by).isDisplayed();

    // 10. Clear 'AppUserName' contents
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#AppUserName");
    driver.findElement(by).clear();

    // 11. Type 'furkan.akkoc@ecozum.com' in 'AppUserName'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#AppUserName");
    driver.findElement(by).sendKeys("furkan.akkoc@ecozum.com");

    // 12. Is 'kullaniciTestAdSoyadTest' visible?
    GeneratedUtils.sleep(500);
    by = By.xpath("/html/body/ul[3]/li/div");
    driver.findElement(by).isDisplayed();

    // 13. Clear 'AppUserName' contents
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#AppUserName");
    driver.findElement(by).clear();

    // 14. Type '76012133968' in 'AppUserName'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#AppUserName");
    driver.findElement(by).sendKeys("76012133968");

    // 15. Is 'kullaniciTestAdSoyadTest' visible?
    GeneratedUtils.sleep(500);
    by = By.xpath("/html/body/ul[3]/li/div");
    driver.findElement(by).isDisplayed();

    // 16. Clear 'AppUserName' contents
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#AppUserName");
    driver.findElement(by).clear();

    // 17. Type 'Bayi123' in 'AppUserName'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#AppUserName");
    driver.findElement(by).sendKeys("Bayi123");

    // 18. Is 'kullaniciTestAdSoyadTest' visible?
    GeneratedUtils.sleep(500);
    by = By.xpath("/html/body/ul[3]/li/div");
    driver.findElement(by).isDisplayed();

    // 19. Click 'kullaniciTestAdSoyadTest'
    GeneratedUtils.sleep(500);
    by = By.xpath("/html/body/ul[3]/li/div");
    driver.findElement(by).click();

    // 20. Clear 'StartDate' contents
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#StartDate");
    driver.findElement(by).clear();

    // 21. Click 'btnListele'
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(35000, TimeUnit.MILLISECONDS);
    GeneratedUtils.sleep(500);
    by = By.xpath("//button[. = 'Listele']");
    driver.findElement(by).click();
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 22. Is 'Refresh' visible?
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(35000, TimeUnit.MILLISECONDS);
    GeneratedUtils.sleep(500);
    by = By.cssSelector("a[class='t-icon t-refresh']");
    driver.findElement(by).isDisplayed();
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 23. Run Get Data From Grid
    //    Kullanıcı - TestAd - Equals
    GeneratedUtils.sleep(500);
    getData = GridOperations.getData("Kullanıcı","TestAd","Equals");
    getData = (GridOperations.GetData)((ReportingDriver)driver).addons().execute(getData);

  }

  @Override
  public ReportingDriver getDriver() {
    return (ReportingDriver) driver;
  }

  @AfterAll
  static void tearDown() {
    if (driver != null) {
      driver.quit();
    }
  }

  private static Stream provideParameters() throws Exception {
    return Stream.of(Arguments.of("https://otomasyon.netahsilatdemo.com/Account/LogOff","",""));
  }
}
