package netahsilat;

import io.testproject.addon.GridOperations;
import io.testproject.addon.WebExtensions;
import io.testproject.sdk.drivers.ReportingDriver;
import io.testproject.sdk.drivers.web.RemoteWebDriver;
import io.testproject.sdk.interfaces.junit5.ExceptionsReporter;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;

import java.util.concurrent.TimeUnit;
import java.util.stream.Stream;

/**
 * This class was automatically generated by TestProject
 * Project: Quality Museum Project
 * Test: C4598 Default Grupların Silme ve düzenleme özelliği olmamalıdır.
 * Generated by: Ahmet Furkan SIMSEK (furkan.simsek@qualitymuseum.com)
 * Generated on Mon Oct 10 07:14:56 GMT 2022.
 */
@DisplayName("C4598 Default Grupların Silme ve düzenleme özelliği olmamalıdır.")
public class C4598 implements ExceptionsReporter {
  public static WebDriver driver;

  @BeforeAll
  static void setup() throws Exception {
    driver = new RemoteWebDriver("wThDxIHw4zNaCydjAhcfe81WrQPYlMBFI7FPwUwV8M41", new ChromeOptions(), "Ahmet Furkan SIMSEK");
  }

  /**
   * In order to upload the test to TestProject need to un-comment @ArgumentsSource and set in comment the @MethodSource
   * @org.junit.jupiter.params.provider.ArgumentsSource(io.testproject.sdk.interfaces.parameterization.TestProjectParameterizer.class) */
  @DisplayName("C4598 Default Grupların Silme ve düzenleme özelliği olmamalıdır.")
  @ParameterizedTest
  @MethodSource("provideParameters")
  void execute(String ApplicationURL, String userName, String password, String currentDateTime,
      String RolName) throws Exception {
    // set timeout for driver actions (similar to step timeout)
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);
    By by;
    boolean booleanResult;
    MethodLogin methodlogin;
    WebExtensions.SelectOptionbyVisibleText selectOptionbyVisibleText;
    WebExtensions.GetElementAttribute getElementAttribute;
    GridOperations.GetData getData;

    // 1. Navigate to '{{Otomasyon3Logout}}'
    GeneratedUtils.sleep(500);
    driver.navigate().to(ProjectParameters.Otomasyon3Logout);

    // 2. Run Method Login
    //    otomasyon@test.com
    GeneratedUtils.sleep(500);
    methodlogin = new MethodLogin();
    methodlogin.ApplicationURL = ApplicationURL;
    methodlogin.userName = "otomasyon@test.com";
    methodlogin.password = ProjectParameters.genelPassword;
    methodlogin.execute(driver);
    currentDateTime = String.valueOf(methodlogin.currentDateTime);

    // 3. Click 'moveToKullaniciYönetimi'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("li[class='user']");
    driver.findElement(by).click();

    // 4. Click 'KULLANICI YÖNETİMİ1'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("a[title='KULLANICI YÖNETİMİ']");
    driver.findElement(by).click();

    // 5. Click 'ROL YÖNETİMİ'
    GeneratedUtils.sleep(500);
    by = By.xpath("//a[. = 'ROL YÖNETİMİ']");
    driver.findElement(by).click();

    // 6. Select options in 'RoleGroupId' with text '[NONE]'
    GeneratedUtils.sleep(500);
    selectOptionbyVisibleText = WebExtensions.selectOptionbyVisibleText("Site Admin");
    by = By.cssSelector("#RoleGroupId");
    selectOptionbyVisibleText = (WebExtensions.SelectOptionbyVisibleText)((ReportingDriver)driver).addons().execute(selectOptionbyVisibleText, by, -1);

    // 7. Run Get Data From Grid
    //    Rol Grubu
    GeneratedUtils.sleep(500);
    getData = GridOperations.getData("Rol Grubu","Site Admin","Equals");
    getData = (GridOperations.GetData)((ReportingDriver)driver).addons().execute(getData);

    // 8. Run Get Data From Grid
    //    Yetki Tipi
    GeneratedUtils.sleep(500);
    getData = GridOperations.getData("Yetki Tipi","Site","Equals");
    getData = (GridOperations.GetData)((ReportingDriver)driver).addons().execute(getData);

    // 9. Run Get Data From Grid
    //    Ekleyen Kullanıcı Tipi
    GeneratedUtils.sleep(500);
    getData = GridOperations.getData("Ekleyen Kullanıcı Tipi","Default","Equals");
    getData = (GridOperations.GetData)((ReportingDriver)driver).addons().execute(getData);

    // 10. Get 'style' attribute value on 'Trash.png'
    //    Disabled olduğunun validate edilmesi
    GeneratedUtils.sleep(500);
    getElementAttribute = WebExtensions.getElementAttribute("style");
    by = By.xpath("//img[contains(@src,'trash.png')]");
    getElementAttribute = (WebExtensions.GetElementAttribute)((ReportingDriver)driver).addons().execute(getElementAttribute, by, -1);

    // 11. Get 'style' attribute value on 'edit.png'
    //    Disabled olduğunun validate edilmesi
    GeneratedUtils.sleep(500);
    getElementAttribute = WebExtensions.getElementAttribute("style");
    by = By.xpath("//img[contains(@src,'edit.png')]");
    getElementAttribute = (WebExtensions.GetElementAttribute)((ReportingDriver)driver).addons().execute(getElementAttribute, by, -1);

    // 12. Get 'style' attribute value on 'copy.png'
    //    enable olduğunun validate edilmesi
    GeneratedUtils.sleep(500);
    getElementAttribute = WebExtensions.getElementAttribute("style");
    by = By.xpath("//img[contains(@src,'copy.png')]");
    getElementAttribute = (WebExtensions.GetElementAttribute)((ReportingDriver)driver).addons().execute(getElementAttribute, by, -1);

    // 13. Select options in 'RoleGroupId' with text '[NONE]'
    GeneratedUtils.sleep(500);
    selectOptionbyVisibleText = WebExtensions.selectOptionbyVisibleText("Site Muhasebe");
    by = By.cssSelector("#RoleGroupId");
    selectOptionbyVisibleText = (WebExtensions.SelectOptionbyVisibleText)((ReportingDriver)driver).addons().execute(selectOptionbyVisibleText, by, -1);

    // 14. Run Get Data From Grid
    //    Rol Grubu
    GeneratedUtils.sleep(500);
    getData = GridOperations.getData("Rol Grubu","Site Muhasebe","Equals");
    getData = (GridOperations.GetData)((ReportingDriver)driver).addons().execute(getData);

    // 15. Run Get Data From Grid
    //    Yetki Tipi
    GeneratedUtils.sleep(500);
    getData = GridOperations.getData("Yetki Tipi","Site","Equals");
    getData = (GridOperations.GetData)((ReportingDriver)driver).addons().execute(getData);

    // 16. Run Get Data From Grid
    //    Ekleyen Kullanıcı Tipi
    GeneratedUtils.sleep(500);
    getData = GridOperations.getData("Ekleyen Kullanıcı Tipi","Default","Equals");
    getData = (GridOperations.GetData)((ReportingDriver)driver).addons().execute(getData);

    // 17. Get 'style' attribute value on 'Trash.png'
    //    Disabled olduğunun validate edilmesi
    GeneratedUtils.sleep(500);
    getElementAttribute = WebExtensions.getElementAttribute("style");
    by = By.xpath("//img[contains(@src,'trash.png')]");
    getElementAttribute = (WebExtensions.GetElementAttribute)((ReportingDriver)driver).addons().execute(getElementAttribute, by, -1);

    // 18. Get 'style' attribute value on 'edit.png'
    //    Disabled olduğunun validate edilmesi
    GeneratedUtils.sleep(500);
    getElementAttribute = WebExtensions.getElementAttribute("style");
    by = By.xpath("//img[contains(@src,'edit.png')]");
    getElementAttribute = (WebExtensions.GetElementAttribute)((ReportingDriver)driver).addons().execute(getElementAttribute, by, -1);

    // 19. Get 'style' attribute value on 'copy.png'
    //    enable olduğunun validate edilmesi
    GeneratedUtils.sleep(500);
    getElementAttribute = WebExtensions.getElementAttribute("style");
    by = By.xpath("//img[contains(@src,'copy.png')]");
    getElementAttribute = (WebExtensions.GetElementAttribute)((ReportingDriver)driver).addons().execute(getElementAttribute, by, -1);

    // 20. Select options in 'RoleGroupId' with text '[NONE]'
    GeneratedUtils.sleep(500);
    selectOptionbyVisibleText = WebExtensions.selectOptionbyVisibleText("Müşteri Temsilcisi(Tüm)");
    by = By.cssSelector("#RoleGroupId");
    selectOptionbyVisibleText = (WebExtensions.SelectOptionbyVisibleText)((ReportingDriver)driver).addons().execute(selectOptionbyVisibleText, by, -1);

    // 21. Run Get Data From Grid
    //    Rol Grubu
    GeneratedUtils.sleep(500);
    getData = GridOperations.getData("Rol Grubu","Müşteri Temsilcisi(Tüm)","Equals");
    getData = (GridOperations.GetData)((ReportingDriver)driver).addons().execute(getData);

    // 22. Run Get Data From Grid
    //    Yetki Tipi
    GeneratedUtils.sleep(500);
    getData = GridOperations.getData("Yetki Tipi","Site","Equals");
    getData = (GridOperations.GetData)((ReportingDriver)driver).addons().execute(getData);

    // 23. Run Get Data From Grid
    //    Ekleyen Kullanıcı Tipi
    GeneratedUtils.sleep(500);
    getData = GridOperations.getData("Ekleyen Kullanıcı Tipi","Default","Equals");
    getData = (GridOperations.GetData)((ReportingDriver)driver).addons().execute(getData);

    // 24. Get 'style' attribute value on 'Trash.png'
    //    Disabled olduğunun validate edilmesi
    GeneratedUtils.sleep(500);
    getElementAttribute = WebExtensions.getElementAttribute("style");
    by = By.xpath("//img[contains(@src,'trash.png')]");
    getElementAttribute = (WebExtensions.GetElementAttribute)((ReportingDriver)driver).addons().execute(getElementAttribute, by, -1);

    // 25. Get 'style' attribute value on 'edit.png'
    //    Disabled olduğunun validate edilmesi
    GeneratedUtils.sleep(500);
    getElementAttribute = WebExtensions.getElementAttribute("style");
    by = By.xpath("//img[contains(@src,'edit.png')]");
    getElementAttribute = (WebExtensions.GetElementAttribute)((ReportingDriver)driver).addons().execute(getElementAttribute, by, -1);

    // 26. Get 'style' attribute value on 'copy.png'
    //    enable olduğunun validate edilmesi
    GeneratedUtils.sleep(500);
    getElementAttribute = WebExtensions.getElementAttribute("style");
    by = By.xpath("//img[contains(@src,'copy.png')]");
    getElementAttribute = (WebExtensions.GetElementAttribute)((ReportingDriver)driver).addons().execute(getElementAttribute, by, -1);

    // 27. Select options in 'RoleGroupId' with text '[NONE]'
    GeneratedUtils.sleep(500);
    selectOptionbyVisibleText = WebExtensions.selectOptionbyVisibleText("Müşteri Temsilcisi(Kendi)");
    by = By.cssSelector("#RoleGroupId");
    selectOptionbyVisibleText = (WebExtensions.SelectOptionbyVisibleText)((ReportingDriver)driver).addons().execute(selectOptionbyVisibleText, by, -1);

    // 28. Run Get Data From Grid
    //    Rol Grubu
    GeneratedUtils.sleep(500);
    getData = GridOperations.getData("Rol Grubu","Müşteri Temsilcisi(Kendi)","Equals");
    getData = (GridOperations.GetData)((ReportingDriver)driver).addons().execute(getData);

    // 29. Run Get Data From Grid
    //    Yetki Tipi
    GeneratedUtils.sleep(500);
    getData = GridOperations.getData("Yetki Tipi","Site","Equals");
    getData = (GridOperations.GetData)((ReportingDriver)driver).addons().execute(getData);

    // 30. Run Get Data From Grid
    //    Ekleyen Kullanıcı Tipi
    GeneratedUtils.sleep(500);
    getData = GridOperations.getData("Ekleyen Kullanıcı Tipi","Default","Equals");
    getData = (GridOperations.GetData)((ReportingDriver)driver).addons().execute(getData);

    // 31. Get 'style' attribute value on 'Trash.png'
    //    Disabled olduğunun validate edilmesi
    GeneratedUtils.sleep(500);
    getElementAttribute = WebExtensions.getElementAttribute("style");
    by = By.xpath("//img[contains(@src,'trash.png')]");
    getElementAttribute = (WebExtensions.GetElementAttribute)((ReportingDriver)driver).addons().execute(getElementAttribute, by, -1);

    // 32. Get 'style' attribute value on 'edit.png'
    //    Disabled olduğunun validate edilmesi
    GeneratedUtils.sleep(500);
    getElementAttribute = WebExtensions.getElementAttribute("style");
    by = By.xpath("//img[contains(@src,'edit.png')]");
    getElementAttribute = (WebExtensions.GetElementAttribute)((ReportingDriver)driver).addons().execute(getElementAttribute, by, -1);

    // 33. Get 'style' attribute value on 'copy.png'
    //    enable olduğunun validate edilmesi
    GeneratedUtils.sleep(500);
    getElementAttribute = WebExtensions.getElementAttribute("style");
    by = By.xpath("//img[contains(@src,'copy.png')]");
    getElementAttribute = (WebExtensions.GetElementAttribute)((ReportingDriver)driver).addons().execute(getElementAttribute, by, -1);

    // 34. Select options in 'RoleGroupId' with text '[NONE]'
    GeneratedUtils.sleep(500);
    selectOptionbyVisibleText = WebExtensions.selectOptionbyVisibleText("Bayi Admin");
    by = By.cssSelector("#RoleGroupId");
    selectOptionbyVisibleText = (WebExtensions.SelectOptionbyVisibleText)((ReportingDriver)driver).addons().execute(selectOptionbyVisibleText, by, -1);

    // 35. Run Get Data From Grid
    //    Rol Grubu
    GeneratedUtils.sleep(500);
    getData = GridOperations.getData("Rol Grubu","Bayi Admin","Equals");
    getData = (GridOperations.GetData)((ReportingDriver)driver).addons().execute(getData);

    // 36. Run Get Data From Grid
    //    Yetki Tipi
    GeneratedUtils.sleep(500);
    getData = GridOperations.getData("Yetki Tipi","Bayi","Equals");
    getData = (GridOperations.GetData)((ReportingDriver)driver).addons().execute(getData);

    // 37. Run Get Data From Grid
    //    Ekleyen Kullanıcı Tipi
    GeneratedUtils.sleep(500);
    getData = GridOperations.getData("Ekleyen Kullanıcı Tipi","Default","Equals");
    getData = (GridOperations.GetData)((ReportingDriver)driver).addons().execute(getData);

    // 38. Get 'style' attribute value on 'Trash.png'
    //    Disabled olduğunun validate edilmesi
    GeneratedUtils.sleep(500);
    getElementAttribute = WebExtensions.getElementAttribute("style");
    by = By.xpath("//img[contains(@src,'trash.png')]");
    getElementAttribute = (WebExtensions.GetElementAttribute)((ReportingDriver)driver).addons().execute(getElementAttribute, by, -1);

    // 39. Get 'style' attribute value on 'edit.png'
    //    Disabled olduğunun validate edilmesi
    GeneratedUtils.sleep(500);
    getElementAttribute = WebExtensions.getElementAttribute("style");
    by = By.xpath("//img[contains(@src,'edit.png')]");
    getElementAttribute = (WebExtensions.GetElementAttribute)((ReportingDriver)driver).addons().execute(getElementAttribute, by, -1);

    // 40. Get 'style' attribute value on 'copy.png'
    //    enable olduğunun validate edilmesi
    GeneratedUtils.sleep(500);
    getElementAttribute = WebExtensions.getElementAttribute("style");
    by = By.xpath("//img[contains(@src,'copy.png')]");
    getElementAttribute = (WebExtensions.GetElementAttribute)((ReportingDriver)driver).addons().execute(getElementAttribute, by, -1);

    // 41. Select options in 'RoleGroupId' with text '[NONE]'
    GeneratedUtils.sleep(500);
    selectOptionbyVisibleText = WebExtensions.selectOptionbyVisibleText("Bayi Muhasebe");
    by = By.cssSelector("#RoleGroupId");
    selectOptionbyVisibleText = (WebExtensions.SelectOptionbyVisibleText)((ReportingDriver)driver).addons().execute(selectOptionbyVisibleText, by, -1);

    // 42. Run Get Data From Grid
    //    Rol Grubu
    GeneratedUtils.sleep(500);
    getData = GridOperations.getData("Rol Grubu","Bayi Muhasebe","Equals");
    getData = (GridOperations.GetData)((ReportingDriver)driver).addons().execute(getData);

    // 43. Run Get Data From Grid
    //    Yetki Tipi
    GeneratedUtils.sleep(500);
    getData = GridOperations.getData("Yetki Tipi","Bayi","Equals");
    getData = (GridOperations.GetData)((ReportingDriver)driver).addons().execute(getData);

    // 44. Run Get Data From Grid
    //    Ekleyen Kullanıcı Tipi
    GeneratedUtils.sleep(500);
    getData = GridOperations.getData("Ekleyen Kullanıcı Tipi","Default","Equals");
    getData = (GridOperations.GetData)((ReportingDriver)driver).addons().execute(getData);

    // 45. Get 'style' attribute value on 'Trash.png'
    //    Disabled olduğunun validate edilmesi
    GeneratedUtils.sleep(500);
    getElementAttribute = WebExtensions.getElementAttribute("style");
    by = By.xpath("//img[contains(@src,'trash.png')]");
    getElementAttribute = (WebExtensions.GetElementAttribute)((ReportingDriver)driver).addons().execute(getElementAttribute, by, -1);

    // 46. Get 'style' attribute value on 'edit.png'
    //    Disabled olduğunun validate edilmesi
    GeneratedUtils.sleep(500);
    getElementAttribute = WebExtensions.getElementAttribute("style");
    by = By.xpath("//img[contains(@src,'edit.png')]");
    getElementAttribute = (WebExtensions.GetElementAttribute)((ReportingDriver)driver).addons().execute(getElementAttribute, by, -1);

    // 47. Get 'style' attribute value on 'copy.png'
    //    enable olduğunun validate edilmesi
    GeneratedUtils.sleep(500);
    getElementAttribute = WebExtensions.getElementAttribute("style");
    by = By.xpath("//img[contains(@src,'copy.png')]");
    getElementAttribute = (WebExtensions.GetElementAttribute)((ReportingDriver)driver).addons().execute(getElementAttribute, by, -1);

    // 48. Select options in 'RoleGroupId' with text '[NONE]'
    GeneratedUtils.sleep(500);
    selectOptionbyVisibleText = WebExtensions.selectOptionbyVisibleText("Alt Bayi Admin");
    by = By.cssSelector("#RoleGroupId");
    selectOptionbyVisibleText = (WebExtensions.SelectOptionbyVisibleText)((ReportingDriver)driver).addons().execute(selectOptionbyVisibleText, by, -1);

    // 49. Run Get Data From Grid
    //    Rol Grubu
    GeneratedUtils.sleep(500);
    getData = GridOperations.getData("Rol Grubu","Alt Bayi Admin","Equals");
    getData = (GridOperations.GetData)((ReportingDriver)driver).addons().execute(getData);

    // 50. Run Get Data From Grid
    //    Yetki Tipi
    GeneratedUtils.sleep(500);
    getData = GridOperations.getData("Yetki Tipi","AltBayi","Equals");
    getData = (GridOperations.GetData)((ReportingDriver)driver).addons().execute(getData);

    // 51. Run Get Data From Grid
    //    Ekleyen Kullanıcı Tipi
    GeneratedUtils.sleep(500);
    getData = GridOperations.getData("Ekleyen Kullanıcı Tipi","Default","Equals");
    getData = (GridOperations.GetData)((ReportingDriver)driver).addons().execute(getData);

    // 52. Get 'style' attribute value on 'Trash.png'
    //    Disabled olduğunun validate edilmesi
    GeneratedUtils.sleep(500);
    getElementAttribute = WebExtensions.getElementAttribute("style");
    by = By.xpath("//img[contains(@src,'trash.png')]");
    getElementAttribute = (WebExtensions.GetElementAttribute)((ReportingDriver)driver).addons().execute(getElementAttribute, by, -1);

    // 53. Get 'style' attribute value on 'edit.png'
    //    Disabled olduğunun validate edilmesi
    GeneratedUtils.sleep(500);
    getElementAttribute = WebExtensions.getElementAttribute("style");
    by = By.xpath("//img[contains(@src,'edit.png')]");
    getElementAttribute = (WebExtensions.GetElementAttribute)((ReportingDriver)driver).addons().execute(getElementAttribute, by, -1);

    // 54. Get 'style' attribute value on 'copy.png'
    //    enable olduğunun validate edilmesi
    GeneratedUtils.sleep(500);
    getElementAttribute = WebExtensions.getElementAttribute("style");
    by = By.xpath("//img[contains(@src,'copy.png')]");
    getElementAttribute = (WebExtensions.GetElementAttribute)((ReportingDriver)driver).addons().execute(getElementAttribute, by, -1);

    // 55. Select options in 'RoleGroupId' with text '[NONE]'
    GeneratedUtils.sleep(500);
    selectOptionbyVisibleText = WebExtensions.selectOptionbyVisibleText("Alt Bayi Muhasebe");
    by = By.cssSelector("#RoleGroupId");
    selectOptionbyVisibleText = (WebExtensions.SelectOptionbyVisibleText)((ReportingDriver)driver).addons().execute(selectOptionbyVisibleText, by, -1);

    // 56. Run Get Data From Grid
    //    Rol Grubu
    GeneratedUtils.sleep(500);
    getData = GridOperations.getData("Rol Grubu","Alt Bayi Muhasebe","Equals");
    getData = (GridOperations.GetData)((ReportingDriver)driver).addons().execute(getData);

    // 57. Run Get Data From Grid
    //    Yetki Tipi
    GeneratedUtils.sleep(500);
    getData = GridOperations.getData("Yetki Tipi","AltBayi","Equals");
    getData = (GridOperations.GetData)((ReportingDriver)driver).addons().execute(getData);

    // 58. Run Get Data From Grid
    //    Ekleyen Kullanıcı Tipi
    GeneratedUtils.sleep(500);
    getData = GridOperations.getData("Ekleyen Kullanıcı Tipi","Default","Equals");
    getData = (GridOperations.GetData)((ReportingDriver)driver).addons().execute(getData);

    // 59. Get 'style' attribute value on 'Trash.png'
    //    Disabled olduğunun validate edilmesi
    GeneratedUtils.sleep(500);
    getElementAttribute = WebExtensions.getElementAttribute("style");
    by = By.xpath("//img[contains(@src,'trash.png')]");
    getElementAttribute = (WebExtensions.GetElementAttribute)((ReportingDriver)driver).addons().execute(getElementAttribute, by, -1);

    // 60. Get 'style' attribute value on 'edit.png'
    //    Disabled olduğunun validate edilmesi
    GeneratedUtils.sleep(500);
    getElementAttribute = WebExtensions.getElementAttribute("style");
    by = By.xpath("//img[contains(@src,'edit.png')]");
    getElementAttribute = (WebExtensions.GetElementAttribute)((ReportingDriver)driver).addons().execute(getElementAttribute, by, -1);

    // 61. Get 'style' attribute value on 'copy.png'
    //    enable olduğunun validate edilmesi
    GeneratedUtils.sleep(500);
    getElementAttribute = WebExtensions.getElementAttribute("style");
    by = By.xpath("//img[contains(@src,'copy.png')]");
    getElementAttribute = (WebExtensions.GetElementAttribute)((ReportingDriver)driver).addons().execute(getElementAttribute, by, -1);

  }

  @Override
  public ReportingDriver getDriver() {
    return (ReportingDriver) driver;
  }

  @AfterAll
  static void tearDown() {
    if (driver != null) {
      driver.quit();
    }
  }

  private static Stream provideParameters() throws Exception {
    return Stream.of(Arguments.of("https://otomasyon3.netahsilatdemo.com/","otomasyon@test.com","Kd!cyhz4","",""));
  }
}
