package netahsilat;

import io.testproject.addon.CombinedActions;
import io.testproject.sdk.drivers.ReportingDriver;
import io.testproject.sdk.drivers.web.RemoteWebDriver;
import io.testproject.sdk.interfaces.junit5.ExceptionsReporter;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.Select;

import java.util.concurrent.TimeUnit;
import java.util.stream.Stream;

/**
 * This class was automatically generated by TestProject
 * Project: Quality Museum Project
 * Test: C5235 Alt bayi olarak giriş yapılıp kendi bilgileri güncelleniyor mu ?
 * Generated by: Ahmet Furkan SIMSEK (furkan.simsek@qualitymuseum.com)
 * Generated on Mon Oct 10 06:56:57 GMT 2022.
 */
@DisplayName("C5235 Alt bayi olarak giriş yapılıp kendi bilgileri güncelleniyor mu ?")
public class C5235 implements ExceptionsReporter {
  public static WebDriver driver;

  @BeforeAll
  static void setup() throws Exception {
    driver = new RemoteWebDriver("wThDxIHw4zNaCydjAhcfe81WrQPYlMBFI7FPwUwV8M41", new ChromeOptions(), "Ahmet Furkan SIMSEK");
  }

  /**
   * In order to upload the test to TestProject need to un-comment @ArgumentsSource and set in comment the @MethodSource
   * @org.junit.jupiter.params.provider.ArgumentsSource(io.testproject.sdk.interfaces.parameterization.TestProjectParameterizer.class) */
  @DisplayName("C5235 Alt bayi olarak giriş yapılıp kendi bilgileri güncelleniyor mu ?")
  @ParameterizedTest
  @MethodSource("provideParameters")
  void execute(String ApplicationURL, String password) throws Exception {
    // set timeout for driver actions (similar to step timeout)
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);
    By by;
    boolean booleanResult;
    MethodLogin methodlogin;
    MethodLogoutlogin methodlogoutlogin;
    CombinedActions.ClearAndTypeAction clearAndTypeAction;

    // 1. Run Method Logout&Login
    GeneratedUtils.sleep(500);
    methodlogoutlogin = new MethodLogoutlogin();
    methodlogoutlogin.ApplicationURL = ProjectParameters.Otomasyon2Logout;
    methodlogoutlogin.userName = "altbayiguncellenecek@test.com";
    methodlogoutlogin.password = ProjectParameters.genelPassword;
    methodlogoutlogin.execute(driver);

    // 2. Click 'YÖNETİCİ1'
    GeneratedUtils.sleep(500);
    by = By.xpath("//a[. = 'YÖNETİCİ']");
    driver.findElement(by).click();

    // 3. Move mouse to 'C5235 Alt Bayi Güncellendi'
    GeneratedUtils.sleep(500);
    by = By.xpath("//strong[. = 'C5235 Alt Bayi Güncellendi']");
    (new Actions(driver)).moveToElement(driver.findElement(by)).perform();

    // 4. Click 'C5235 Alt Bayi Güncellendi'
    GeneratedUtils.sleep(500);
    by = By.xpath("//strong[. = 'C5235 Alt Bayi Güncellendi']");
    driver.findElement(by).click();

    // 5. Move mouse to 'BAYİMİ GÜNCELLE'
    GeneratedUtils.sleep(500);
    by = By.xpath("//a[. = 'BAYİMİ GÜNCELLE']");
    (new Actions(driver)).moveToElement(driver.findElement(by)).perform();

    // 6. Click 'BAYİMİ GÜNCELLE'
    GeneratedUtils.sleep(500);
    by = By.xpath("//a[. = 'BAYİMİ GÜNCELLE']");
    driver.findElement(by).click();

    // 7. Run Clear 'Entity.Name' contents and type 'C5235 Alt Bayi Güncellendi'
    GeneratedUtils.sleep(500);
    clearAndTypeAction = CombinedActions.clearAndTypeAction("C5235 Alt Bayi Güncellendi");
    by = By.cssSelector("#Entity_Name");
    clearAndTypeAction = (CombinedActions.ClearAndTypeAction)((ReportingDriver)driver).addons().execute(clearAndTypeAction, by, -1);

    // 8. Run Clear 'Entity.TaxOffice' contents and type 'selçuk'
    GeneratedUtils.sleep(500);
    clearAndTypeAction = CombinedActions.clearAndTypeAction("selçuk");
    by = By.cssSelector("#Entity_TaxOffice");
    clearAndTypeAction = (CombinedActions.ClearAndTypeAction)((ReportingDriver)driver).addons().execute(clearAndTypeAction, by, -1);

    // 9. Run Clear 'Entity.TaxNumber' contents and type '3955124336'
    GeneratedUtils.sleep(500);
    clearAndTypeAction = CombinedActions.clearAndTypeAction("3955124336");
    by = By.cssSelector("#Entity_TaxNumber");
    clearAndTypeAction = (CombinedActions.ClearAndTypeAction)((ReportingDriver)driver).addons().execute(clearAndTypeAction, by, -1);

    // 10. Run Clear 'Entity.Email' contents and type 'altbayiguncellendi@test.com'
    GeneratedUtils.sleep(500);
    clearAndTypeAction = CombinedActions.clearAndTypeAction("altbayiguncellendi@test.com");
    by = By.cssSelector("#Entity_Email");
    clearAndTypeAction = (CombinedActions.ClearAndTypeAction)((ReportingDriver)driver).addons().execute(clearAndTypeAction, by, -1);

    // 11. Run Clear 'Entity.AddressModel.Address' contents and type 'meram/konya'
    GeneratedUtils.sleep(500);
    clearAndTypeAction = CombinedActions.clearAndTypeAction("meram/konya");
    by = By.cssSelector("#Entity_AddressModel_Address");
    clearAndTypeAction = (CombinedActions.ClearAndTypeAction)((ReportingDriver)driver).addons().execute(clearAndTypeAction, by, -1);

    // 12. Select the '42' option in 'Entity.AddressModel.CityId'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_AddressModel_CityId");
    (new Select(driver.findElement(by))).selectByValue("42");

    // 13. Select the '868' option in 'Entity.AddressModel.DistrictId'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_AddressModel_DistrictId");
    (new Select(driver.findElement(by))).selectByValue("868");

    // 14. Select the '2983' option in 'Entity.AddressModel.NeighborhoodId'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_AddressModel_NeighborhoodId");
    (new Select(driver.findElement(by))).selectByValue("2983");

    // 15. Run Clear 'Entity.AddressModel.PostCode' contents and type '42042'
    GeneratedUtils.sleep(500);
    clearAndTypeAction = CombinedActions.clearAndTypeAction("42042");
    by = By.cssSelector("#Entity_AddressModel_PostCode");
    clearAndTypeAction = (CombinedActions.ClearAndTypeAction)((ReportingDriver)driver).addons().execute(clearAndTypeAction, by, -1);

    // 16. Run Clear 'Entity.ContactModel.Phone1Number' contents and type '5000000001'
    GeneratedUtils.sleep(500);
    clearAndTypeAction = CombinedActions.clearAndTypeAction("5000000001");
    by = By.cssSelector("#Entity_ContactModel_Phone1Number");
    clearAndTypeAction = (CombinedActions.ClearAndTypeAction)((ReportingDriver)driver).addons().execute(clearAndTypeAction, by, -1);

    // 17. Run Clear 'Entity.ContactModel.Fax1Number' contents and type '5222222223'
    GeneratedUtils.sleep(500);
    clearAndTypeAction = CombinedActions.clearAndTypeAction("5222222223");
    by = By.cssSelector("#Entity_ContactModel_Fax1Number");
    clearAndTypeAction = (CombinedActions.ClearAndTypeAction)((ReportingDriver)driver).addons().execute(clearAndTypeAction, by, -1);

    // 18. Run Clear 'Entity.ContactModel.WebAddress' contents and type 'ibrahim2.netahsilatdemo.com'
    GeneratedUtils.sleep(500);
    clearAndTypeAction = CombinedActions.clearAndTypeAction("ibrahim2.netahsilatdemo.com");
    by = By.cssSelector("#Entity_ContactModel_WebAddress");
    clearAndTypeAction = (CombinedActions.ClearAndTypeAction)((ReportingDriver)driver).addons().execute(clearAndTypeAction, by, -1);

    // 19. Click 'Tamam'
    GeneratedUtils.sleep(500);
    by = By.xpath("//button[. = 'Tamam']");
    driver.findElement(by).click();

    // 20. Move mouse to 'C5235 Alt Bayi Güncellendi'
    GeneratedUtils.sleep(500);
    by = By.xpath("//strong[. = 'C5235 Alt Bayi Güncellendi']");
    (new Actions(driver)).moveToElement(driver.findElement(by)).perform();

    // 21. Click 'C5235 Alt Bayi Güncellendi'
    GeneratedUtils.sleep(500);
    by = By.xpath("//strong[. = 'C5235 Alt Bayi Güncellendi']");
    driver.findElement(by).click();

    // 22. Move mouse to 'BAYİMİ GÜNCELLE'
    GeneratedUtils.sleep(500);
    by = By.xpath("//a[. = 'BAYİMİ GÜNCELLE']");
    (new Actions(driver)).moveToElement(driver.findElement(by)).perform();

    // 23. Click 'BAYİMİ GÜNCELLE'
    GeneratedUtils.sleep(500);
    by = By.xpath("//a[. = 'BAYİMİ GÜNCELLE']");
    driver.findElement(by).click();

    // 24. Does 'Entity.Name' contain 'C5235 Alt Bayi Güncellendi'?
    by = By.cssSelector("#Entity_Name");
    Assertions.assertTrue(driver.findElement(by).getText().contains("C5235 Alt Bayi Güncellendi"));

    // 25. Does 'Entity.TaxOffice' contain 'selçuk'?
    by = By.cssSelector("#Entity_TaxOffice");
    Assertions.assertTrue(driver.findElement(by).getText().contains("selçuk"));

    // 26. Does 'Entity.Email' contain 'altbayiguncellendi@test.com'?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_Email");
    Assertions.assertTrue(driver.findElement(by).getText().contains("altbayiguncellendi@test.com"));

    // 27. Does 'Entity.TaxNumber' contain '3955124336'?
    by = By.cssSelector("#Entity_TaxNumber");
    Assertions.assertTrue(driver.findElement(by).getText().contains("3955124336"));

    // 28. Does 'Entity.AddressModel.Address' contain 'meram/konya'?
    by = By.cssSelector("#Entity_AddressModel_Address");
    Assertions.assertTrue(driver.findElement(by).getText().contains("meram/konya"));

    // 29. Does 'Entity.AddressModel.CityId' contain 'Konya'?
    by = By.cssSelector("#Entity_AddressModel_CityId");
    Assertions.assertTrue(driver.findElement(by).getText().contains("Konya"));

    // 30. Does 'Entity.AddressModel.NeighborhoodId' contain 'Meram'?
    by = By.cssSelector("#Entity_AddressModel_NeighborhoodId");
    Assertions.assertTrue(driver.findElement(by).getText().contains("Meram"));

    // 31. Does 'Entity.ContactModel.Phone1Number' contain '(500)0000001'?
    by = By.cssSelector("#Entity_ContactModel_Phone1Number");
    Assertions.assertTrue(driver.findElement(by).getText().contains("(500)0000001"));

    // 32. Does 'Entity.AddressModel.DistrictId' contain 'Meram'?
    by = By.cssSelector("#Entity_AddressModel_DistrictId");
    Assertions.assertTrue(driver.findElement(by).getText().contains("Meram"));

    // 33. Does 'Entity.AddressModel.PostCode' contain '42042'?
    by = By.cssSelector("#Entity_AddressModel_PostCode");
    Assertions.assertTrue(driver.findElement(by).getText().contains("42042"));

    // 34. Does 'Entity.ContactModel.Fax1Number' contain '(522)2222223'?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_ContactModel_Fax1Number");
    Assertions.assertTrue(driver.findElement(by).getText().contains("(522)2222223"));

    // 35. Does 'Entity.ContactModel.WebAddress' contain 'ibrahim2.netahsilatdemo.com'?
    by = By.cssSelector("#Entity_ContactModel_WebAddress");
    Assertions.assertTrue(driver.findElement(by).getText().contains("ibrahim2.netahsilatdemo.com"));

    // 36. Run Clear 'Entity.Name' contents and type 'C5235 Alt Bayi Güncellenecek'
    GeneratedUtils.sleep(500);
    clearAndTypeAction = CombinedActions.clearAndTypeAction("C5235 Alt Bayi Güncellenecek");
    by = By.cssSelector("#Entity_Name");
    clearAndTypeAction = (CombinedActions.ClearAndTypeAction)((ReportingDriver)driver).addons().execute(clearAndTypeAction, by, -1);

    // 37. Run Clear 'Entity.TaxOffice' contents and type 'kartal'
    GeneratedUtils.sleep(500);
    clearAndTypeAction = CombinedActions.clearAndTypeAction("kartal");
    by = By.cssSelector("#Entity_TaxOffice");
    clearAndTypeAction = (CombinedActions.ClearAndTypeAction)((ReportingDriver)driver).addons().execute(clearAndTypeAction, by, -1);

    // 38. Run Clear 'Entity.TaxNumber' contents and type '6860808842'
    GeneratedUtils.sleep(500);
    clearAndTypeAction = CombinedActions.clearAndTypeAction("6860808842");
    by = By.cssSelector("#Entity_TaxNumber");
    clearAndTypeAction = (CombinedActions.ClearAndTypeAction)((ReportingDriver)driver).addons().execute(clearAndTypeAction, by, -1);

    // 39. Run Clear 'Entity.Email' contents and type 'altbayiguncellenecek@test.com'
    GeneratedUtils.sleep(500);
    clearAndTypeAction = CombinedActions.clearAndTypeAction("altbayiguncellenecek@test.com");
    by = By.cssSelector("#Entity_Email");
    clearAndTypeAction = (CombinedActions.ClearAndTypeAction)((ReportingDriver)driver).addons().execute(clearAndTypeAction, by, -1);

    // 40. Run Clear 'Entity.AddressModel.Address' contents and type 'kartal/istanbul'
    GeneratedUtils.sleep(500);
    clearAndTypeAction = CombinedActions.clearAndTypeAction("kartal/istanbul");
    by = By.cssSelector("#Entity_AddressModel_Address");
    clearAndTypeAction = (CombinedActions.ClearAndTypeAction)((ReportingDriver)driver).addons().execute(clearAndTypeAction, by, -1);

    // 41. Select the '34' option in 'Entity.AddressModel.CityId'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_AddressModel_CityId");
    (new Select(driver.findElement(by))).selectByValue("34");

    // 42. Select the '118' option in 'Entity.AddressModel.DistrictId'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_AddressModel_DistrictId");
    (new Select(driver.findElement(by))).selectByValue("118");

    // 43. Select the '2130' option in 'Entity.AddressModel.NeighborhoodId'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_AddressModel_NeighborhoodId");
    (new Select(driver.findElement(by))).selectByValue("2130");

    // 44. Run Clear 'Entity.AddressModel.PostCode' contents and type '34034'
    GeneratedUtils.sleep(500);
    clearAndTypeAction = CombinedActions.clearAndTypeAction("34034");
    by = By.cssSelector("#Entity_AddressModel_PostCode");
    clearAndTypeAction = (CombinedActions.ClearAndTypeAction)((ReportingDriver)driver).addons().execute(clearAndTypeAction, by, -1);

    // 45. Run Clear 'Entity.ContactModel.Phone1Number' contents and type '5000000000'
    GeneratedUtils.sleep(500);
    clearAndTypeAction = CombinedActions.clearAndTypeAction("5000000000");
    by = By.cssSelector("#Entity_ContactModel_Phone1Number");
    clearAndTypeAction = (CombinedActions.ClearAndTypeAction)((ReportingDriver)driver).addons().execute(clearAndTypeAction, by, -1);

    // 46. Run Clear 'Entity.ContactModel.Fax1Number' contents and type '5222222222'
    GeneratedUtils.sleep(500);
    clearAndTypeAction = CombinedActions.clearAndTypeAction("5222222222");
    by = By.cssSelector("#Entity_ContactModel_Fax1Number");
    clearAndTypeAction = (CombinedActions.ClearAndTypeAction)((ReportingDriver)driver).addons().execute(clearAndTypeAction, by, -1);

    // 47. Run Clear 'Entity.ContactModel.WebAddress' contents and type 'ibrahim.netahsilatdemo.com'
    GeneratedUtils.sleep(500);
    clearAndTypeAction = CombinedActions.clearAndTypeAction("ibrahim.netahsilatdemo.com");
    by = By.cssSelector("#Entity_ContactModel_WebAddress");
    clearAndTypeAction = (CombinedActions.ClearAndTypeAction)((ReportingDriver)driver).addons().execute(clearAndTypeAction, by, -1);

    // 48. Click 'Tamam'
    GeneratedUtils.sleep(500);
    by = By.xpath("//button[. = 'Tamam']");
    driver.findElement(by).click();

    // 49. Move mouse to 'C5235 Alt Bayi Güncellendi'
    GeneratedUtils.sleep(500);
    by = By.xpath("//strong[. = 'C5235 Alt Bayi Güncellendi']");
    (new Actions(driver)).moveToElement(driver.findElement(by)).perform();

    // 50. Click 'C5235 Alt Bayi Güncellendi'
    GeneratedUtils.sleep(500);
    by = By.xpath("//strong[. = 'C5235 Alt Bayi Güncellendi']");
    driver.findElement(by).click();

    // 51. Move mouse to 'HESABIMI GÜNCELLE'
    GeneratedUtils.sleep(500);
    by = By.xpath("//a[. = 'HESABIMI GÜNCELLE']");
    (new Actions(driver)).moveToElement(driver.findElement(by)).perform();

    // 52. Click 'HESABIMI GÜNCELLE'
    GeneratedUtils.sleep(500);
    by = By.xpath("//a[. = 'HESABIMI GÜNCELLE']");
    driver.findElement(by).click();

    // 53. Run Clear 'Entity.Name' contents and type 'C5235 Ana Bayi1'
    GeneratedUtils.sleep(500);
    clearAndTypeAction = CombinedActions.clearAndTypeAction("C5235 Ana Bayi1");
    by = By.cssSelector("#Entity_Name");
    clearAndTypeAction = (CombinedActions.ClearAndTypeAction)((ReportingDriver)driver).addons().execute(clearAndTypeAction, by, -1);

    // 54. Run Clear 'Entity.Surname' contents and type 'Güncellendi'
    GeneratedUtils.sleep(500);
    clearAndTypeAction = CombinedActions.clearAndTypeAction("Güncellendi");
    by = By.cssSelector("#Entity_Surname");
    clearAndTypeAction = (CombinedActions.ClearAndTypeAction)((ReportingDriver)driver).addons().execute(clearAndTypeAction, by, -1);

    // 55. Run Clear 'Entity.Email' contents and type 'altbayiguncellendi@test.com'
    GeneratedUtils.sleep(500);
    clearAndTypeAction = CombinedActions.clearAndTypeAction("altbayiguncellendi@test.com");
    by = By.cssSelector("#Entity_Email");
    clearAndTypeAction = (CombinedActions.ClearAndTypeAction)((ReportingDriver)driver).addons().execute(clearAndTypeAction, by, -1);

    // 56. Run Clear 'Entity.MobilePhone' contents and type '5111111112'
    GeneratedUtils.sleep(500);
    clearAndTypeAction = CombinedActions.clearAndTypeAction("5111111112");
    by = By.cssSelector("#Entity_MobilePhone");
    clearAndTypeAction = (CombinedActions.ClearAndTypeAction)((ReportingDriver)driver).addons().execute(clearAndTypeAction, by, -1);

    // 57. Run Clear 'Entity.Tckn' contents and type '31675522146'
    GeneratedUtils.sleep(500);
    clearAndTypeAction = CombinedActions.clearAndTypeAction("31675522146");
    by = By.cssSelector("#Entity_Tckn");
    clearAndTypeAction = (CombinedActions.ClearAndTypeAction)((ReportingDriver)driver).addons().execute(clearAndTypeAction, by, -1);

    // 58. Type 'Kd!cyhz4' in 'Entity.OldPassword'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_OldPassword");
    driver.findElement(by).sendKeys("Kd!cyhz4");

    // 59. Type 'Kd!cyhz41' in 'Entity.Password'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_Password");
    driver.findElement(by).sendKeys("Kd!cyhz41");

    // 60. Type 'Kd!cyhz41' in 'Entity.PasswordAgain'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_PasswordAgain");
    driver.findElement(by).sendKeys("Kd!cyhz41");

    // 61. Click 'Tamam'
    GeneratedUtils.sleep(500);
    by = By.xpath("//button[. = 'Tamam']");
    driver.findElement(by).click();

    // 62. Run Method Login
    GeneratedUtils.sleep(500);
    methodlogin = new MethodLogin();
    methodlogin.ApplicationURL = ApplicationURL;
    methodlogin.userName = "altbayiguncellendi@test.com";
    methodlogin.password = "Kd!cyhz41";
    methodlogin.execute(driver);

    // 63. Click 'YÖNETİCİ1'
    GeneratedUtils.sleep(500);
    by = By.xpath("//a[. = 'YÖNETİCİ']");
    driver.findElement(by).click();

    // 64. Move mouse to 'C5235 Ana Bayi1 Güncellendi'
    GeneratedUtils.sleep(500);
    by = By.xpath("//strong[. = 'C5235 Ana Bayi1 Güncellendi']");
    (new Actions(driver)).moveToElement(driver.findElement(by)).perform();

    // 65. Click 'C5235 Ana Bayi1 Güncellendi'
    GeneratedUtils.sleep(500);
    by = By.xpath("//strong[. = 'C5235 Ana Bayi1 Güncellendi']");
    driver.findElement(by).click();

    // 66. Move mouse to 'HESABIMI GÜNCELLE'
    GeneratedUtils.sleep(500);
    by = By.xpath("//a[. = 'HESABIMI GÜNCELLE']");
    (new Actions(driver)).moveToElement(driver.findElement(by)).perform();

    // 67. Click 'HESABIMI GÜNCELLE'
    GeneratedUtils.sleep(500);
    by = By.xpath("//a[. = 'HESABIMI GÜNCELLE']");
    driver.findElement(by).click();

    // 68. Does 'Entity.Name' contain 'C5235 Ana Bayi1'?
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(35000, TimeUnit.MILLISECONDS);
    by = By.cssSelector("#Entity_Name");
    Assertions.assertTrue(driver.findElement(by).getText().contains("C5235 Ana Bayi1"));
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 69. Does 'Entity.Surname' contain 'Güncellendi'?
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(35000, TimeUnit.MILLISECONDS);
    by = By.cssSelector("#Entity_Surname");
    Assertions.assertTrue(driver.findElement(by).getText().contains("Güncellendi"));
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 70. Does 'Entity.Email' contain 'altbayiguncellendi@test.com'?
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(35000, TimeUnit.MILLISECONDS);
    by = By.cssSelector("#Entity_Email");
    Assertions.assertTrue(driver.findElement(by).getText().contains("altbayiguncellendi@test.com"));
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 71. Does 'Entity.MobilePhone' contain '(511)1111112'?
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(35000, TimeUnit.MILLISECONDS);
    by = By.cssSelector("#Entity_MobilePhone");
    Assertions.assertTrue(driver.findElement(by).getText().contains("(511)1111112"));
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 72. Does 'Entity.SelectedCountry' contain 'Turkey'?
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(35000, TimeUnit.MILLISECONDS);
    by = By.cssSelector("#Entity_SelectedCountry");
    Assertions.assertTrue(driver.findElement(by).getText().contains("Turkey"));
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 73. Does 'Entity.Tckn' contain '31675522146'?
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(35000, TimeUnit.MILLISECONDS);
    by = By.cssSelector("#Entity_Tckn");
    Assertions.assertTrue(driver.findElement(by).getText().contains("31675522146"));
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 74. Run Clear 'Entity.Name' contents and type 'C5235 Alt Bayi'
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(35000, TimeUnit.MILLISECONDS);
    clearAndTypeAction = CombinedActions.clearAndTypeAction("C5235 Alt Bayi");
    by = By.cssSelector("#Entity_Name");
    clearAndTypeAction = (CombinedActions.ClearAndTypeAction)((ReportingDriver)driver).addons().execute(clearAndTypeAction, by, -1);
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 75. Run Clear 'Entity.Surname' contents and type 'Güncellendi'
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(35000, TimeUnit.MILLISECONDS);
    clearAndTypeAction = CombinedActions.clearAndTypeAction("Güncellendi");
    by = By.cssSelector("#Entity_Surname");
    clearAndTypeAction = (CombinedActions.ClearAndTypeAction)((ReportingDriver)driver).addons().execute(clearAndTypeAction, by, -1);
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 76. Run Clear 'Entity.Email' contents and type 'altbayiguncellenecek@test.com'
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(35000, TimeUnit.MILLISECONDS);
    clearAndTypeAction = CombinedActions.clearAndTypeAction("altbayiguncellenecek@test.com");
    by = By.cssSelector("#Entity_Email");
    clearAndTypeAction = (CombinedActions.ClearAndTypeAction)((ReportingDriver)driver).addons().execute(clearAndTypeAction, by, -1);
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 77. Run Clear 'Entity.MobilePhone' contents and type '5111111111'
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(35000, TimeUnit.MILLISECONDS);
    clearAndTypeAction = CombinedActions.clearAndTypeAction("5111111111");
    by = By.cssSelector("#Entity_MobilePhone");
    clearAndTypeAction = (CombinedActions.ClearAndTypeAction)((ReportingDriver)driver).addons().execute(clearAndTypeAction, by, -1);
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 78. Run Clear 'Entity.Tckn' contents and type '50254439002'
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(35000, TimeUnit.MILLISECONDS);
    clearAndTypeAction = CombinedActions.clearAndTypeAction("50254439002");
    by = By.cssSelector("#Entity_Tckn");
    clearAndTypeAction = (CombinedActions.ClearAndTypeAction)((ReportingDriver)driver).addons().execute(clearAndTypeAction, by, -1);
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 79. Type 'Kd!cyhz41' in 'Entity.OldPassword'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_OldPassword");
    driver.findElement(by).sendKeys("Kd!cyhz41");

    // 80. Type 'Kd!cyhz4' in 'Entity.Password'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_Password");
    driver.findElement(by).sendKeys("Kd!cyhz4");

    // 81. Type 'Kd!cyhz4' in 'Entity.PasswordAgain'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_PasswordAgain");
    driver.findElement(by).sendKeys("Kd!cyhz4");

    // 82. Click 'Tamam'
    GeneratedUtils.sleep(500);
    by = By.xpath("//button[. = 'Tamam']");
    driver.findElement(by).click();

  }

  @Override
  public ReportingDriver getDriver() {
    return (ReportingDriver) driver;
  }

  @AfterAll
  static void tearDown() {
    if (driver != null) {
      driver.quit();
    }
  }

  private static Stream provideParameters() throws Exception {
    return Stream.of(Arguments.of("https://otomasyon2.netahsilatdemo.com/","Kd!cyhz4"));
  }
}
