package netahsilat;

import io.testproject.addon.GridOperations;
import io.testproject.addon.ImapMailOperations;
import io.testproject.addon.NetahsilatUtills;
import io.testproject.addon.WebExtensions;
import io.testproject.sdk.drivers.ReportingDriver;
import io.testproject.sdk.drivers.web.RemoteWebDriver;
import io.testproject.sdk.interfaces.junit5.ExceptionsReporter;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;

import java.util.concurrent.TimeUnit;
import java.util.stream.Stream;

/**
 * This class was automatically generated by TestProject
 * Project: Quality Museum Project
 * Test: C554 İşlem Detayları
 * Generated by: Ahmet Furkan SIMSEK (furkan.simsek@qualitymuseum.com)
 * Generated on Tue Oct 04 11:00:44 GMT 2022.
 */
@DisplayName("C554 İşlem Detayları")
public class C554 implements ExceptionsReporter {
  public static WebDriver driver;

  @BeforeAll
  static void setup() throws Exception {
    driver = new RemoteWebDriver("wThDxIHw4zNaCydjAhcfe81WrQPYlMBFI7FPwUwV8M41", new ChromeOptions(), "Ahmet Furkan SIMSEK");
  }

  /**
   * In order to upload the test to TestProject need to un-comment @ArgumentsSource and set in comment the @MethodSource
   * @org.junit.jupiter.params.provider.ArgumentsSource(io.testproject.sdk.interfaces.parameterization.TestProjectParameterizer.class) */
  @DisplayName("C554 İşlem Detayları")
  @ParameterizedTest
  @MethodSource("provideParameters")
  void execute(String ApplicationURL, String userName, String password, String gridHeaders) throws
      Exception {
    // set timeout for driver actions (similar to step timeout)
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);
    By by;
    boolean booleanResult;
    MethodLogoutlogin methodlogoutlogin;
    ImapMailOperations.ReadSpecificsMail readSpecificsMail;
    NetahsilatUtills.ClickUntilGone clickUntilGone;
    WebExtensions.ExecuteJavascript executeJavascript;
    GridOperations.conditionalClick conditionalClick;

    // 1. Run Method Logout&Login
    GeneratedUtils.sleep(500);
    methodlogoutlogin = new MethodLogoutlogin();
    methodlogoutlogin.ApplicationURL = ApplicationURL;
    methodlogoutlogin.userName = ProjectParameters.genelEmail;
    methodlogoutlogin.password = ProjectParameters.genelPassword;
    methodlogoutlogin.execute(driver);

    // 2. Move mouse to 'moveToIslemler'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("li[class='tag']");
    (new Actions(driver)).moveToElement(driver.findElement(by)).perform();

    // 3. Click 'İŞLEMLER1'
    GeneratedUtils.sleep(500);
    by = By.xpath("//a[. = 'İŞLEMLER']");
    driver.findElement(by).click();

    // 4. Click 'ÖDEME LİNKİ LİSTESİ'
    GeneratedUtils.sleep(500);
    by = By.xpath("//a[. = 'ÖDEME LİNKİ LİSTESİ']");
    driver.findElement(by).click();

    // 5. Type 'NT56154P0000033047' in 'ReferenceNumber'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#ReferenceNumber");
    driver.findElement(by).sendKeys("NT56154P0000033047");

    // 6. Click 'btnListele'
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(35000, TimeUnit.MILLISECONDS);
    GeneratedUtils.sleep(500);
    by = By.xpath("//button[. = 'Listele']");
    driver.findElement(by).click();
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 7. Is 'Refresh' visible?
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(35000, TimeUnit.MILLISECONDS);
    GeneratedUtils.sleep(500);
    by = By.cssSelector("a[class='t-icon t-refresh']");
    driver.findElement(by).isDisplayed();
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 8. Run Conditional Click
    GeneratedUtils.sleep(500);
    conditionalClick = GridOperations.conditionalClick("img[src*='mail-open-document-text.png']",false);
    by = By.xpath("//span[. = 'next']");
    conditionalClick = (GridOperations.conditionalClick)((ReportingDriver)driver).addons().execute(conditionalClick, by, -1);

    // 9. Click 'imgIslemDetaylariOdemeLinki'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("img[src*='mail-open-document-text.png']");
    driver.findElement(by).click();

    // 10. Does 'referansIslemDetayiOdemeLinki' contain 'NT56154P0000033047'?
    GeneratedUtils.sleep(500);
    by = By.xpath(" //div[normalize-space()='Referans']//following-sibling::div[starts-with(@class,'colx2-right')]");
    Assertions.assertTrue(driver.findElement(by).getText().contains("NT56154P0000033047"));

    // 11. Click 'Yazdır'
    GeneratedUtils.sleep(500);
    by = By.xpath("//a[. = 'Yazdır']");
    driver.findElement(by).click();

    // 12. Pause for '3000'ms
    GeneratedUtils.sleep(500);
    driver.manage().timeouts().implicitlyWait(3000, TimeUnit.MILLISECONDS);

    // 13. Switch to window '1'
    GeneratedUtils.sleep(500);
    driver.switchTo().window(driver.getWindowHandles().toArray(new String[0])[1]);

    // 14. Execute JavaScript 'document.querySelector('print-preview-app').shadowRoot.querySelector('print-preview-sidebar').shadowRoot.querySelector('print-preview-button-strip').shadowRoot.querySelector('.cancel-button').click()' with arguments '[NONE]'
    GeneratedUtils.sleep(500);
    executeJavascript = WebExtensions.executeJavascript("document.querySelector('print-preview-app').shadowRoot.querySelector('print-preview-sidebar').shadowRoot.querySelector('print-preview-button-strip').shadowRoot.querySelector('.cancel-button').click()","");
    executeJavascript = (WebExtensions.ExecuteJavascript)((ReportingDriver)driver).addons().execute(executeJavascript);

    // 15. Switch to window '1'
    GeneratedUtils.sleep(500);
    driver.switchTo().window(driver.getWindowHandles().toArray(new String[0])[1]);

    // 16. Is 'tutarOnFormFromOdemeLınkı' visible?
    GeneratedUtils.sleep(500);
    by = By.xpath("//label[normalize-space()='Tutar:']//following-sibling::label");
    driver.findElement(by).isDisplayed();

    // 17. Close window with index '1'
    GeneratedUtils.sleep(500);
    driver.close();

    // 18. Switch to window '0'
    GeneratedUtils.sleep(500);
    driver.switchTo().window(driver.getWindowHandles().toArray(new String[0])[0]);

    // 19. Move mouse to 'ddTalimatForumu'
    GeneratedUtils.sleep(500);
    by = By.xpath("//form/div/div[2]/div/div[2]");
    (new Actions(driver)).moveToElement(driver.findElement(by)).perform();

    // 20. Click 'Görüntüle'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#print");
    driver.findElement(by).click();

    // 21. Does 'Provizyon Tutarı > following-sibling::td' contain ': 87 ₺ .'?
    GeneratedUtils.sleep(500);
    by = By.xpath("//td[normalize-space()='Provizyon Tutarı']//following-sibling::td");
    Assertions.assertTrue(driver.findElement(by).getText().contains(": 87 ₺ ."));

    // 22. Click 'svgKapatForm'
    GeneratedUtils.sleep(500);
    by = By.xpath("//div[1]//*[name()='svg']");
    driver.findElement(by).click();

    // 23. Move mouse to 'ddTalimatForumu'
    GeneratedUtils.sleep(500);
    by = By.xpath("//form/div/div[2]/div/div[2]");
    (new Actions(driver)).moveToElement(driver.findElement(by)).perform();

    // 24. Click 'Mail Gönder'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#sendMail");
    driver.findElement(by).click();

    // 25. Type 'netahsilatotomasyon@yandex.com' in '//h1[contains(text(),'Lütfen E-Mail Giriniz')]/..//input[@id='email']'
    GeneratedUtils.sleep(500);
    by = By.xpath("//h1[contains(text(),'Lütfen E-Mail Giriniz')]/..//input[@id='email']");
    driver.findElement(by).sendKeys("netahsilatotomasyon@yandex.com");

    // 26. Run Click Until Gone
    GeneratedUtils.sleep(500);
    clickUntilGone = NetahsilatUtills.clickUntilGone(30);
    by = By.xpath("//button[. = 'Gönder']");
    clickUntilGone = (NetahsilatUtills.ClickUntilGone)((ReportingDriver)driver).addons().execute(clickUntilGone, by, -1);

    // 27. Is 'netahsilatotomasyon@yandex.com adresi...' visible?
    GeneratedUtils.sleep(500);
    by = By.xpath("//div[contains(text(), 'netahsilatotomasyon@yandex.com adresine ödeme talimat formu başarıyla gönderildi')]");
    driver.findElement(by).isDisplayed();

    // 28. Output searched string in specific mail
    /* Step is disabled
    GeneratedUtils.sleep(500);
    readSpecificsMail = ImapMailOperations.readSpecificsMail(ProjectParameters.odemeEmail,ProjectParameters.yandexMailKey,"NT56154P0000032987","C:/TestProject/mail/C554.html");
    readSpecificsMail = (ImapMailOperations.ReadSpecificsMail)((ReportingDriver)driver).addons().execute(readSpecificsMail);
    */
  }

  @Override
  public ReportingDriver getDriver() {
    return (ReportingDriver) driver;
  }

  @AfterAll
  static void tearDown() {
    if (driver != null) {
      driver.quit();
    }
  }

  private static Stream provideParameters() throws Exception {
    return Stream.of(Arguments.of("https://otomasyon.netahsilatdemo.com/Account/LogOff","otomasyon@test.com","Kd!cyhz4",""));
  }
}
