package netahsilat;

import io.testproject.addon.NetahsilatUtills;
import io.testproject.addon.RandomDataGenerator;
import io.testproject.addon.WebExtensions;
import io.testproject.sdk.drivers.ReportingDriver;
import io.testproject.sdk.drivers.web.RemoteWebDriver;
import io.testproject.sdk.interfaces.junit5.ExceptionsReporter;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;

import java.util.concurrent.TimeUnit;
import java.util.stream.Stream;

/**
 * This class was automatically generated by TestProject
 * Project: Quality Museum Project
 * Test: C634 Cari Hesaplar Sekmesi
 * Generated by: Ahmet Furkan SIMSEK (furkan.simsek@qualitymuseum.com)
 * Generated on Thu Oct 06 07:14:41 GMT 2022.
 */
@DisplayName("C634 Cari Hesaplar Sekmesi")
public class C634 implements ExceptionsReporter {
  public static WebDriver driver;

  @BeforeAll
  static void setup() throws Exception {
    driver = new RemoteWebDriver("wThDxIHw4zNaCydjAhcfe81WrQPYlMBFI7FPwUwV8M41", new ChromeOptions(), "Ahmet Furkan SIMSEK");
  }

  /**
   * In order to upload the test to TestProject need to un-comment @ArgumentsSource and set in comment the @MethodSource
   * @org.junit.jupiter.params.provider.ArgumentsSource(io.testproject.sdk.interfaces.parameterization.TestProjectParameterizer.class) */
  @DisplayName("C634 Cari Hesaplar Sekmesi")
  @ParameterizedTest
  @MethodSource("provideParameters")
  void execute(String ApplicationURL, String userName, String password, String randomERP) throws
      Exception {
    // set timeout for driver actions (similar to step timeout)
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);
    By by;
    boolean booleanResult;
    MethodLogoutlogin methodlogoutlogin;
    NetahsilatUtills.ClickUntilGone clickUntilGone;
    RandomDataGenerator.GenerateNumberInRange generateNumberInRange;
    WebExtensions.AcceptAlert acceptAlert;

    // 1. Run Method Logout&Login
    GeneratedUtils.sleep(500);
    methodlogoutlogin = new MethodLogoutlogin();
    methodlogoutlogin.ApplicationURL = ApplicationURL;
    methodlogoutlogin.userName = ProjectParameters.genelEmail;
    methodlogoutlogin.password = ProjectParameters.genelPassword;
    methodlogoutlogin.execute(driver);

    // 2. Move mouse to 'moveUstUyeYonetimi'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("li[class='content']");
    (new Actions(driver)).moveToElement(driver.findElement(by)).perform();

    // 3. Click 'ustUyeYonetimi'
    GeneratedUtils.sleep(500);
    by = By.xpath("//li[4]/a[. = 'ÜYE YÖNETİMİ']");
    driver.findElement(by).click();

    // 4. Click 'altUyeYonetimi'
    GeneratedUtils.sleep(500);
    by = By.xpath("//li[1]/a[. = 'ÜYE YÖNETİMİ']");
    driver.findElement(by).click();

    // 5. Click 'SearchVendorNameVN'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#SearchVendorName");
    driver.findElement(by).click();

    // 6. Is 'Refresh' visible?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("a[class='t-icon t-refresh']");
    driver.findElement(by).isDisplayed();

    // 7. Type '181212' in 'SearchVendorNameVN'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#SearchVendorName");
    driver.findElement(by).sendKeys("181212");

    // 8. Click 'resultListelenen'
    GeneratedUtils.sleep(500);
    by = By.xpath("//body/ul//div");
    driver.findElement(by).click();

    // 9. Click 'btnListele'
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(35000, TimeUnit.MILLISECONDS);
    GeneratedUtils.sleep(500);
    by = By.xpath("//button[. = 'Listele']");
    driver.findElement(by).click();
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 10. Is 'Refresh' visible?
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(35000, TimeUnit.MILLISECONDS);
    GeneratedUtils.sleep(500);
    by = By.cssSelector("a[class='t-icon t-refresh']");
    driver.findElement(by).isDisplayed();
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 11. Is 'test bayi' visible?
    GeneratedUtils.sleep(500);
    by = By.xpath("//td[contains(text(),'test bayi')] ");
    driver.findElement(by).isDisplayed();

    // 12. Click 'EditButton'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("img[src*='fugue/edit.png']");
    driver.findElement(by).click();

    // 13. Click 'CariHesaplarImage'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("img[src*='Paper-Money-icon.png']");
    driver.findElement(by).click();

    // 14. Click 'Yeni Hesap Ekle'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#btnInsertCurrentAccount");
    driver.findElement(by).click();

    // 15. Click 'ClickImage'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("img[src*='fugue/tick.png']");
    driver.findElement(by).click();

    // 16. Accept alert
    GeneratedUtils.sleep(500);
    acceptAlert = WebExtensions.acceptAlert(1000);
    acceptAlert = (WebExtensions.AcceptAlert)((ReportingDriver)driver).addons().execute(acceptAlert);

    // 17. Type 'test' in 'Entity.CurrentAccounts[1].Name'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_CurrentAccounts_1__Name");
    driver.findElement(by).sendKeys("test");

    // 18. Click 'ClickImage'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("img[src*='fugue/tick.png']");
    driver.findElement(by).click();

    // 19. Accept alert
    GeneratedUtils.sleep(500);
    acceptAlert = WebExtensions.acceptAlert(1000);
    acceptAlert = (WebExtensions.AcceptAlert)((ReportingDriver)driver).addons().execute(acceptAlert);

    // 20. Clear 'Entity.CurrentAccounts[1].Name' contents
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_CurrentAccounts_1__Name");
    driver.findElement(by).clear();

    // 21. Type 'test' in 'Entity.CurrentAccounts[1].Name'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_CurrentAccounts_1__Name");
    driver.findElement(by).sendKeys("test");

    // 22. Click 'Seçiniz'
    GeneratedUtils.sleep(500);
    by = By.xpath("//td[9]/button[. = 'Seçiniz']");
    driver.findElement(by).click();

    // 23. Click 'multiselect_Entity_CurrentAccounts_1_...'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#ui-multiselect-Entity_CurrentAccounts_1__CurrencyCodes-option-1");
    driver.findElement(by).click();

    // 24. Click 'ClickImage'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("img[src*='fugue/tick.png']");
    driver.findElement(by).click();

    // 25. Accept alert
    GeneratedUtils.sleep(500);
    acceptAlert = WebExtensions.acceptAlert(1000);
    acceptAlert = (WebExtensions.AcceptAlert)((ReportingDriver)driver).addons().execute(acceptAlert);

    // 26. Clear 'Entity.CurrentAccounts[1].Name' contents
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_CurrentAccounts_1__Name");
    driver.findElement(by).clear();

    // 27. Type 'test' in 'Entity.CurrentAccounts[1].Name'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_CurrentAccounts_1__Name");
    driver.findElement(by).sendKeys("test");

    // 28. Click 'Seçiniz'
    GeneratedUtils.sleep(500);
    by = By.xpath("//td[9]/button[. = 'Seçiniz']");
    driver.findElement(by).click();

    // 29. Click 'multiselect_Entity_CurrentAccounts_1_...1'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#ui-multiselect-Entity_CurrentAccounts_1__CurrencyCodes-option-2");
    driver.findElement(by).click();

    // 30. Click 'ClickImage'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("img[src*='fugue/tick.png']");
    driver.findElement(by).click();

    // 31. Accept alert
    GeneratedUtils.sleep(500);
    acceptAlert = WebExtensions.acceptAlert(1000);
    acceptAlert = (WebExtensions.AcceptAlert)((ReportingDriver)driver).addons().execute(acceptAlert);

    // 32. Generate random number between '111111' and '999999'
    GeneratedUtils.sleep(500);
    generateNumberInRange = RandomDataGenerator.generateNumberInRange("111111","999999");
    generateNumberInRange = (RandomDataGenerator.GenerateNumberInRange)((ReportingDriver)driver).addons().execute(generateNumberInRange);
    randomERP = String.valueOf(generateNumberInRange.result);

    // 33. Type '{{randomERP}}' in 'Entity.CurrentAccounts[1].ErpCode'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_CurrentAccounts_1__ErpCode");
    driver.findElement(by).sendKeys(randomERP);

    // 34. Type 'acıklama' in 'Entity.CurrentAccounts[1].Description'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_CurrentAccounts_1__Description");
    driver.findElement(by).sendKeys("acıklama");

    // 35. Click 'ClickImage'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("img[src*='fugue/tick.png']");
    driver.findElement(by).click();

    // 36. Run Click Until Gone
    GeneratedUtils.sleep(500);
    clickUntilGone = NetahsilatUtills.clickUntilGone(30);
    by = By.xpath("//button[. = 'Tamam']");
    clickUntilGone = (NetahsilatUtills.ClickUntilGone)((ReportingDriver)driver).addons().execute(clickUntilGone, by, -1);

    // 37. Is 'Refresh' visible?
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(60000, TimeUnit.MILLISECONDS);
    GeneratedUtils.sleep(500);
    by = By.cssSelector("a[class='t-icon t-refresh']");
    driver.findElement(by).isDisplayed();
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 38. Click 'EditButton'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("img[src*='fugue/edit.png']");
    driver.findElement(by).click();

    // 39. Click 'CariHesaplarImage'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("img[src*='Paper-Money-icon.png']");
    driver.findElement(by).click();

    // 40. Does 'Entity.CurrentAccounts[1].ErpCode' contain '{{randomERP}}'?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_CurrentAccounts_1__ErpCode");
    Assertions.assertTrue(driver.findElement(by).getText().contains(randomERP));

    // 41. Does 'Entity.CurrentAccounts[1].Name' contain 'test'?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_CurrentAccounts_1__Name");
    Assertions.assertTrue(driver.findElement(by).getText().contains("test"));

    // 42. Does 'Entity.CurrentAccounts[1].Description' contain 'acıklama'?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_CurrentAccounts_1__Description");
    Assertions.assertTrue(driver.findElement(by).getText().contains("acıklama"));

    // 43. Click 'SilImage'
    GeneratedUtils.sleep(500);
    by = By.xpath("(//img[@title='Sil'])[2]");
    driver.findElement(by).click();

    // 44. Run Click Until Gone
    GeneratedUtils.sleep(500);
    clickUntilGone = NetahsilatUtills.clickUntilGone(30);
    by = By.xpath("//button[. = 'Tamam']");
    clickUntilGone = (NetahsilatUtills.ClickUntilGone)((ReportingDriver)driver).addons().execute(clickUntilGone, by, -1);

  }

  @Override
  public ReportingDriver getDriver() {
    return (ReportingDriver) driver;
  }

  @AfterAll
  static void tearDown() {
    if (driver != null) {
      driver.quit();
    }
  }

  private static Stream provideParameters() throws Exception {
    return Stream.of(Arguments.of("https://otomasyon.netahsilatdemo.com/Account/LogOff","","",""));
  }
}
