package netahsilat;

import io.testproject.addon.JSActions;
import io.testproject.addon.NetahsilatUtills;
import io.testproject.addon.WebExtensions;
import io.testproject.sdk.drivers.ReportingDriver;
import io.testproject.sdk.drivers.web.RemoteWebDriver;
import io.testproject.sdk.interfaces.junit5.ExceptionsReporter;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.concurrent.TimeUnit;
import java.util.stream.Stream;

/**
 * This class was automatically generated by TestProject
 * Project: Quality Museum Project
 * Test: C724 Sanal Pos ekleme/güncelleme/silme(parametreler dahil) - Akbank
 * Generated by: Ahmet Furkan SIMSEK (furkan.simsek@qualitymuseum.com)
 * Generated on Fri Oct 07 11:26:49 GMT 2022.
 */
@DisplayName("C724 Sanal Pos ekleme/güncelleme/silme(parametreler dahil) - Akbank")
public class C724 implements ExceptionsReporter {
  public static WebDriver driver;

  @BeforeAll
  static void setup() throws Exception {
    driver = new RemoteWebDriver("wThDxIHw4zNaCydjAhcfe81WrQPYlMBFI7FPwUwV8M41", new ChromeOptions(), "Ahmet Furkan SIMSEK");
  }

  /**
   * In order to upload the test to TestProject need to un-comment @ArgumentsSource and set in comment the @MethodSource
   * @org.junit.jupiter.params.provider.ArgumentsSource(io.testproject.sdk.interfaces.parameterization.TestProjectParameterizer.class) */
  @DisplayName("C724 Sanal Pos ekleme/güncelleme/silme(parametreler dahil) - Akbank")
  @ParameterizedTest
  @MethodSource("provideParameters")
  void execute(String ApplicationURL, String userName, String password) throws Exception {
    // set timeout for driver actions (similar to step timeout)
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);
    By by;
    boolean booleanResult;
    MethodRefreshLoadingControl methodrefreshloadingcontrol;
    MethodLogoutlogin methodlogoutlogin;
    WebExtensions.SelectOptionbyVisibleText selectOptionbyVisibleText;
    JSActions.ClickAction clickAction;
    NetahsilatUtills.ClickUntilGone clickUntilGone;

    // 1. Run Method Logout&Login
    GeneratedUtils.sleep(500);
    methodlogoutlogin = new MethodLogoutlogin();
    methodlogoutlogin.ApplicationURL = ApplicationURL;
    methodlogoutlogin.userName = ProjectParameters.genelEmail;
    methodlogoutlogin.password = ProjectParameters.genelPassword;
    methodlogoutlogin.execute(driver);

    // 2. Click 'SANAL POSLAR'
    clickAction = JSActions.getClickAction();
    by = By.xpath("//a[. = 'SANAL POSLAR']");
    clickAction = (JSActions.ClickAction)((ReportingDriver)driver).addons().execute(clickAction, by, -1);

    // 3. This test was auto generated from steps of the 'C1909-Listelerde ki verilerin maskelenmesi' test
    methodrefreshloadingcontrol = new MethodRefreshLoadingControl();
    methodrefreshloadingcontrol.execute(driver);

    // 4. Click 'Yeni Sanal Pos Ekle'
    by = By.xpath("//a[. = 'Yeni Sanal Pos Ekle']");
    driver.findElement(by).click();

    // 5. Click 'Banka Posları Radio Button'
    by = By.cssSelector("input[type='radio'][name='PosApiTypeSystemId'][value='10']");
    driver.findElement(by).click();

    // 6. Type 'Otomasyon posu (Silinen)' in 'Name'
    by = By.cssSelector("#Name");
    driver.findElement(by).sendKeys("Otomasyon posu (Silinen)");

    // 7. Type 'Otomasyon tarafından oluşturulup silinen pos' in 'Explanation'
    by = By.cssSelector("#Explanation");
    driver.findElement(by).sendKeys("Otomasyon tarafından oluşturulup silinen pos");

    // 8. Type '45643565676' in 'input[id='Code']'
    by = By.cssSelector("input[id='Code']");
    driver.findElement(by).sendKeys("45643565676");

    // 9. Type '876758694' in 'ErpCode'
    by = By.cssSelector("#ErpCode");
    driver.findElement(by).sendKeys("876758694");

    // 10. Is 'VPosApiId' is clickable?
    //    Sanal Pos seçim alanı disabled kontrolü
    by = By.cssSelector("#VPosApiId");
    (new WebDriverWait(driver, 15)).until(ExpectedConditions.elementToBeClickable(by));

    // 11. Select options in 'VPosApiId' with text '[NONE]'
    //    Akbank
    selectOptionbyVisibleText = WebExtensions.selectOptionbyVisibleText("Akbank");
    by = By.cssSelector("#VPosApiId");
    selectOptionbyVisibleText = (WebExtensions.SelectOptionbyVisibleText)((ReportingDriver)driver).addons().execute(selectOptionbyVisibleText, by, -1);

    // 12. Select options in 'VPosApiCurrencyId' with text '[NONE]'
    selectOptionbyVisibleText = WebExtensions.selectOptionbyVisibleText("TL");
    by = By.cssSelector("#VPosApiCurrencyId");
    selectOptionbyVisibleText = (WebExtensions.SelectOptionbyVisibleText)((ReportingDriver)driver).addons().execute(selectOptionbyVisibleText, by, -1);

    // 13. Click 'axessPNG'
    by = By.xpath("(//img[contains(@src,'axess.png')])[2]");
    driver.findElement(by).click();

    // 14. Click '3D aktif'
    by = By.xpath("//label[@for='Is3DAvailable']/..//..//img");
    driver.findElement(by).click();

    // 15. Click 'CVV Kullanılsın'
    by = By.xpath("//label[@for='IsCVVUse']/..//..//img");
    driver.findElement(by).click();

    // 16. Click 'Bayi Ödeme Servisinde Aktif'
    by = By.xpath("//label[@for='IsVendorPaymentServiceActive']/..//..//img");
    driver.findElement(by).click();

    // 17. Click 'Merchant Safe Aktif'
    by = By.xpath("//label[@for='IsMerchantSafeEnabled']/..//..//img");
    driver.findElement(by).click();

    // 18. Click 'Aktif'
    by = By.xpath("//label[@for='IsActive']/..//..//img");
    driver.findElement(by).click();

    // 19. Type '2834723874' in 'BranchCode'
    by = By.cssSelector("#BranchCode");
    driver.findElement(by).sendKeys("2834723874");

    // 20. Type '2837423840' in 'BankAccountNumber'
    by = By.cssSelector("#BankAccountNumber");
    driver.findElement(by).sendKeys("2837423840");

    // 21. Type 'NL63ABNA7864733042' in 'IBAN'
    by = By.cssSelector("#IBAN");
    driver.findElement(by).sendKeys("NL63ABNA7864733042");

    // 22. Click 'Komisyon Oranları'
    by = By.cssSelector("a[href='#tab-comission']");
    driver.findElement(by).click();

    // 23. Type '1' in 'Installment'
    by = By.cssSelector("[name='Installment']");
    driver.findElement(by).sendKeys("1");

    // 24. Type '0' in 'CommRate6'
    by = By.cssSelector("[name='CommRate']");
    driver.findElement(by).sendKeys("0");

    // 25. Type '0' in 'ServiceCommRate'
    by = By.cssSelector("[name='ServiceCommRate']");
    driver.findElement(by).sendKeys("0");

    // 26. Type '0' in 'PlusInstalment'
    by = By.cssSelector("[name='PlusInstalment']");
    driver.findElement(by).sendKeys("0");

    // 27. Click 'TaksitEKle'
    by = By.cssSelector("input[value='Ekle']");
    driver.findElement(by).click();

    // 28. Run Click Until Gone
    clickUntilGone = NetahsilatUtills.clickUntilGone(30);
    by = By.xpath("//button[. = 'Tamam']");
    clickUntilGone = (NetahsilatUtills.ClickUntilGone)((ReportingDriver)driver).addons().execute(clickUntilGone, by, -1);

    // 29. This test was auto generated from steps of the 'C1909-Listelerde ki verilerin maskelenmesi' test
    methodrefreshloadingcontrol = new MethodRefreshLoadingControl();
    methodrefreshloadingcontrol.execute(driver);

    // 30. Click 'Sanal Pos Sayfalama Button'
    by = By.cssSelector("span[class='t-icon t-arrow-down']");
    driver.findElement(by).click();

    // 31. Click 'Grid 500 Liste'
    by = By.xpath("//div[@class = 't-animation-container' and contains(@style, 'display: block;')]//li[. = '500']");
    driver.findElement(by).click();

    // 32. Is '//td[text()='Otomasyon posu (Silinen)']' visible?
    by = By.xpath("//td[text()='Otomasyon posu (Silinen)']");
    driver.findElement(by).isDisplayed();

    // 33. Click 'Sanal Pos Güncelle = Otomasyon posu (Silinen)'
    by = By.xpath("//td[text()='Otomasyon posu (Silinen)']/..//a[@title='Sanal Pos Güncelle']//img");
    driver.findElement(by).click();

    // 34. Does 'Name' contain 'Otomasyon posu (Silinen)'?
    by = By.cssSelector("#Name");
    Assertions.assertTrue(driver.findElement(by).getText().contains("Otomasyon posu (Silinen)"));

    // 35. Does 'Explanation' contain 'Otomasyon tarafından oluşturulup silinen pos'?
    by = By.cssSelector("#Explanation");
    Assertions.assertTrue(driver.findElement(by).getText().contains("Otomasyon tarafından oluşturulup silinen pos"));

    // 36. Does 'input[id='Code']' contain '45643565676'?
    by = By.cssSelector("input[id='Code']");
    Assertions.assertTrue(driver.findElement(by).getText().contains("45643565676"));

    // 37. Does 'ErpCode' contain '876758694'?
    by = By.cssSelector("#ErpCode");
    Assertions.assertTrue(driver.findElement(by).getText().contains("876758694"));

    // 38. Does 'VPosApiCurrencyId' contain 'TL'?
    by = By.cssSelector("#VPosApiCurrencyId");
    Assertions.assertTrue(driver.findElement(by).getText().contains("TL"));

    // 39. Does 'BranchCode' contain '2834723874'?
    by = By.cssSelector("#BranchCode");
    Assertions.assertTrue(driver.findElement(by).getText().contains("2834723874"));

    // 40. Does 'BankAccountNumber' contain '2837423840'?
    by = By.cssSelector("#BankAccountNumber");
    Assertions.assertTrue(driver.findElement(by).getText().contains("2837423840"));

    // 41. Does 'IBAN' contain 'NL63ABNA7864733042'?
    by = By.cssSelector("#IBAN");
    Assertions.assertTrue(driver.findElement(by).getText().contains("NL63ABNA7864733042"));

    // 42. Click 'Vazgeç'
    by = By.xpath("//button[. = 'Vazgeç']");
    driver.findElement(by).click();

    // 43. Click 'Paremetreler Otomasyon posu (Silinen)'
    by = By.xpath("//td[text()='Otomasyon posu (Silinen)']/..//a[@title='Parametreler']//img");
    driver.findElement(by).click();

    // 44. Type '58746548765' in 'listItemModel[1].VendorVPosParameterV...'
    by = By.cssSelector("[id = 'listItemModel[1].VendorVPosParameterValue']");
    driver.findElement(by).sendKeys("58746548765");

    // 45. Type '385723048' in 'GroupId Input'
    by = By.xpath("//label[contains(text(),'GroupId ')]/../following-sibling::td/input[@type='text']");
    driver.findElement(by).sendKeys("385723048");

    // 46. Clear 'listItemModel[4].VendorVPosParameterV...' contents
    by = By.cssSelector("[id = 'listItemModel[4].VendorVPosParameterValue']");
    driver.findElement(by).clear();

    // 47. Type '84237503482' in 'listItemModel[4].VendorVPosParameterV...'
    by = By.cssSelector("[id = 'listItemModel[4].VendorVPosParameterValue']");
    driver.findElement(by).sendKeys("84237503482");

    // 48. Type '74569237456' in 'listItemModel[6].VendorVPosParameterV...'
    by = By.cssSelector("[id = 'listItemModel[6].VendorVPosParameterValue']");
    driver.findElement(by).sendKeys("74569237456");

    // 49. Type '938278465673' in 'listItemModel[8].VendorVPosParameterV...'
    by = By.cssSelector("[id = 'listItemModel[8].VendorVPosParameterValue']");
    driver.findElement(by).sendKeys("938278465673");

    // 50. Run Click Until Gone
    clickUntilGone = NetahsilatUtills.clickUntilGone(30);
    by = By.xpath("//button[. = 'Tamam']");
    clickUntilGone = (NetahsilatUtills.ClickUntilGone)((ReportingDriver)driver).addons().execute(clickUntilGone, by, -1);

    // 51. Click 'Paremetreler Otomasyon posu (Silinen)'
    by = By.xpath("//td[text()='Otomasyon posu (Silinen)']/..//a[@title='Parametreler']//img");
    driver.findElement(by).click();

    // 52. Does '3DPostUrl' contain 'https://www.sanalakpos.com/servlet/est3Dgate'?
    by = By.xpath("//label[contains(text(),'3DPostUrl')]/../following-sibling::td/input[@type='text']");
    Assertions.assertTrue(driver.findElement(by).getText().contains("https://www.sanalakpos.com/servlet/est3Dgate"));

    // 53. Does 'listItemModel[1].VendorVPosParameterV...' contain '58746548765'?
    by = By.cssSelector("[id = 'listItemModel[1].VendorVPosParameterValue']");
    Assertions.assertTrue(driver.findElement(by).getText().contains("58746548765"));

    // 54. Does 'GroupId Input' contain '385723048'?
    by = By.xpath("//label[contains(text(),'GroupId ')]/../following-sibling::td/input[@type='text']");
    Assertions.assertTrue(driver.findElement(by).getText().contains("385723048"));

    // 55. Does 'listItemModel[4].VendorVPosParameterV...' contain '84237503482'?
    by = By.cssSelector("[id = 'listItemModel[4].VendorVPosParameterValue']");
    Assertions.assertTrue(driver.findElement(by).getText().contains("84237503482"));

    // 56. Does 'listItemModel[6].VendorVPosParameterV...' contain '[NONE]'?
    by = By.cssSelector("[id = 'listItemModel[6].VendorVPosParameterValue']");
    Assertions.assertTrue(driver.findElement(by).getText().contains(""));

    // 57. Does 'listItemModel[7].VendorVPosParameterV...' contain 'https://www.sanalakpos.com/servlet/cc5ApiServer'?
    by = By.cssSelector("[id = 'listItemModel[7].VendorVPosParameterValue']");
    Assertions.assertTrue(driver.findElement(by).getText().contains("https://www.sanalakpos.com/servlet/cc5ApiServer"));

    // 58. Does 'listItemModel[8].VendorVPosParameterV...' contain '938278465673'?
    by = By.cssSelector("[id = 'listItemModel[8].VendorVPosParameterValue']");
    Assertions.assertTrue(driver.findElement(by).getText().contains("938278465673"));

    // 59. Click 'Vazgeç'
    by = By.xpath("//button[. = 'Vazgeç']");
    driver.findElement(by).click();

    // 60. Click 'Sil Otomasyon posu (Silinen)'
    by = By.xpath("//td[text()='Otomasyon posu (Silinen)']/..//a[@title='Sil']//img");
    driver.findElement(by).click();

    // 61. Click 'Tamam1'
    by = By.xpath("//button[. = 'Tamam']");
    driver.findElement(by).click();

    // 62. This test was auto generated from steps of the 'C1909-Listelerde ki verilerin maskelenmesi' test
    methodrefreshloadingcontrol = new MethodRefreshLoadingControl();
    methodrefreshloadingcontrol.execute(driver);

    // 63. Is '//td[text()='Otomasyon posu (Silinen)']' not present or invisible?
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(2000, TimeUnit.MILLISECONDS);
    by = By.xpath("//td[text()='Otomasyon posu (Silinen)']");
    (new WebDriverWait(driver, 2)).until(ExpectedConditions.invisibilityOf(driver.findElement(by)));
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

  }

  @Override
  public ReportingDriver getDriver() {
    return (ReportingDriver) driver;
  }

  @AfterAll
  static void tearDown() {
    if (driver != null) {
      driver.quit();
    }
  }

  private static Stream provideParameters() throws Exception {
    return Stream.of(Arguments.of("https://otomasyon.netahsilatdemo.com/Account/LogOff","otomasyon@test.com","Kd!cyhz4"));
  }
}
