package netahsilat;

import io.testproject.addon.JSActions;
import io.testproject.addon.NetahsilatUtills;
import io.testproject.addon.WebExtensions;
import io.testproject.sdk.drivers.ReportingDriver;
import io.testproject.sdk.drivers.web.RemoteWebDriver;
import io.testproject.sdk.interfaces.junit5.ExceptionsReporter;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.concurrent.TimeUnit;
import java.util.stream.Stream;

/**
 * This class was automatically generated by TestProject
 * Project: Quality Museum Project
 * Test: C749 Üye Excel Aktarım (Alt Bayi)
 * Generated by: Ahmet Furkan SIMSEK (furkan.simsek@qualitymuseum.com)
 * Generated on Fri Oct 07 10:13:15 GMT 2022.
 */
@DisplayName("C749 Üye Excel Aktarım (Alt Bayi)")
public class C749 implements ExceptionsReporter {
  public static WebDriver driver;

  @BeforeAll
  static void setup() throws Exception {
    driver = new RemoteWebDriver("wThDxIHw4zNaCydjAhcfe81WrQPYlMBFI7FPwUwV8M41", new ChromeOptions(), "Ahmet Furkan SIMSEK");
  }

  /**
   * In order to upload the test to TestProject need to un-comment @ArgumentsSource and set in comment the @MethodSource
   * @org.junit.jupiter.params.provider.ArgumentsSource(io.testproject.sdk.interfaces.parameterization.TestProjectParameterizer.class) */
  @DisplayName("C749 Üye Excel Aktarım (Alt Bayi)")
  @ParameterizedTest
  @MethodSource("provideParameters")
  void execute(String ApplicationURL, String userName, String password) throws Exception {
    // set timeout for driver actions (similar to step timeout)
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);
    By by;
    boolean booleanResult;
    MethodLogoutlogin methodlogoutlogin;
    WebExtensions.SelectOptionbyVisibleText selectOptionbyVisibleText;
    NetahsilatUtills.ClickUntilGone clickUntilGone;
    JSActions.ClickAction clickAction;
    FileUpload.UploadFileElementAction uploadFileElementAction;

    // 1. Run Method Logout&Login
    GeneratedUtils.sleep(500);
    methodlogoutlogin = new MethodLogoutlogin();
    methodlogoutlogin.ApplicationURL = ApplicationURL;
    methodlogoutlogin.userName = ProjectParameters.genelEmail;
    methodlogoutlogin.password = ProjectParameters.genelPassword;
    methodlogoutlogin.execute(driver);

    // 2. Move mouse to 'moveUstUyeYonetimi'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("li[class='content']");
    (new Actions(driver)).moveToElement(driver.findElement(by)).perform();

    // 3. Click 'ustUyeYonetimi'
    GeneratedUtils.sleep(500);
    by = By.xpath("//li[4]/a[. = 'ÜYE YÖNETİMİ']");
    driver.findElement(by).click();

    // 4. Click 'ÜYE AKTARIM'
    GeneratedUtils.sleep(500);
    by = By.xpath("//a[. = 'ÜYE AKTARIM']");
    driver.findElement(by).click();

    // 5. Uploads a file to a given element with the 'file' type
    GeneratedUtils.sleep(500);
    uploadFileElementAction = FileUpload.uploadFileElementAction("C:\\TestProject\\C749.xlsx");
    by = By.cssSelector("#import");
    uploadFileElementAction = (FileUpload.UploadFileElementAction)((ReportingDriver)driver).addons().execute(uploadFileElementAction, by, -1);

    // 6. Click 'Tamam1'
    GeneratedUtils.sleep(500);
    by = By.xpath("//button[. = 'Tamam']");
    driver.findElement(by).click();

    // 7. Select options in 'primarykey' with text '[NONE]'
    GeneratedUtils.sleep(500);
    selectOptionbyVisibleText = WebExtensions.selectOptionbyVisibleText("Code");
    by = By.cssSelector("#primarykey");
    selectOptionbyVisibleText = (WebExtensions.SelectOptionbyVisibleText)((ReportingDriver)driver).addons().execute(selectOptionbyVisibleText, by, -1);

    // 8. Is 'Aktarımı Başlat' is clickable?
    GeneratedUtils.sleep(500);
    by = By.xpath("//button[. = 'Aktarımı Başlat']");
    (new WebDriverWait(driver, 15)).until(ExpectedConditions.elementToBeClickable(by));

    // 9. Click 'Aktarımı Başlat'
    GeneratedUtils.sleep(500);
    by = By.xpath("//button[. = 'Aktarımı Başlat']");
    driver.findElement(by).click();

    // 10. Does 'P3' contain 'Kaydedilen Toplam Kayıt : 2 Hata Oluşan Toplam Kayıt :0'?
    GeneratedUtils.sleep(500);
    by = By.xpath("//div/div[1]/p");
    Assertions.assertTrue(driver.findElement(by).getText().contains("Kaydedilen Toplam Kayıt : 2 Hata Oluşan Toplam Kayıt :0"));

    // 11. Click 'altUyeYonetimi'
    GeneratedUtils.sleep(500);
    clickAction = JSActions.getClickAction();
    by = By.xpath("//li[1]/a[. = 'ÜYE YÖNETİMİ']");
    clickAction = (JSActions.ClickAction)((ReportingDriver)driver).addons().execute(clickAction, by, -1);

    // 12. Is 'SearchVendorName' visible?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#SearchVendorName");
    driver.findElement(by).isDisplayed();

    // 13. Type 'AltKurCodeErp01' in 'SearchVendorName'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#SearchVendorName");
    driver.findElement(by).sendKeys("AltKurCodeErp01");

    // 14. Click '//div[contains(text(),'AltKurCodeErp01')]'
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(35000, TimeUnit.MILLISECONDS);
    GeneratedUtils.sleep(500);
    by = By.xpath("//div[contains(text(),'AltKurCodeErp01')]");
    driver.findElement(by).click();
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 15. Click 'btnListele'
    GeneratedUtils.sleep(500);
    by = By.xpath("//button[. = 'Listele']");
    driver.findElement(by).click();

    // 16. Is '//tr[1]//td[. = 'AltKurCode01']' visible?
    GeneratedUtils.sleep(500);
    by = By.xpath("//tr[1]//td[. = 'AltKurCode01']");
    driver.findElement(by).isDisplayed();

    // 17. Click 'EditButton'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("img[src*='fugue/edit.png']");
    driver.findElement(by).click();

    // 18. Does 'Entity.Email' contain 'kurumsalaltbayi@test.com'?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_Email");
    Assertions.assertTrue(driver.findElement(by).getText().contains("kurumsalaltbayi@test.com"));

    // 19. Does 'Entity.AddressModel.Address' contain 'Gazeteciler sit. Kelebek çıkmazı sk.'?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_AddressModel_Address");
    Assertions.assertTrue(driver.findElement(by).getText().contains("Gazeteciler sit. Kelebek çıkmazı sk."));

    // 20. Does 'Entity.ContactModel.Phone1Number' contain '(212)6635858'?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_ContactModel_Phone1Number");
    Assertions.assertTrue(driver.findElement(by).getText().contains("(212)6635858"));

    // 21. Does 'Entity.ErpCode' contain 'AltKurCodeErp01'?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_ErpCode");
    Assertions.assertTrue(driver.findElement(by).getText().contains("AltKurCodeErp01"));

    // 22. Is 'input[vendortype='Company']:checked' visible?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("input[vendortype='Company']:checked");
    driver.findElement(by).isDisplayed();

    // 23. Is '//input[@id='Entity_IsActive']/..//span[contains(@class,'checked')]' visible?
    GeneratedUtils.sleep(500);
    by = By.xpath("//input[@id='Entity_IsActive']/..//span[contains(@class,'checked')]");
    driver.findElement(by).isDisplayed();

    // 24. Click 'btnCariHesaplar'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("img[src*='Paper-Money-icon.png']");
    driver.findElement(by).click();

    // 25. Is 'Entity.CurrentAccounts[0].ErpCode' visible?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_CurrentAccounts_0__ErpCode");
    driver.findElement(by).isDisplayed();

    // 26. Run Click Until Gone
    GeneratedUtils.sleep(500);
    clickUntilGone = NetahsilatUtills.clickUntilGone(30);
    by = By.xpath("//button[. = 'Vazgeç']");
    clickUntilGone = (NetahsilatUtills.ClickUntilGone)((ReportingDriver)driver).addons().execute(clickUntilGone, by, -1);

    // 27. Click 'KullanıcılarıGörüntüleImage'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("img[src*='fugue/detail.png']");
    driver.findElement(by).click();

    // 28. Click 'btnPencil'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("img[src*='fugue/pencil.png']");
    driver.findElement(by).click();

    // 29. Is '//input[@id='Entity_IsActive']/..//span[contains(@class,'checked')]' visible?
    GeneratedUtils.sleep(500);
    by = By.xpath("//input[@id='Entity_IsActive']/..//span[contains(@class,'checked')]");
    driver.findElement(by).isDisplayed();

    // 30. Does 'Bayi Adi' contain 'Alt Bayi Kurumsal Name'?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_Name");
    Assertions.assertTrue(driver.findElement(by).getText().contains("Alt Bayi Kurumsal Name"));

    // 31. Does 'Entity.Surname' contain 'Alt Bayi Bireysel Name'?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_Surname");
    Assertions.assertTrue(driver.findElement(by).getText().contains("Alt Bayi Bireysel Name"));

    // 32. Does 'Entity.Email' contain 'kurumsalaltbayi@test.com'?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_Email");
    Assertions.assertTrue(driver.findElement(by).getText().contains("kurumsalaltbayi@test.com"));

    // 33. Does 'Entity.MobilePhone' contain '(555)2345678'?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_MobilePhone");
    Assertions.assertTrue(driver.findElement(by).getText().contains("(555)2345678"));

    // 34. Does 'Entity.SelectedCountry' contain 'Turkey'?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_SelectedCountry");
    Assertions.assertTrue(driver.findElement(by).getText().contains("Turkey"));

    // 35. Does 'Entity.Code' contain 'AltKurCode01'?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_Code");
    Assertions.assertTrue(driver.findElement(by).getText().contains("AltKurCode01"));

    // 36. Run Click Until Gone
    GeneratedUtils.sleep(500);
    clickUntilGone = NetahsilatUtills.clickUntilGone(30);
    by = By.xpath("//button[. = 'Vazgeç']");
    clickUntilGone = (NetahsilatUtills.ClickUntilGone)((ReportingDriver)driver).addons().execute(clickUntilGone, by, -1);

    // 37. Click 'Rol/Ekle Çıkar'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("img[src*='question.png']");
    driver.findElement(by).click();

    // 38. Does 'RoleGroupId' contain 'Alt Bayi Admin'?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("[name='RoleGroupId']");
    Assertions.assertTrue(driver.findElement(by).getText().contains("Alt Bayi Admin"));

    // 39. Run Click Until Gone
    GeneratedUtils.sleep(500);
    clickUntilGone = NetahsilatUtills.clickUntilGone(30);
    by = By.xpath("//button[. = 'Vazgeç']");
    clickUntilGone = (NetahsilatUtills.ClickUntilGone)((ReportingDriver)driver).addons().execute(clickUntilGone, by, -1);

    // 40. Click 'Kullanıcı Silme'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("img[src$$='/trash.png']");
    driver.findElement(by).click();

    // 41. Run Click Until Gone
    GeneratedUtils.sleep(500);
    clickUntilGone = NetahsilatUtills.clickUntilGone(30);
    by = By.xpath("//button[. = 'Tamam']");
    clickUntilGone = (NetahsilatUtills.ClickUntilGone)((ReportingDriver)driver).addons().execute(clickUntilGone, by, -1);

    // 42. Does 'Gösterilecek Kayıt Bulunamadı.2' contain 'Gösterilecek Kayıt Bulunamadı.'?
    GeneratedUtils.sleep(500);
    by = By.xpath("//div[3]/div/table//td[. = 'Gösterilecek Kayıt Bulunamadı.']");
    Assertions.assertTrue(driver.findElement(by).getText().contains("Gösterilecek Kayıt Bulunamadı."));

    // 43. Clear 'SearchVendorName' contents
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#SearchVendorName");
    driver.findElement(by).clear();

    // 44. Type 'AltBirKurCode02' in 'SearchVendorName'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#SearchVendorName");
    driver.findElement(by).sendKeys("AltBirKurCode02");

    // 45. Click '//div[contains(text(),'AltBirKurCode02')]'
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(35000, TimeUnit.MILLISECONDS);
    GeneratedUtils.sleep(500);
    by = By.xpath("//div[contains(text(),'AltBirKurCode02')]");
    driver.findElement(by).click();
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 46. Click 'btnListele'
    GeneratedUtils.sleep(500);
    by = By.xpath("//button[. = 'Listele']");
    driver.findElement(by).click();

    // 47. Is 'AltBirKurCode02' visible?
    GeneratedUtils.sleep(500);
    by = By.xpath("//td[. = 'AltBirKurCode02']");
    driver.findElement(by).isDisplayed();

    // 48. Does 'Bireysel Ana Bayi (Silmeyiniz-Değişti...4' contain 'Bireysel Ana Bayi (Silmeyiniz-Değiştirmeyiniz)'?
    GeneratedUtils.sleep(500);
    by = By.xpath("//a[. = 'Bireysel Ana Bayi (Silmeyiniz-Değiştirmeyiniz)']");
    Assertions.assertTrue(driver.findElement(by).getText().contains("Bireysel Ana Bayi (Silmeyiniz-Değiştirmeyiniz)"));

    // 49. Click 'EditButton'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("img[src*='fugue/edit.png']");
    driver.findElement(by).click();

    // 50. Does 'Entity.Email' contain 'bireyselaltbayi@test.com'?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_Email");
    Assertions.assertTrue(driver.findElement(by).getText().contains("bireyselaltbayi@test.com"));

    // 51. Is 'input[vendortype='Individual']:checked' visible?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("input[vendortype='Individual']:checked");
    driver.findElement(by).isDisplayed();

    // 52. Does 'Entity.ErpCode' contain 'AltBirCodeErp02'?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_ErpCode");
    Assertions.assertTrue(driver.findElement(by).getText().contains("AltBirCodeErp02"));

    // 53. Does 'Entity.ContactModel.Phone1Number' contain '(212)6635859'?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_ContactModel_Phone1Number");
    Assertions.assertTrue(driver.findElement(by).getText().contains("(212)6635859"));

    // 54. Does 'Entity.AddressModel.Address' contain 'Gazeteciler sit. Kelebek çıkmazı sk.'?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_AddressModel_Address");
    Assertions.assertTrue(driver.findElement(by).getText().contains("Gazeteciler sit. Kelebek çıkmazı sk."));

    // 55. Click 'btnCariHesaplar'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("img[src*='Paper-Money-icon.png']");
    driver.findElement(by).click();

    // 56. Is 'Entity.CurrentAccounts[0].ErpCode' visible?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_CurrentAccounts_0__ErpCode");
    driver.findElement(by).isDisplayed();

    // 57. Run Click Until Gone
    GeneratedUtils.sleep(500);
    clickUntilGone = NetahsilatUtills.clickUntilGone(30);
    by = By.xpath("//button[. = 'Vazgeç']");
    clickUntilGone = (NetahsilatUtills.ClickUntilGone)((ReportingDriver)driver).addons().execute(clickUntilGone, by, -1);

    // 58. Click 'KullanıcılarıGörüntüleImage'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("img[src*='fugue/detail.png']");
    driver.findElement(by).click();

    // 59. Click 'btnPencil'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("img[src*='fugue/pencil.png']");
    driver.findElement(by).click();

    // 60. Does 'Bayi Adi' contain 'Alt Bayi Bireysel Name'?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_Name");
    Assertions.assertTrue(driver.findElement(by).getText().contains("Alt Bayi Bireysel Name"));

    // 61. Does 'Entity.Surname' contain 'Alt Bayi Kurumsal Name'?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_Surname");
    Assertions.assertTrue(driver.findElement(by).getText().contains("Alt Bayi Kurumsal Name"));

    // 62. Does 'Entity.Email' contain 'bireyselaltbayi@test.com'?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_Email");
    Assertions.assertTrue(driver.findElement(by).getText().contains("bireyselaltbayi@test.com"));

    // 63. Does 'Entity.MobilePhone' contain '(555)2345679'?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_MobilePhone");
    Assertions.assertTrue(driver.findElement(by).getText().contains("(555)2345679"));

    // 64. Does 'Entity.SelectedCountry' contain 'Turkey'?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_SelectedCountry");
    Assertions.assertTrue(driver.findElement(by).getText().contains("Turkey"));

    // 65. Does 'Entity.Code' contain 'AltBirKurCode02'?
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#Entity_Code");
    Assertions.assertTrue(driver.findElement(by).getText().contains("AltBirKurCode02"));

    // 66. Is '//input[@id='Entity_IsActive']/..//span[contains(@class,'checked')]' visible?
    GeneratedUtils.sleep(500);
    by = By.xpath("//input[@id='Entity_IsActive']/..//span[contains(@class,'checked')]");
    driver.findElement(by).isDisplayed();

    // 67. Run Click Until Gone
    GeneratedUtils.sleep(500);
    clickUntilGone = NetahsilatUtills.clickUntilGone(30);
    by = By.xpath("//button[. = 'Vazgeç']");
    clickUntilGone = (NetahsilatUtills.ClickUntilGone)((ReportingDriver)driver).addons().execute(clickUntilGone, by, -1);

    // 68. Click 'Kullanıcı Silme'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("img[src$$='/trash.png']");
    driver.findElement(by).click();

    // 69. Run Click Until Gone
    GeneratedUtils.sleep(500);
    clickUntilGone = NetahsilatUtills.clickUntilGone(30);
    by = By.xpath("//button[. = 'Tamam']");
    clickUntilGone = (NetahsilatUtills.ClickUntilGone)((ReportingDriver)driver).addons().execute(clickUntilGone, by, -1);

    // 70. Is 'Refresh' visible?
    // set step-specific timeout (will undo this at the end)
    driver.manage().timeouts().implicitlyWait(80000, TimeUnit.MILLISECONDS);
    GeneratedUtils.sleep(500);
    by = By.cssSelector("a[class='t-icon t-refresh']");
    driver.findElement(by).isDisplayed();
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);

    // 71. Does 'Gösterilecek Kayıt Bulunamadı.2' contain 'Gösterilecek Kayıt Bulunamadı.'?
    GeneratedUtils.sleep(500);
    by = By.xpath("//div[3]/div/table//td[. = 'Gösterilecek Kayıt Bulunamadı.']");
    Assertions.assertTrue(driver.findElement(by).getText().contains("Gösterilecek Kayıt Bulunamadı."));

  }

  @Override
  public ReportingDriver getDriver() {
    return (ReportingDriver) driver;
  }

  @AfterAll
  static void tearDown() {
    if (driver != null) {
      driver.quit();
    }
  }

  private static Stream provideParameters() throws Exception {
    return Stream.of(Arguments.of("https://otomasyon.netahsilatdemo.com/Account/LogOff","otomasyon@test.com","Kd!cyhz4"));
  }
}
