package netahsilat;

import io.testproject.addon.BasicAuthentication;
import io.testproject.addon.VisibleElementsOperations;
import io.testproject.sdk.drivers.ReportingDriver;
import io.testproject.sdk.interfaces.junit5.ExceptionsReporter;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

import java.util.concurrent.TimeUnit;

/**
 * This class was automatically generated by TestProject
 * Project: Quality Museum Project
 * Test: 01-Üyeliksiz Ödeme
 * Generated by: Ahmet Furkan SIMSEK (furkan.simsek@qualitymuseum.com)
 * Generated on Thu Sep 29 17:38:09 GMT 2022.
 */
public class Test01yeliksizdeme implements Test, ExceptionsReporter {
  public static WebDriver driver;

  /**
   * ApplicationURL test parameter
   */
  public String ApplicationURL = "https://otomasyon.netahsilatdemo.com/Account/LogOff";

  public void execute(WebDriver parentDriver) throws Exception {
    driver = parentDriver;
    // set timeout for driver actions (similar to step timeout)
    driver.manage().timeouts().implicitlyWait(15000, TimeUnit.MILLISECONDS);
    By by;
    boolean booleanResult;
    MethodGeneldeme methodgeneldeme;
    VisibleElementsOperations.ContainsTextIfVisibleWeb containsTextIfVisibleWeb;
    BasicAuthentication.NavigateToBasicAuth navigateToBasicAuth;

    // 1. Navigate to a URL that required basic authentication
    //    Navigates the specified URL (Auto-generated)
    GeneratedUtils.sleep(500);
    navigateToBasicAuth = BasicAuthentication.navigateToBasicAuth(ApplicationURL,"furkan.simsek","Gh024vTyk");
    navigateToBasicAuth = (BasicAuthentication.NavigateToBasicAuth)((ReportingDriver)driver).addons().execute(navigateToBasicAuth);

    // 2. Click 'buttonUyeliksizOdeme'
    //    Üyeliksiz Ödeme butonuna tıklanması
    GeneratedUtils.sleep(500);
    by = By.xpath("(//a[text()='Üyeliksiz Ödeme'])[2]");
    driver.findElement(by).click();

    // 3. Clear 'inputTutar' contents
    //    tutar alanının temizlenmesi
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#PureAmount");
    driver.findElement(by).clear();

    // 4. Type '750' in 'inputTutar'
    //    yeni tutarın girilmesi
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#PureAmount");
    driver.findElement(by).sendKeys("750");

    // 5. Run Method Genel Ödeme
    GeneratedUtils.sleep(500);
    methodgeneldeme = new MethodGeneldeme();
    methodgeneldeme.ApplicationURL = ApplicationURL;
    methodgeneldeme.execute(driver);

    // 6. Click 'odemeTalimatiOlustur'
    GeneratedUtils.sleep(500);
    by = By.cssSelector("input[value='ÖDEME TALİMATI OLUŞTUR']");
    driver.findElement(by).click();

    // 7. Click 'btnOdemeyiTamamla'
    //    Ödemeyi tamamla
    GeneratedUtils.sleep(500);
    by = By.cssSelector("#btnNormalPayment");
    driver.findElement(by).click();

    // 8. 'textIsleminizBasarili' contains text 'Referans Numarası'?
    GeneratedUtils.sleep(500);
    containsTextIfVisibleWeb = VisibleElementsOperations.containsTextIfVisibleWeb("Referans Numarası","");
    by = By.cssSelector("div[class='alert alert-success success-template']>p");
    containsTextIfVisibleWeb = (VisibleElementsOperations.ContainsTextIfVisibleWeb)((ReportingDriver)driver).addons().execute(containsTextIfVisibleWeb, by, -1);

  }

  @Override
  public ReportingDriver getDriver() {
    return (ReportingDriver) driver;
  }
}
